import React,{createContext,useContext,useEffect,useMemo,useState}from'react';

export const ADMIN_LOCALES=[
  {code:'en',label:'English',native:'English'},
  {code:'my',label:'Burmese',native:'မြန်မာ'},
  {code:'id',label:'Indonesian',native:'Bahasa Indonesia'},
];

const DICT={
 en:{
  'group.operate':'Operate','group.grow':'Grow','group.experience':'Experience','group.system':'System',
  'nav.dashboard':'Dashboard','nav.stores':'Stores','nav.orders':'Orders','nav.products':'Products','nav.media':'Media Library','nav.inventory':'Inventory','nav.customers':'Customers','nav.promotions':'Promotions','nav.payments':'Payments','nav.delivery':'Delivery','nav.experience':'Customer Experience','nav.languages':'Languages','nav.address':'Address Form','nav.cs':'Luke CS & AI','nav.profile':'My profile','nav.settings':'Store settings','nav.access':'Access & roles','nav.audit':'Audit log',
  'shell.tenant':'Tenant','shell.workspace':'Workspace','shell.store_context':'Store context','shell.primary_store':'Primary store','shell.live_api':'Live API','shell.sign_out':'Sign out','shell.language':'Admin language',
  'common.save':'Save draft','common.publish':'Publish','common.loading':'Loading…','common.retry':'Retry','common.enabled':'Enabled','common.disabled':'Disabled','common.remove':'Remove','common.add':'Add','common.default':'Default','common.language':'Language','common.optional':'Optional',
  'auth.kicker':'Merchant operations','auth.hero_title':'Run your store from one focused workspace.','auth.hero_desc':'Products, inventory, orders, customers, payments, delivery, promotions and storefront controls stay together without exposing platform-level complexity.','auth.capability_ops':'Daily operations','auth.capability_ops_desc':'Catalog, stock, orders and fulfillment in one flow.','auth.capability_roles':'Role-aware access','auth.capability_roles_desc':'Navigation and actions remain permission scoped.','auth.capability_store':'Store context','auth.capability_store_desc':'Switch between authorized stores without changing accounts.','auth.capability_tenant':'Tenant isolated','auth.capability_tenant_desc':'Every request stays inside the selected merchant tenant.','auth.welcome':'Welcome back','auth.signin_desc':'Sign in with the merchant account provisioned for your business.','auth.tenant':'Tenant slug','auth.tenant_placeholder':'your-business','auth.email':'Email address','auth.email_placeholder':'name@company.com','auth.password':'Password','auth.password_placeholder':'Enter your password','auth.password_hint':'Use the password assigned to this merchant account.','auth.signin':'Sign in to Merchant Admin','auth.opening':'Opening workspace…','auth.secure_session':'Secure tenant session','auth.help':'Authorized merchant staff only','auth.error_title':'Sign-in failed','auth.error_message':'The merchant session could not be started. Check your details and try again.',
  'languages.title':'Storefront Languages','languages.desc':'Enable up to four customer languages and enter merchant-owned translations manually.','languages.settings':'Language settings','languages.translations':'Translations','languages.default':'Default storefront language','languages.add':'Add language','languages.code':'Language code','languages.label':'Display name','languages.native':'Native label','languages.brand':'Store & SEO','languages.navigation':'Menu labels','languages.categories':'Categories','languages.products':'Products & modifiers','languages.home':'Home sections','languages.select_product':'Choose product','languages.no_product':'Choose a product to translate its content and modifier labels.','languages.saved':'Language draft saved','languages.published':'Language settings published',
  'address.title':'Delivery Address Form','address.desc':'Choose which customer address fields are included in Profile and Checkout.','address.fields':'Address fields','address.label':'Label','address.country':'Country code','address.line2':'Address line 2','address.postal':'Postal code','address.default_country':'Default country code','address.default_country_hint':'Used when Country code is hidden. Enter a two-letter ISO code such as IN, SG, MM or ID.','address.saved':'Address form draft saved','address.published':'Address form published',
 },
 my:{
  'group.operate':'လုပ်ငန်း','group.grow':'တိုးတက်မှု','group.experience':'ဖောက်သည်အတွေ့အကြုံ','group.system':'စနစ်',
  'nav.dashboard':'ဒက်ရှ်ဘုတ်','nav.stores':'စတိုးများ','nav.orders':'အော်ဒါများ','nav.products':'ကုန်ပစ္စည်းများ','nav.media':'မီဒီယာ','nav.inventory':'စတော့','nav.customers':'ဖောက်သည်များ','nav.promotions':'ပရိုမိုးရှင်း','nav.payments':'ငွေပေးချေမှု','nav.delivery':'ပို့ဆောင်မှု','nav.experience':'ဖောက်သည်အတွေ့အကြုံ','nav.languages':'ဘာသာစကားများ','nav.address':'လိပ်စာဖောင်','nav.cs':'Luke CS & AI','nav.profile':'ကျွန်ုပ်၏ပရိုဖိုင်','nav.settings':'စတိုးဆက်တင်','nav.access':'အသုံးပြုခွင့်','nav.audit':'မှတ်တမ်း',
  'shell.tenant':'Tenant','shell.workspace':'Workspace','shell.store_context':'စတိုး','shell.primary_store':'မူလစတိုး','shell.live_api':'Live API','shell.sign_out':'ထွက်မည်','shell.language':'Admin ဘာသာစကား',
  'common.save':'Draft သိမ်းမည်','common.publish':'ထုတ်ပြန်မည်','common.loading':'လုပ်ဆောင်နေသည်…','common.retry':'ထပ်စမ်းမည်','common.enabled':'ဖွင့်','common.disabled':'ပိတ်','common.remove':'ဖယ်ရှား','common.add':'ထည့်မည်','common.default':'မူလ','common.language':'ဘာသာစကား','common.optional':'ရွေးချယ်နိုင်',
  'auth.kicker':'Merchant လုပ်ငန်းစီမံခန့်ခွဲမှု','auth.hero_title':'သင့်စတိုးလုပ်ငန်းအားလုံးကို Workspace တစ်ခုထဲမှ စီမံပါ။','auth.hero_desc':'ကုန်ပစ္စည်း၊ စတော့၊ အော်ဒါ၊ ဖောက်သည်၊ ငွေပေးချေမှု၊ ပို့ဆောင်မှု၊ ပရိုမိုးရှင်းနှင့် Storefront ဆက်တင်များကို တစ်နေရာတည်းတွင် စီမံနိုင်သည်။','auth.capability_ops':'နေ့စဉ်လုပ်ငန်း','auth.capability_ops_desc':'Catalog မှ fulfillment အထိ တစ်ဆက်တည်းစီမံပါ။','auth.capability_roles':'Role အလိုက်အသုံးပြုခွင့်','auth.capability_roles_desc':'Menu နှင့် လုပ်ဆောင်ချက်များကို permission အလိုက်ကန့်သတ်ထားသည်။','auth.capability_store':'Store context','auth.capability_store_desc':'ခွင့်ပြုထားသော စတိုးများကို account မပြောင်းဘဲ ပြောင်းနိုင်သည်။','auth.capability_tenant':'Tenant သီးခြားခွဲထားမှု','auth.capability_tenant_desc':'Request တိုင်းကို ရွေးထားသော merchant tenant အတွင်းသာ လုပ်ဆောင်သည်။','auth.welcome':'ပြန်လည်ကြိုဆိုပါသည်','auth.signin_desc':'သင့်လုပ်ငန်းအတွက် သတ်မှတ်ထားသော merchant account ဖြင့် ဝင်ရောက်ပါ။','auth.tenant':'Tenant slug','auth.tenant_placeholder':'your-business','auth.email':'အီးမေးလ်','auth.email_placeholder':'name@company.com','auth.password':'စကားဝှက်','auth.password_placeholder':'စကားဝှက်ထည့်ပါ','auth.password_hint':'ဤ merchant account အတွက် သတ်မှတ်ထားသော စကားဝှက်ကို အသုံးပြုပါ။','auth.signin':'Merchant Admin သို့ ဝင်မည်','auth.opening':'Workspace ဖွင့်နေသည်…','auth.secure_session':'လုံခြုံသော tenant session','auth.help':'ခွင့်ပြုထားသော merchant staff များအတွက်သာ','auth.error_title':'ဝင်ရောက်မှု မအောင်မြင်ပါ','auth.error_message':'Merchant session စတင်မရပါ။ အချက်အလက်များကို စစ်ပြီး ထပ်စမ်းပါ။',
  'languages.title':'Storefront ဘာသာစကားများ','languages.desc':'ဖောက်သည်အတွက် ဘာသာစကား ၄ မျိုးအထိ ဖွင့်ပြီး ဘာသာပြန်စာကို Admin မှ ကိုယ်တိုင်ဖြည့်ပါ။','languages.settings':'ဘာသာစကားဆက်တင်','languages.translations':'ဘာသာပြန်များ','languages.default':'မူလ storefront ဘာသာစကား','languages.add':'ဘာသာစကားထည့်မည်','languages.code':'ဘာသာစကားကုဒ်','languages.label':'ပြသမည့်အမည်','languages.native':'မူရင်းအမည်','languages.brand':'စတိုးနှင့် SEO','languages.navigation':'Menu အမည်များ','languages.categories':'အမျိုးအစားများ','languages.products':'ကုန်ပစ္စည်းနှင့် Modifier','languages.home':'ပင်မစာမျက်နှာ','languages.select_product':'ကုန်ပစ္စည်းရွေးပါ','languages.no_product':'ကုန်ပစ္စည်းနှင့် modifier အမည်များ ဘာသာပြန်ရန် ကုန်ပစ္စည်းရွေးပါ။','languages.saved':'ဘာသာစကား Draft သိမ်းပြီး','languages.published':'ဘာသာစကားဆက်တင် ထုတ်ပြန်ပြီး',
  'address.title':'ပို့ဆောင်ရေးလိပ်စာဖောင်','address.desc':'Profile နှင့် Checkout တွင် ပြမည့် လိပ်စာအကွက်များကို ရွေးချယ်ပါ။','address.fields':'လိပ်စာအကွက်များ','address.label':'Label','address.country':'နိုင်ငံကုဒ်','address.line2':'လိပ်စာလိုင်း ၂','address.postal':'စာတိုက်ကုဒ်','address.default_country':'မူလနိုင်ငံကုဒ်','address.default_country_hint':'နိုင်ငံကုဒ်ကို ဖျောက်ထားသည့်အခါ အသုံးပြုမည်။ IN, SG, MM, ID ကဲ့သို့ ၂ လုံး ISO code ထည့်ပါ။','address.saved':'လိပ်စာ Draft သိမ်းပြီး','address.published':'လိပ်စာဖောင် ထုတ်ပြန်ပြီး',
 },
 id:{
  'group.operate':'Operasi','group.grow':'Pertumbuhan','group.experience':'Pengalaman','group.system':'Sistem',
  'nav.dashboard':'Dasbor','nav.stores':'Toko','nav.orders':'Pesanan','nav.products':'Produk','nav.media':'Pustaka Media','nav.inventory':'Inventaris','nav.customers':'Pelanggan','nav.promotions':'Promosi','nav.payments':'Pembayaran','nav.delivery':'Pengiriman','nav.experience':'Pengalaman Pelanggan','nav.languages':'Bahasa','nav.address':'Formulir Alamat','nav.cs':'Luke CS & AI','nav.profile':'Profil saya','nav.settings':'Pengaturan toko','nav.access':'Akses & peran','nav.audit':'Log audit',
  'shell.tenant':'Tenant','shell.workspace':'Workspace','shell.store_context':'Konteks toko','shell.primary_store':'Toko utama','shell.live_api':'Live API','shell.sign_out':'Keluar','shell.language':'Bahasa Admin',
  'common.save':'Simpan draf','common.publish':'Terbitkan','common.loading':'Memuat…','common.retry':'Coba lagi','common.enabled':'Aktif','common.disabled':'Nonaktif','common.remove':'Hapus','common.add':'Tambah','common.default':'Default','common.language':'Bahasa','common.optional':'Opsional',
  'auth.kicker':'Operasi merchant','auth.hero_title':'Kelola toko Anda dari satu workspace yang terfokus.','auth.hero_desc':'Produk, inventaris, pesanan, pelanggan, pembayaran, pengiriman, promosi, dan kontrol storefront tetap berada dalam satu tempat tanpa mengekspos kompleksitas platform.','auth.capability_ops':'Operasi harian','auth.capability_ops_desc':'Kelola katalog, stok, pesanan, dan fulfillment dalam satu alur.','auth.capability_roles':'Akses berbasis peran','auth.capability_roles_desc':'Navigasi dan tindakan tetap dibatasi oleh permission.','auth.capability_store':'Konteks toko','auth.capability_store_desc':'Beralih antar toko yang diizinkan tanpa mengganti akun.','auth.capability_tenant':'Tenant terisolasi','auth.capability_tenant_desc':'Setiap request tetap berada di dalam tenant merchant yang dipilih.','auth.welcome':'Selamat datang kembali','auth.signin_desc':'Masuk dengan akun merchant yang disediakan untuk bisnis Anda.','auth.tenant':'Slug tenant','auth.tenant_placeholder':'bisnis-anda','auth.email':'Alamat email','auth.email_placeholder':'nama@perusahaan.com','auth.password':'Kata sandi','auth.password_placeholder':'Masukkan kata sandi','auth.password_hint':'Gunakan kata sandi yang ditetapkan untuk akun merchant ini.','auth.signin':'Masuk ke Merchant Admin','auth.opening':'Membuka workspace…','auth.secure_session':'Sesi tenant aman','auth.help':'Khusus staf merchant yang berwenang','auth.error_title':'Gagal masuk','auth.error_message':'Sesi merchant tidak dapat dimulai. Periksa detail Anda lalu coba lagi.',
  'languages.title':'Bahasa Storefront','languages.desc':'Aktifkan hingga empat bahasa pelanggan dan masukkan terjemahan milik merchant secara manual.','languages.settings':'Pengaturan bahasa','languages.translations':'Terjemahan','languages.default':'Bahasa storefront default','languages.add':'Tambah bahasa','languages.code':'Kode bahasa','languages.label':'Nama tampilan','languages.native':'Nama asli','languages.brand':'Toko & SEO','languages.navigation':'Label menu','languages.categories':'Kategori','languages.products':'Produk & modifier','languages.home':'Bagian beranda','languages.select_product':'Pilih produk','languages.no_product':'Pilih produk untuk menerjemahkan konten dan label modifier.','languages.saved':'Draf bahasa disimpan','languages.published':'Pengaturan bahasa diterbitkan',
  'address.title':'Formulir Alamat Pengiriman','address.desc':'Pilih kolom alamat pelanggan yang ditampilkan di Profil dan Checkout.','address.fields':'Kolom alamat','address.label':'Label','address.country':'Kode negara','address.line2':'Baris alamat 2','address.postal':'Kode pos','address.default_country':'Kode negara default','address.default_country_hint':'Dipakai saat Kode negara disembunyikan. Masukkan kode ISO dua huruf seperti IN, SG, MM atau ID.','address.saved':'Draf alamat disimpan','address.published':'Formulir alamat diterbitkan',
 },
};

const Ctx=createContext(null);
const KEY='luke-admin-ui-locale';
export function AdminI18nProvider({children}){
 const[locale,setLocale]=useState(()=>{try{return localStorage.getItem(KEY)||'en'}catch{return'en'}});
 useEffect(()=>{if(!ADMIN_LOCALES.some(x=>x.code===locale))setLocale('en');try{localStorage.setItem(KEY,locale)}catch{}document.documentElement.lang=locale;},[locale]);
 const value=useMemo(()=>({locale,setLocale,locales:ADMIN_LOCALES,t:(key)=>DICT[locale]?.[key]??DICT.en[key]??key}),[locale]);
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
export function useAdminI18n(){const value=useContext(Ctx);if(!value)throw new Error('useAdminI18n must be used inside AdminI18nProvider');return value;}
