import{useCallback,useEffect,useRef,useState}from'react';import{useAuth}from'../auth/AuthContext.jsx';
const SOUND_KEY='luke-shop-admin.order-sound.v1';
const ACTIVE_POLL_MS=60_000,IDLE_POLL_MS=15*60_000,ACTIVE_FOR_MS=2*60_000;
const readSoundPreference=()=>{try{return localStorage.getItem(SOUND_KEY)!=='off'}catch{return true}};
const safeList=value=>Array.isArray(value)?value:[];
export function useMerchantNotifications(){const{api,session}=useAuth();const[items,setItems]=useState([]),[unread,setUnread]=useState(0),[newOrders,setNewOrders]=useState(0),[soundEnabled,setSoundEnabledState]=useState(readSoundPreference),[loading,setLoading]=useState(false);const seen=useRef(new Set()),first=useRef(true),audio=useRef(null),mounted=useRef(true),lastActivity=useRef(Date.now());const canRead=Array.isArray(session?.user?.permissions)&&session.user.permissions.includes('orders.read');
 useEffect(()=>{mounted.current=true;const unlock=()=>{lastActivity.current=Date.now();if(!audio.current){try{audio.current=new(window.AudioContext||window.webkitAudioContext)()}catch{}}audio.current?.resume?.().catch(()=>{});};window.addEventListener('pointerdown',unlock,{passive:true});return()=>{mounted.current=false;window.removeEventListener('pointerdown',unlock)}},[]);
 const chime=()=>{if(!soundEnabled||!audio.current||audio.current.state!=='running')return;const ctx=audio.current,now=ctx.currentTime;[[659.25,0,.12],[783.99,.14,.16]].forEach(([freq,delay,dur])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,now+delay);g.gain.exponentialRampToValueAtTime(.12,now+delay+.01);g.gain.exponentialRampToValueAtTime(.0001,now+delay+dur);o.connect(g);g.connect(ctx.destination);o.start(now+delay);o.stop(now+delay+dur+.02)});};
 const refresh=useCallback(async({silent=false}={})=>{if(!canRead)return;if(!silent)setLoading(true);try{const d=await api.request('/v1/merchant/notifications',{query:{limit:40}});if(!mounted.current)return;const next=safeList(d?.data?.notifications);if(first.current){next.forEach(n=>n?.id&&seen.current.add(n.id));first.current=false}else{const fresh=next.filter(n=>n?.id&&!seen.current.has(n.id));fresh.forEach(n=>seen.current.add(n.id));if(fresh.some(n=>n?.notification_type==='ORDER_CREATED'&&!n?.read_at))chime();}setItems(next);setUnread(Number.isFinite(Number(d?.data?.unread))?Number(d.data.unread):0);setNewOrders(Number.isFinite(Number(d?.data?.new_orders))?Number(d.data.new_orders):0);}catch{}finally{if(mounted.current)setLoading(false)}},[api,canRead,soundEnabled,session?.storeId]);
 useEffect(()=>{first.current=true;seen.current=new Set();if(!canRead)return;let timer=null,stopped=false;const clear=()=>{if(timer){clearTimeout(timer);timer=null}};const schedule=()=>{clear();if(stopped||document.hidden)return;const active=Date.now()-lastActivity.current<ACTIVE_FOR_MS;timer=setTimeout(async()=>{if(stopped||document.hidden)return;await refresh({silent:true});schedule()},active?ACTIVE_POLL_MS:IDLE_POLL_MS)};const wake=()=>{lastActivity.current=Date.now();if(document.hidden){clear();return}refresh({silent:true}).finally(schedule)};const activity=()=>{const wasIdle=Date.now()-lastActivity.current>=ACTIVE_FOR_MS;lastActivity.current=Date.now();if(wasIdle)schedule()};refresh().finally(schedule);document.addEventListener('visibilitychange',wake);window.addEventListener('focus',wake);window.addEventListener('pointerdown',activity,{passive:true});window.addEventListener('keydown',activity);return()=>{stopped=true;clear();document.removeEventListener('visibilitychange',wake);window.removeEventListener('focus',wake);window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity)}},[refresh,canRead,session?.storeId]);
 const markRead=async id=>{await api.request(`/v1/merchant/notifications/${encodeURIComponent(id)}/read`,{method:'POST',body:{}});await refresh({silent:true})};const markAll=async()=>{await api.request('/v1/merchant/notifications/read-all',{method:'POST',body:{}});await refresh({silent:true})};const setSoundEnabled=value=>{setSoundEnabledState(value);try{localStorage.setItem(SOUND_KEY,value?'on':'off')}catch{}if(value){try{if(!audio.current)audio.current=new(window.AudioContext||window.webkitAudioContext)();audio.current.resume?.()}catch{}}};const testSound=()=>chime();return{items,unread,newOrders,loading,refresh,markRead,markAll,soundEnabled,setSoundEnabled,testSound};}