import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,Empty,ErrorBox,Field,Loading,Modal,PageHeader,SearchBar,Table,Toast,statusTone}from'../components/UI.jsx';

const blankStaff={email:'',display_name:'',password:'',role_ids:[]};
const blankRole={key:'',name:'',description:'',permission_keys:[]};
const tabs=['Staff','Roles','Permissions'];
const fmt=(v)=>v?new Date(v).toLocaleString():'—';
const uniq=(v)=>[...new Set(v)];

export function AccessPage(){
 const{session,api,has,refreshProfile}=useAuth();
 const[tab,setTab]=useState('Staff'),[staff,setStaff]=useState([]),[roles,setRoles]=useState([]),[permissions,setPermissions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[toast,setToast]=useState(''),[q,setQ]=useState('');
 const[staffModal,setStaffModal]=useState(false),[staffForm,setStaffForm]=useState(blankStaff),[editStaff,setEditStaff]=useState(null),[editStaffForm,setEditStaffForm]=useState({display_name:'',status:'ACTIVE',role_ids:[]});
 const[roleModal,setRoleModal]=useState(false),[editRole,setEditRole]=useState(null),[roleForm,setRoleForm]=useState(blankRole);
 const[passwordStaff,setPasswordStaff]=useState(null),[newPassword,setNewPassword]=useState('');
 const[sessionsStaff,setSessionsStaff]=useState(null),[sessions,setSessions]=useState([]),[sessionsLoading,setSessionsLoading]=useState(false);
 const canStaffRead=has('merchant.staff.read'),canStaffManage=has('merchant.staff.manage'),canRolesRead=has('merchant.roles.read'),canRolesManage=has('merchant.roles.manage'),canSessionsManage=has('merchant.sessions.manage');
 const isOwner=(session?.user?.roles||[]).includes('OWNER');
 const canAccess=canStaffRead||canRolesRead;
 const allowedRoleOptions=useMemo(()=>roles.filter(r=>isOwner||r.key!=='OWNER'),[roles,isOwner]);
 const grantablePermissions=useMemo(()=>permissions.filter(p=>isOwner||(session?.user?.permissions||[]).includes(p.key)),[permissions,isOwner,session]);
 const filteredStaff=useMemo(()=>{const x=q.trim().toLowerCase();if(!x)return staff;return staff.filter(s=>[s.display_name,s.email,...(s.roles||[])].some(v=>String(v||'').toLowerCase().includes(x)))},[staff,q]);

 const load=async()=>{setLoading(true);setError(null);try{const jobs=[];if(canStaffRead)jobs.push(api.request('/v1/merchant/staff').then(x=>setStaff(x.data.staff)));else setStaff([]);if(canRolesRead)jobs.push(api.request('/v1/merchant/roles').then(x=>setRoles(x.data.roles)));else setRoles([]);if(canRolesRead)jobs.push(api.request('/v1/merchant/permissions').then(x=>setPermissions(x.data.permissions)));else setPermissions([]);await Promise.all(jobs)}catch(e){setError(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[canStaffRead,canRolesRead]);

 const openCreateStaff=()=>{setStaffForm(blankStaff);setStaffModal(true)};
 const createStaff=async()=>{setError(null);try{await api.request('/v1/merchant/staff',{method:'POST',body:{...staffForm,email:staffForm.email.trim(),display_name:staffForm.display_name.trim(),role_ids:uniq(staffForm.role_ids)}});setStaffModal(false);setToast('Staff account created');await load()}catch(e){setError(e)}};
 const openEditStaff=async(row)=>{setError(null);try{const d=await api.request(`/v1/merchant/staff/${row.id}`);const s=d.data.staff;setEditStaff(s);setEditStaffForm({display_name:s.display_name,status:s.status==='BLOCKED'?'DISABLED':s.status,role_ids:(s.roles||[]).map(r=>r.id)})}catch(e){setError(e)}};
 const saveStaff=async()=>{setError(null);try{const currentRoles=(editStaff.roles||[]).map(r=>r.id).sort().join('|'),nextRoles=uniq(editStaffForm.role_ids).sort().join('|');await api.request(`/v1/merchant/staff/${editStaff.id}`,{method:'PATCH',body:{display_name:editStaffForm.display_name.trim(),status:editStaffForm.status}});if(canRolesManage&&currentRoles!==nextRoles)await api.request(`/v1/merchant/staff/${editStaff.id}/roles`,{method:'PUT',body:{role_ids:uniq(editStaffForm.role_ids)}});if(editStaff.id===session.user.id)await refreshProfile();setEditStaff(null);setToast('Staff account updated');await load()}catch(e){setError(e)}};
 const resetPassword=async()=>{setError(null);try{await api.request(`/v1/merchant/staff/${passwordStaff.id}/reset-password`,{method:'POST',body:{new_password:newPassword}});setPasswordStaff(null);setNewPassword('');setToast('Password reset and active sessions revoked');await load()}catch(e){setError(e)}};
 const forceLogout=async(row)=>{if(!window.confirm(`Force logout all active sessions for ${row.display_name}?`))return;setError(null);try{const d=await api.request(`/v1/merchant/staff/${row.id}/force-logout`,{method:'POST',body:{}});setToast(`${d.data.sessions_revoked} session(s) revoked`);await load()}catch(e){setError(e)}};
 const openSessions=async(row)=>{setSessionsStaff(row);setSessions([]);setSessionsLoading(true);setError(null);try{const d=await api.request(`/v1/merchant/staff/${row.id}/sessions`);setSessions(d.data.sessions)}catch(e){setError(e)}finally{setSessionsLoading(false)}};
 const revokeSession=async(s)=>{setError(null);try{await api.request(`/v1/merchant/staff/${sessionsStaff.id}/sessions/${s.id}`,{method:'DELETE'});setSessions(x=>x.map(v=>v.id===s.id?{...v,active:false,revoked_at:new Date().toISOString()}:v));setToast('Session revoked')}catch(e){setError(e)}};

 const openCreateRole=()=>{setEditRole(null);setRoleForm(blankRole);setRoleModal(true)};
 const openEditRole=(r)=>{setEditRole(r);setRoleForm({key:r.key,name:r.name,description:r.description||'',permission_keys:r.permissions||[]});setRoleModal(true)};
 const saveRole=async()=>{setError(null);try{if(editRole){await api.request(`/v1/merchant/roles/${editRole.id}`,{method:'PATCH',body:{name:roleForm.name.trim(),description:roleForm.description.trim()||null}});const a=[...(editRole.permissions||[])].sort().join('|'),b=uniq(roleForm.permission_keys).sort().join('|');if(a!==b)await api.request(`/v1/merchant/roles/${editRole.id}/permissions`,{method:'PUT',body:{permission_keys:uniq(roleForm.permission_keys)}})}else await api.request('/v1/merchant/roles',{method:'POST',body:{key:roleForm.key.trim(),name:roleForm.name.trim(),description:roleForm.description.trim()||null,permission_keys:uniq(roleForm.permission_keys)}});setRoleModal(false);setToast(editRole?'Role updated':'Role created');await load()}catch(e){setError(e)}};
 const deleteRole=async(r)=>{if(!window.confirm(`Delete role ${r.name}? It must not be assigned to any staff account.`))return;setError(null);try{await api.request(`/v1/merchant/roles/${r.id}`,{method:'DELETE'});setToast('Role deleted');await load()}catch(e){setError(e)}};
 const toggle=(arr,value)=>arr.includes(value)?arr.filter(x=>x!==value):[...arr,value];

 if(!canAccess)return <><PageHeader title="Access & roles" description="Your current account is authenticated, but it does not have staff/RBAC read permission."/><Card title="Current merchant"><div className="detail-list"><div><span>Name</span><strong>{session.user.display_name}</strong></div><div><span>Email</span><strong>{session.user.email}</strong></div><div><span>Roles</span><div className="badge-row">{(session.user.roles||[]).map(r=><Badge key={r}>{r}</Badge>)}</div></div></div></Card></>;
 if(loading)return <Loading/>;
 return <>
  <PageHeader title="Staff & access" description="Create merchant staff, assign least-privilege roles, reset passwords, and revoke sessions. Backend v0.6.0 remains the authorization authority." actions={<>{canStaffManage&&canRolesRead&&<button className="primary" onClick={openCreateStaff}>+ Create staff</button>}{canRolesManage&&<button className="secondary" onClick={openCreateRole}>+ Create role</button>}</>}/>
  <ErrorBox error={error}/><Toast message={toast} onDone={()=>setToast('')}/>
  <div className="access-summary"><div><span>Staff</span><strong>{staff.length}</strong></div><div><span>Active</span><strong>{staff.filter(s=>s.status==='ACTIVE').length}</strong></div><div><span>Custom roles</span><strong>{roles.filter(r=>!r.is_system).length}</strong></div><div><span>Permissions</span><strong>{permissions.length}</strong></div></div>
  <div className="tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>

  {tab==='Staff'&&<Card title="Merchant staff" subtitle="Suspending or disabling an account immediately revokes its active sessions."><div className="toolbar"><SearchBar value={q} onChange={setQ} placeholder="Search staff, email, or role"/><span className="toolbar-spacer"/>{canStaffManage&&canRolesRead&&<button className="primary small" onClick={openCreateStaff}>Create staff</button>}</div>{!canStaffRead?<Empty title="Staff read permission required"/>:<Table rows={filteredStaff} emptyTitle="No staff accounts" columns={[
   {key:'staff',label:'Staff',render:r=><div className="person-cell"><div className="avatar light">{(r.display_name||r.email).slice(0,1).toUpperCase()}</div><div><strong>{r.display_name}</strong><small>{r.email}</small></div></div>},
   {key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},
   {key:'roles',label:'Roles',render:r=><div className="badge-row">{(r.roles||[]).map(x=><Badge key={x}>{x}</Badge>)}</div>},
   {key:'sessions',label:'Sessions',render:r=><button className="link-btn" onClick={()=>openSessions(r)}>{r.active_sessions||0} active</button>},
   {key:'last',label:'Last login',render:r=><span className="small-text">{fmt(r.last_login_at)}</span>},
   {key:'actions',label:'Actions',render:r=><div className="action-group"><button className="secondary small" onClick={()=>openEditStaff(r)}>View</button>{canSessionsManage&&r.id!==session.user.id&&<button className="secondary small" onClick={()=>forceLogout(r)}>Force logout</button>}</div>}
  ]}/>}</Card>}

  {tab==='Roles'&&<Card title="Roles" subtitle="System OWNER is protected. Custom roles can only receive permissions the acting merchant already has.">{!canRolesRead?<Empty title="Role read permission required"/>:<Table rows={roles} emptyTitle="No roles" columns={[
   {key:'name',label:'Role',render:r=><div><strong>{r.name}</strong><small className="block"><code>{r.key}</code>{r.description?` · ${r.description}`:''}</small></div>},
   {key:'system',label:'Type',render:r=><Badge tone={r.is_system?'success':'neutral'}>{r.is_system?'SYSTEM':'CUSTOM'}</Badge>},
   {key:'staff_count',label:'Staff',render:r=>r.staff_count},
   {key:'permissions',label:'Permissions',render:r=><span>{(r.permissions||[]).length}</span>},
   {key:'actions',label:'Actions',render:r=>r.is_system?<span className="muted">Protected</span>:<div className="action-group">{canRolesManage&&<button className="secondary small" onClick={()=>openEditRole(r)}>Edit</button>}{canRolesManage&&<button className="danger-btn small" onClick={()=>deleteRole(r)}>Delete</button>}</div>}
  ]}/>}</Card>}

  {tab==='Permissions'&&<div className="two-col"><Card title="Effective permissions" subtitle="What your current merchant account can do."><div className="permission-grid">{(session.user.permissions||[]).sort().map(p=><code key={p}>{p}</code>)}</div></Card><Card title="Platform permission catalog" subtitle="Permissions available to tenant roles."><div className="permission-list">{permissions.map(p=><div key={p.key}><code>{p.key}</code><span>{p.description}</span></div>)}</div></Card></div>}

  <Modal open={staffModal} onClose={()=>setStaffModal(false)} title="Create merchant staff" footer={<><button className="secondary" onClick={()=>setStaffModal(false)}>Cancel</button><button className="primary" disabled={!staffForm.email||!staffForm.display_name||staffForm.password.length<12||!staffForm.role_ids.length} onClick={createStaff}>Create staff</button></>}><div className="form-grid"><Field label="Display name"><input value={staffForm.display_name} onChange={e=>setStaffForm({...staffForm,display_name:e.target.value})}/></Field><Field label="Email"><input type="email" value={staffForm.email} onChange={e=>setStaffForm({...staffForm,email:e.target.value})}/></Field></div><Field label="Initial password" hint="12–128 characters. Share it through a secure channel."><input type="password" value={staffForm.password} onChange={e=>setStaffForm({...staffForm,password:e.target.value})}/></Field><Field label="Roles"><div className="choice-grid">{allowedRoleOptions.map(r=><label className="choice" key={r.id}><input type="checkbox" checked={staffForm.role_ids.includes(r.id)} onChange={()=>setStaffForm({...staffForm,role_ids:toggle(staffForm.role_ids,r.id)})}/><div><strong>{r.name}</strong><span>{r.key} · {(r.permissions||[]).length} permissions</span></div></label>)}</div></Field></Modal>

  <Modal open={Boolean(editStaff)} onClose={()=>setEditStaff(null)} title={editStaff?`Manage ${editStaff.display_name}`:'Manage staff'} footer={<><button className="secondary" onClick={()=>setEditStaff(null)}>Cancel</button>{canStaffManage&&<button className="primary" onClick={saveStaff}>Save changes</button>}</>}>
   {editStaff&&<><div className="detail-grid"><div><span>Email</span><strong>{editStaff.email}</strong></div><div><span>Active sessions</span><strong>{editStaff.active_sessions}</strong></div><div><span>Created</span><strong>{fmt(editStaff.created_at)}</strong></div><div><span>Last login</span><strong>{fmt(editStaff.last_login_at)}</strong></div></div><Field label="Display name"><input disabled={!canStaffManage} value={editStaffForm.display_name} onChange={e=>setEditStaffForm({...editStaffForm,display_name:e.target.value})}/></Field><Field label="Status" hint={editStaff.id===session.user.id?'Self suspension/disable is blocked to prevent lockout.':'Non-active status revokes all active sessions.'}><select disabled={!canStaffManage||editStaff.id===session.user.id} value={editStaffForm.status} onChange={e=>setEditStaffForm({...editStaffForm,status:e.target.value})}><option>ACTIVE</option><option>SUSPENDED</option><option>DISABLED</option></select></Field>{canRolesManage&&editStaff.id!==session.user.id&&<Field label="Roles"><div className="choice-grid">{allowedRoleOptions.map(r=><label className="choice" key={r.id}><input type="checkbox" checked={editStaffForm.role_ids.includes(r.id)} onChange={()=>setEditStaffForm({...editStaffForm,role_ids:toggle(editStaffForm.role_ids,r.id)})}/><div><strong>{r.name}</strong><span>{r.key}</span></div></label>)}</div></Field>}<div className="danger-zone"><strong>Security actions</strong><span>Password reset revokes every active session for this account.</span><div className="action-group">{canStaffManage&&editStaff.id!==session.user.id&&<button className="secondary" onClick={()=>{setPasswordStaff(editStaff);setNewPassword('')}}>Reset password</button>}{canSessionsManage&&editStaff.id!==session.user.id&&<button className="danger-btn" onClick={()=>forceLogout(editStaff)}>Force logout</button>}<button className="secondary" onClick={()=>openSessions(editStaff)}>View sessions</button></div></div></>}
  </Modal>

  <Modal open={Boolean(passwordStaff)} onClose={()=>setPasswordStaff(null)} title="Reset staff password" footer={<><button className="secondary" onClick={()=>setPasswordStaff(null)}>Cancel</button><button className="danger-btn" disabled={newPassword.length<12} onClick={resetPassword}>Reset & revoke sessions</button></>}><div className="alert"><strong>{passwordStaff?.display_name}</strong><span>All active sessions will be revoked immediately after the password changes.</span></div><Field label="New password" hint="12–128 characters"><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field></Modal>

  <Modal open={Boolean(sessionsStaff)} onClose={()=>setSessionsStaff(null)} title={sessionsStaff?`${sessionsStaff.display_name} · Sessions`:'Sessions'}>{sessionsLoading?<Loading/>:<Table rows={sessions} emptyTitle="No sessions" columns={[
   {key:'state',label:'State',render:r=><Badge tone={r.active?'success':'neutral'}>{r.active?'ACTIVE':'REVOKED'}</Badge>},
   {key:'device',label:'Device',render:r=><span className="small-text">{r.user_agent||'Unknown device'}</span>},
   {key:'ip',label:'IP',render:r=>r.request_ip||'—'},
   {key:'seen',label:'Last seen',render:r=>fmt(r.last_seen_at)},
   {key:'action',label:'',render:r=>r.active&&canSessionsManage&&sessionsStaff?.id!==session.user.id?<button className="danger-btn small" onClick={()=>revokeSession(r)}>Revoke</button>:null}
  ]}/>}</Modal>

  <Modal open={roleModal} onClose={()=>setRoleModal(false)} title={editRole?'Edit role':'Create role'} footer={<><button className="secondary" onClick={()=>setRoleModal(false)}>Cancel</button><button className="primary" disabled={!roleForm.name||(!editRole&&!roleForm.key)} onClick={saveRole}>{editRole?'Save role':'Create role'}</button></>}><div className="form-grid"><Field label="Role key" hint="Uppercase identifier such as ORDER_MANAGER"><input disabled={Boolean(editRole)} value={roleForm.key} onChange={e=>setRoleForm({...roleForm,key:e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,'_')})}/></Field><Field label="Name"><input value={roleForm.name} onChange={e=>setRoleForm({...roleForm,name:e.target.value})}/></Field></div><Field label="Description"><textarea value={roleForm.description} onChange={e=>setRoleForm({...roleForm,description:e.target.value})}/></Field><Field label="Permissions" hint="The backend blocks assigning permissions you do not possess."><div className="permission-choice-grid">{grantablePermissions.map(p=><label className="permission-choice" key={p.key}><input type="checkbox" checked={roleForm.permission_keys.includes(p.key)} onChange={()=>setRoleForm({...roleForm,permission_keys:toggle(roleForm.permission_keys,p.key)})}/><div><code>{p.key}</code><span>{p.description}</span></div></label>)}</div></Field></Modal>
 </>
}
