import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,DateTime,ErrorBox,Field,Modal,PageHeader,SearchBar,Table,Toast,statusTone,PermissionNote}from'../components/UI.jsx';

export function CustomersPage(){
 const{api,has}=useAuth();const[rows,setRows]=useState([]),[err,setErr]=useState(null),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[status,setStatus]=useState('ACTIVE'),[filter,setFilter]=useState(''),[q,setQ]=useState(''),[reason,setReason]=useState(''),[toast,setToast]=useState('');
 const load=async()=>{setErr(null);try{const d=await api.request('/v1/merchant/customers',{query:{status:filter||undefined,limit:100}});setRows(d.data.customers)}catch(e){setErr(e)}};useEffect(()=>{load()},[filter]);
 const openCustomer=async(r)=>{setSelected(r.public_id);setStatus(r.status==='DELETION_PENDING'?'ACTIVE':r.status);setReason('');try{const d=await api.request(`/v1/merchant/customers/${encodeURIComponent(r.public_id)}`);setDetail(d.data.customer)}catch(e){setErr(e);setSelected(null)}};
 const save=async()=>{try{await api.request(`/v1/merchant/customers/${encodeURIComponent(selected)}/status`,{method:'PATCH',body:{status,reason:reason||undefined}});setToast('Customer status updated');const d=await api.request(`/v1/merchant/customers/${encodeURIComponent(selected)}`);setDetail(d.data.customer);load()}catch(e){setErr(e)}};
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();if(!x)return rows;return rows.filter(r=>`${r.display_name||''} ${r.email||''}`.toLowerCase().includes(x))},[rows,q]);
 if(!has('customers.read'))return <PermissionNote permission="customers.read"/>;
 return <><PageHeader title="Customers" description="Search customer accounts, inspect account history signals, and control access status with audited reasons."/><ErrorBox error={err}/><div className="toolbar"><SearchBar value={q} onChange={setQ} placeholder="Search name or email"/><select className="toolbar-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option><option>ACTIVE</option><option>SUSPENDED</option><option>BLOCKED</option><option>DELETION_PENDING</option></select><div className="toolbar-spacer"/><span className="muted">{filtered.length} customers</span></div><Card title="Customer directory"><Table rows={filtered} keyField="public_id" columns={[{key:'display_name',label:'Customer',render:r=><button className="link-btn" onClick={()=>openCustomer(r)}>{r.display_name||'Unnamed'}</button>},{key:'email',label:'Email'},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'created_at',label:'Joined',render:r=><DateTime value={r.created_at}/>},{key:'last_login_at',label:'Last login',render:r=><DateTime value={r.last_login_at}/>}]} /></Card><Modal open={!!selected} onClose={()=>{setSelected(null);setDetail(null)}} title="Customer account" size="lg"><div className="detail-grid"><div><span>Name</span><strong>{detail?.display_name||'Unnamed'}</strong></div><div><span>Email</span><strong>{detail?.email||'—'}</strong></div><div><span>Status</span><Badge tone={statusTone(detail?.status)}>{detail?.status||'—'}</Badge></div><div><span>Customer ID</span><code>{detail?.public_id||selected}</code></div><div><span>Joined</span><strong><DateTime value={detail?.created_at}/></strong></div><div><span>Last login</span><strong><DateTime value={detail?.last_login_at}/></strong></div></div>{has('customers.status.manage')?<Card title="Account status" subtitle="Suspending or blocking a customer revokes active customer sessions"><Field label="New status"><select value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>SUSPENDED</option><option>BLOCKED</option></select></Field><Field label="Audit reason"><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why the account status is changing"/></Field><button className="primary" onClick={save}>Update customer status</button></Card>:<PermissionNote permission="customers.status.manage"/>}</Modal><Toast message={toast} onDone={()=>setToast('')}/></>;
}
