import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,DateTime,ErrorBox,Field,Modal,PageHeader,SearchBar,Table,Toast,statusTone,PermissionNote}from'../components/UI.jsx';

export function CustomersPage(){
 const{api,has}=useAuth();const[rows,setRows]=useState([]),[err,setErr]=useState(null),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[status,setStatus]=useState('ACTIVE'),[filter,setFilter]=useState(''),[q,setQ]=useState(''),[reason,setReason]=useState(''),[toast,setToast]=useState('');
 const load=async()=>{setErr(null);try{const d=await api.request('/v1/merchant/customers',{query:{status:filter||undefined,limit:100}});setRows(d.data.customers)}catch(e){setErr(e)}};useEffect(()=>{load()},[filter]);
 const openCustomer=async(r)=>{setSelected(r.public_id);setStatus(r.status==='DELETION_PENDING'?'ACTIVE':r.status);setReason('');try{const d=await api.request(`/v1/merchant/customers/${encodeURIComponent(r.public_id)}`);setDetail(d.data.customer)}catch(e){setErr(e);setSelected(null)}};
 const refreshDetail=async()=>{if(!selected)return;const d=await api.request(`/v1/merchant/customers/${encodeURIComponent(selected)}`);setDetail(d.data.customer)};
 const save=async()=>{try{await api.request(`/v1/merchant/customers/${encodeURIComponent(selected)}/status`,{method:'PATCH',body:{status,reason:reason||undefined}});setToast('Customer status updated');await refreshDetail();load()}catch(e){setErr(e)}};
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();if(!x)return rows;return rows.filter(r=>`${r.display_name||''} ${r.email||''} ${r.phone_e164||''} ${r.customer_code||''}`.toLowerCase().includes(x))},[rows,q]);
 if(!has('customers.read'))return <PermissionNote permission="customers.read"/>;
 return <><PageHeader title="Customers" description="Search accounts, inspect saved addresses, recent orders, security activity and status history, then control access with audited reasons."/><ErrorBox error={err}/><div className="toolbar"><SearchBar value={q} onChange={setQ} placeholder="Search name, ID, email or phone"/><select className="toolbar-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option><option>ACTIVE</option><option>SUSPENDED</option><option>BLOCKED</option><option>DELETION_PENDING</option></select><div className="toolbar-spacer"/><span className="muted">{filtered.length} customers</span></div><Card title="Customer directory"><Table rows={filtered} keyField="public_id" columns={[{key:'display_name',label:'Customer',render:r=><div className="customer-cell">{r.avatar_url?<img src={r.avatar_url} alt=""/>:<span>{(r.display_name||'C').slice(0,1).toUpperCase()}</span>}<div><button className="link-btn" onClick={()=>openCustomer(r)}>{r.display_name||'Unnamed'}</button><code>{r.customer_code||r.public_id}</code></div></div>},{key:'email',label:'Contact',render:r=><div>{r.email||'—'}<small className="block">{r.phone_e164||''}</small></div>},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'created_at',label:'Joined',render:r=><DateTime value={r.created_at}/>},{key:'last_login_at',label:'Last login',render:r=><DateTime value={r.last_login_at}/>}]} /></Card>
 <Modal open={!!selected} onClose={()=>{setSelected(null);setDetail(null)}} title="Customer account" size="xl">{detail&&<><div className="detail-grid"><div><span>Name</span><strong>{detail.display_name||'Unnamed'}</strong></div><div><span>Email</span><strong>{detail.email||'—'}</strong></div><div><span>Status</span><Badge tone={statusTone(detail.status)}>{detail.status||'—'}</Badge></div><div><span>Customer ID</span><code>{detail.customer_code||detail.public_id||selected}</code></div><div><span>Internal reference</span><code>{detail.public_id||selected}</code></div><div><span>Phone</span><strong>{detail.phone_e164||'—'}</strong></div><div><span>Joined</span><strong><DateTime value={detail.created_at}/></strong></div><div><span>Last login</span><strong><DateTime value={detail.last_login_at}/></strong></div><div><span>Password changed</span><strong><DateTime value={detail.password_changed_at}/></strong></div><div><span>Active sessions</span><strong>{detail.active_sessions??0}</strong></div></div>
 <div className="grid2"><Card title="Saved addresses" subtitle={`${detail.addresses?.length||0} address(es)`}>{detail.addresses?.length?<div className="history-list">{detail.addresses.map(a=><div key={a.id}><div><strong>{a.label}{a.is_default?' · default':''}</strong><span>{a.recipient_name}{a.phone?` · ${a.phone}`:''}</span><small className="block">{a.formatted_address||[a.address_line_1,a.address_line_2,a.city,a.state,a.postal_code,a.country_code].filter(Boolean).join(', ')}</small></div></div>)}</div>:<p className="muted">No saved addresses.</p>}</Card>
 <Card title="Status history" subtitle="Immutable customer lifecycle changes">{detail.status_history?.length?<div className="timeline">{detail.status_history.map((h,i)=><div className="timeline-item" key={`${h.created_at}-${i}`}><i/><div><strong>{h.from_status||'—'} → {h.to_status}</strong><span>{h.reason||'No reason recorded'} · {h.changed_by_type}</span><small><DateTime value={h.created_at}/></small></div></div>)}</div>:<p className="muted">No status changes recorded.</p>}</Card></div>
 <Card title="Recent orders" subtitle="Latest 25 orders for this customer">{detail.recent_orders?.length?<Table rows={detail.recent_orders} keyField="id" columns={[{key:'order_number',label:'Order'},{key:'store_name',label:'Store'},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'payment_status',label:'Payment',render:r=><Badge tone={statusTone(r.payment_status)}>{r.payment_status}</Badge>},{key:'grand_total',label:'Total',render:r=>`${r.currency} ${Number(r.grand_total||0).toFixed(2)}`},{key:'created_at',label:'Created',render:r=><DateTime value={r.created_at}/>}]} />:<p className="muted">No orders yet.</p>}</Card>
 {has('customers.status.manage')?<Card title="Account status" subtitle="Suspending or blocking a customer revokes active customer sessions"><Field label="New status"><select value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>SUSPENDED</option><option>BLOCKED</option></select></Field><Field label="Audit reason"><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why the account status is changing"/></Field><button className="primary" onClick={save}>Update customer status</button></Card>:<PermissionNote permission="customers.status.manage"/>}</>}</Modal><Toast message={toast} onDone={()=>setToast('')}/></>;
}
