import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,ErrorBox,Field,Loading,PageHeader,PermissionNote,Toast,statusTone}from'../components/UI.jsx';

const fallback={schema_version:2,theme:{preset:'modern',primary:'#166534',secondary:'#111827',accent:'#14b8a6',background:'#f8fafc',surface:'#ffffff',text:'#172033',muted_text:'#667085',success:'#15803d',danger:'#b42318',radius:'medium',card_style:'clean',button_style:'solid',density:'comfortable'},typography:{preset:'SYSTEM_MINIMAL',heading_scale:'normal',body_scale:'normal',letter_spacing:'normal',button_case:'none'},layout:{header:'logo_left',hero:'split',categories:'cards',product_grid:'four',product_card:'standard',mobile_nav:'standard'},branding:{store_name:'',announcement:'',hero_title:'',hero_subtitle:'',logo_url:'',favicon_url:''},navigation:['home','explore','cart','orders','profile'],home:{sections:[{id:'hero',type:'hero',enabled:true},{id:'categories',type:'categories',enabled:true},{id:'featured',type:'featured_products',enabled:true}]},features:{search:true,promotions:true,support:true,ratings:false,stock_status:true,quick_add:false}};
const CUSTOMER_WEB_BASE=(import.meta.env.VITE_LUKE_SHOP_CUSTOMER_WEB_BASE_URL||'http://localhost:4174').replace(/\/$/,'');
const clone=x=>JSON.parse(JSON.stringify(x||fallback));
const types=[['hero','Hero'],['hero_slider','Hero slider'],['categories','Categories'],['featured_products','Featured products'],['promotion_banner','Promotion banner'],['new_arrivals','New arrivals'],['announcement_bar','Announcement bar']];
const navItems=['home','explore','cart','orders','profile'];
const layouts={header:[['logo_left','Logo left'],['centered_logo','Centered logo'],['search_first','Search first'],['compact','Compact'],['transparent','Transparent over hero']],hero:[['split','Split image + text'],['full_width','Full-width campaign'],['slider','Slider'],['featured_product','Featured product'],['video','Video campaign'],['minimal','Minimal text']],categories:[['cards','Cards'],['circles','Circles'],['image_tiles','Image tiles'],['chips','Compact chips'],['horizontal','Horizontal rail']],product_grid:[['two','2 columns'],['three','3 columns'],['four','4 columns'],['editorial','Editorial'],['compact','Compact marketplace'],['horizontal','Horizontal rail']],product_card:[['standard','Standard'],['minimal','Minimal'],['soft','Soft'],['bold','Bold'],['technical','Technical'],['compact','Compact'],['quick_add','Quick add'],['editorial','Editorial']],mobile_nav:[['standard','Standard'],['ios','iOS style'],['compact','Compact']]};
const themeFields=[['primary','Primary'],['secondary','Secondary'],['accent','Accent'],['background','Background'],['surface','Surface'],['text','Text'],['muted_text','Muted text'],['success','Success'],['danger','Danger']];

export function CustomerExperiencePage(){
 const{api,has}=useAuth();
 const[data,setData]=useState(null),[catalog,setCatalog]=useState({templates:[],typography_presets:[]}),[draft,setDraft]=useState(clone(fallback)),[err,setErr]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[preview,setPreview]=useState(true),[openSections,setOpenSections]=useState({}),[dirty,setDirty]=useState(false),[savedAt,setSavedAt]=useState(null),[templateChoice,setTemplateChoice]=useState('');
 const load=async()=>{setErr(null);try{const[d,c]=await Promise.all([api.request('/v1/merchant/customer-experience'),api.request('/v1/merchant/customer-experience/catalog')]);setData(d.data);setCatalog(c.data||{templates:[],typography_presets:[]});const next=clone(d.data.draft?.config||d.data.published?.config||fallback);setDraft(next);setTemplateChoice(d.data.draft?.template_key||d.data.published?.template_key||'');setDirty(false)}catch(e){setErr(e)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const before=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty]);
 const mutate=fn=>{setDraft(prev=>{const next=clone(prev);fn(next);return next});setDirty(true)};
 const update=(area,key,value)=>mutate(next=>{next[area]={...(next[area]||{}),[key]:value}});
 const save=async()=>{setBusy(true);setErr(null);try{await api.request('/v1/merchant/customer-experience/draft',{method:'PUT',body:{config:draft}});setDirty(false);setSavedAt(new Date());setToast('Draft saved');await load()}catch(e){setErr(e)}finally{setBusy(false)}};
 const publish=async()=>{if(dirty){setErr({code:'UNSAVED_CHANGES',message:'Save the draft before publishing so the live storefront exactly matches your editor.'});return}setBusy(true);setErr(null);try{await api.request('/v1/merchant/customer-experience/publish',{method:'POST',body:{}});setToast('Customer experience published');await load()}catch(e){setErr(e)}finally{setBusy(false)}};
 const applyTemplate=async(mode='full')=>{if(!templateChoice)return;setBusy(true);setErr(null);try{const r=await api.request('/v1/merchant/customer-experience/apply-template',{method:'POST',body:{template_key:templateChoice,mode,keep_content:true}});setDraft(clone(r.data.draft.config));setDirty(false);setSavedAt(new Date());setToast(mode==='full'?'Template applied':'Template '+mode+' applied');await load()}catch(e){setErr(e)}finally{setBusy(false)}};
 const rollback=async version=>{if(!confirm(`Publish a new version based on version ${version}?`))return;setBusy(true);try{await api.request('/v1/merchant/customer-experience/rollback',{method:'POST',body:{version}});setToast(`Rolled back from version ${version}`);await load()}catch(e){setErr(e)}finally{setBusy(false)}};
 const openPublished=()=>data?.storefront_path&&window.open(`${CUSTOMER_WEB_BASE}${data.storefront_path}`,'_blank','noopener,noreferrer');
 const openDraftPreview=async()=>{if(dirty){setErr({code:'SAVE_DRAFT_FIRST',message:'Save your draft first. Secure preview always opens the exact server-saved draft.'});return}setBusy(true);try{const r=await api.request('/v1/merchant/customer-experience/preview-token',{method:'POST',body:{}});window.open(`${CUSTOMER_WEB_BASE}${r.data.preview_path}`,'_blank','noopener,noreferrer')}catch(e){setErr(e)}finally{setBusy(false)}};
 if(!has('customer_experience.read'))return <PermissionNote permission="customer_experience.read"/>;if(!data&&!err)return <Loading/>;
 const sections=draft.home?.sections||[];const setSections=next=>mutate(x=>{x.home={...(x.home||{}),sections:next}});const patchSection=(i,patch)=>{const next=[...sections];next[i]={...next[i],...patch};setSections(next)};const move=(i,dir)=>{const j=i+dir;if(j<0||j>=sections.length)return;const x=[...sections];[x[i],x[j]]=[x[j],x[i]];setSections(x)};const add=()=>{const id=`section-${Date.now()}`;setSections([...sections,{id,type:'promotion_banner',enabled:true,title:'New campaign',body:'',image_url:'',cta_label:'Shop now',cta_path:'/explore',limit:8}]);setOpenSections({...openSections,[id]:true})};
 const font=catalog.typography_presets?.find(x=>x.key===draft.typography?.preset);
 return <>
  <PageHeader eyebrow="Customer Experience" title="Store Designer" description="Choose a template, typography, layout and commerce styling. Draft, preview and published storefronts now use the same canonical Experience Engine v2." actions={<><span className={`save-state ${dirty?'dirty':'saved'}`}>{dirty?'● Unsaved changes':savedAt?`✓ Saved ${savedAt.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'✓ Draft synced'}</span><button className="secondary" onClick={openPublished}>Open published</button><button className="secondary" disabled={busy} onClick={openDraftPreview}>Preview draft</button><button className="secondary" onClick={()=>setPreview(!preview)}>{preview?'Hide preview':'Show preview'}</button>{has('customer_experience.manage')&&<button className="secondary" disabled={busy||!dirty} onClick={save}>Save draft</button>}{has('customer_experience.publish')&&<button className="primary" disabled={busy||dirty} onClick={publish}>Publish</button>}</>}/>
  <ErrorBox error={err}/>
  <div className="experience-status"><div><span>Store</span><strong>{data?.store?.name||'Primary store'}</strong><small>{data?.storefront_path||'—'}</small></div><div><span>Live</span><strong>v{data?.published?.version||'—'}</strong></div><div><span>Draft</span><strong>v{data?.draft?.version||'—'}</strong></div><div><span>Engine</span><strong>Schema v{draft.schema_version||2}</strong><small>{data?.draft?.template_key||'Custom'}</small></div></div>
  <div className={preview?'experience-layout':'experience-layout no-preview'}><div className="experience-editor">
   <Card title="Template library" subtitle="Clients can choose a starting design without replacing their products or campaign copy."><div className="template-chooser"><Field label="Template"><select value={templateChoice} onChange={e=>setTemplateChoice(e.target.value)}><option value="">Choose a template</option>{catalog.templates?.map(t=><option key={t.key} value={t.key}>{t.business_type} · {t.name}</option>)}</select></Field><div className="button-row"><button className="secondary" disabled={!templateChoice||busy} onClick={()=>applyTemplate('layout')}>Apply layout only</button><button className="secondary" disabled={!templateChoice||busy} onClick={()=>applyTemplate('theme')}>Apply theme + fonts</button><button className="primary" disabled={!templateChoice||busy} onClick={()=>confirm('Apply the complete template while keeping your current store copy and home section content?')&&applyTemplate('full')}>Use template</button></div></div><div className="template-gallery">{catalog.templates?.slice(0,12).map(t=><button type="button" key={t.key} className={templateChoice===t.key?'selected':''} onClick={()=>setTemplateChoice(t.key)}><span>{t.business_type}</span><strong>{t.name}</strong><small>{t.config?.typography?.preset||'System font'} · {t.config?.layout?.hero||'split'} hero</small></button>)}</div></Card>
   <Card title="Brand identity" subtitle="Customer-facing identity and campaign copy"><div className="form-grid"><Field label="Store display name"><input value={draft.branding?.store_name||''} onChange={e=>update('branding','store_name',e.target.value)}/></Field><Field label="Logo URL"><input value={draft.branding?.logo_url||''} onChange={e=>update('branding','logo_url',e.target.value)} placeholder="https://…"/></Field><Field label="Favicon URL"><input value={draft.branding?.favicon_url||''} onChange={e=>update('branding','favicon_url',e.target.value)} placeholder="https://…"/></Field><Field label="Announcement"><input value={draft.branding?.announcement||''} onChange={e=>update('branding','announcement',e.target.value)} /></Field><Field label="Hero title"><input value={draft.branding?.hero_title||''} onChange={e=>update('branding','hero_title',e.target.value)}/></Field><Field label="Hero subtitle"><textarea value={draft.branding?.hero_subtitle||''} onChange={e=>update('branding','hero_subtitle',e.target.value)}/></Field></div></Card>
   <Card title="Theme" subtitle="Published values are stored completely; Luke defaults are only used when a field is genuinely absent."><div className="theme-controls">{themeFields.map(([k,l])=><Field key={k} label={l}><div className="color-field"><input type="color" value={draft.theme?.[k]||fallback.theme[k]} onChange={e=>update('theme',k,e.target.value)}/><input value={draft.theme?.[k]||''} onChange={e=>update('theme',k,e.target.value)}/></div></Field>)}<Field label="Corner radius"><select value={draft.theme?.radius||'medium'} onChange={e=>update('theme','radius',e.target.value)}><option value="small">Compact</option><option value="medium">Balanced</option><option value="large">Soft</option><option value="xl">Extra soft</option></select></Field><Field label="Card style"><select value={draft.theme?.card_style||'clean'} onChange={e=>update('theme','card_style',e.target.value)}>{['clean','soft','editorial','bold','technical'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Button style"><select value={draft.theme?.button_style||'solid'} onChange={e=>update('theme','button_style',e.target.value)}>{['solid','pill','outline','soft'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Density"><select value={draft.theme?.density||'comfortable'} onChange={e=>update('theme','density',e.target.value)}><option>compact</option><option>comfortable</option><option>spacious</option></select></Field></div></Card>
   <Card title="Typography" subtitle="Approved font presets only. iPhone / iOS System uses Apple’s native SF system font when available; no Apple font file is bundled."><div className="typography-grid"><Field label="Font preset"><select value={draft.typography?.preset||'SYSTEM_MINIMAL'} onChange={e=>update('typography','preset',e.target.value)}>{catalog.typography_presets?.map(x=><option key={x.key} value={x.key}>{x.category} · {x.name}</option>)}</select></Field><Field label="Heading scale"><select value={draft.typography?.heading_scale||'normal'} onChange={e=>update('typography','heading_scale',e.target.value)}><option>compact</option><option>normal</option><option>large</option><option>display</option></select></Field><Field label="Body scale"><select value={draft.typography?.body_scale||'normal'} onChange={e=>update('typography','body_scale',e.target.value)}><option>compact</option><option>normal</option><option>large</option></select></Field><Field label="Letter spacing"><select value={draft.typography?.letter_spacing||'normal'} onChange={e=>update('typography','letter_spacing',e.target.value)}><option>tight</option><option>normal</option><option>wide</option></select></Field></div>{font&&<div className="font-sample" style={{fontFamily:font.body_stack}}><span>{font.name}</span><strong style={{fontFamily:font.heading_stack}}>The quick brown fox</strong><p>Beautiful commerce typography that adapts safely across devices.</p><small>Heading: {font.heading_stack}<br/>Body: {font.body_stack}</small></div>}</Card>
   <Card title="Layout" subtitle="Choose safe page structures instead of editing React code."><div className="layout-grid">{Object.entries(layouts).map(([key,opts])=><Field key={key} label={key.replace(/_/g,' ')}><select value={draft.layout?.[key]||fallback.layout[key]} onChange={e=>update('layout',key,e.target.value)}>{opts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>)}</div></Card>
   <Card title="Customer features"><div className="feature-grid">{[['search','Product search'],['promotions','Promotions'],['support','Customer support'],['ratings','Ratings'],['stock_status','Stock status'],['quick_add','Quick add']].map(([k,l])=><FeatureToggle key={k} label={l} checked={Boolean(draft.features?.[k])} onChange={v=>mutate(x=>{x.features={...(x.features||{}),[k]:v}})}/>)}</div></Card>
   <Card title="Navigation"><div className="nav-choice">{navItems.map(item=><label key={item}><input type="checkbox" checked={(draft.navigation||[]).includes(item)} onChange={e=>mutate(x=>{x.navigation=e.target.checked?[...(x.navigation||[]),item]:(x.navigation||[]).filter(v=>v!==item)})}/><span>{item}</span></label>)}</div></Card>
   <Card title="Home page builder" subtitle="Campaigns and commerce feeds"><div className="builder-list refined-builder">{sections.map((s,i)=>{const expanded=openSections[s.id]??i===0;return <div className={`builder-item ${expanded?'expanded':''}`} key={s.id||i}><div className="builder-handle">⋮⋮</div><div className="builder-main"><div className="builder-row"><select value={s.type} onChange={e=>patchSection(i,{type:e.target.value})}>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="toggle"><input type="checkbox" checked={s.enabled!==false} onChange={e=>patchSection(i,{enabled:e.target.checked})}/>Enabled</label><button className="builder-expand" onClick={()=>setOpenSections({...openSections,[s.id]:!expanded})}>{expanded?'Collapse':'Edit'}</button></div>{expanded&&<div className="builder-fields"><Field label="Title"><input value={s.title||''} onChange={e=>patchSection(i,{title:e.target.value})}/></Field><Field label="Body"><textarea value={s.body||''} onChange={e=>patchSection(i,{body:e.target.value})}/></Field><Field label="Image / video poster URL"><input value={s.image_url||''} onChange={e=>patchSection(i,{image_url:e.target.value})}/></Field><Field label="CTA label"><input value={s.cta_label||''} onChange={e=>patchSection(i,{cta_label:e.target.value})}/></Field><Field label="CTA path"><input value={s.cta_path||''} onChange={e=>patchSection(i,{cta_path:e.target.value})}/></Field><Field label="Item limit"><input type="number" min="1" max="24" value={s.limit||8} onChange={e=>patchSection(i,{limit:Number(e.target.value)})}/></Field></div>}<div className="builder-actions"><button onClick={()=>move(i,-1)} disabled={i===0}>↑</button><button onClick={()=>move(i,1)} disabled={i===sections.length-1}>↓</button><button className="danger-mini" onClick={()=>setSections(sections.filter((_,j)=>j!==i))}>×</button></div></div></div>})}<button className="add-section" onClick={add}>+ Add section</button></div></Card>
   <Card title="Version history" subtitle="Rollback publishes a new immutable version"><div className="history-list">{(data?.history||[]).map(x=><div key={x.version}><div><strong>Version {x.version}</strong><span>{x.state} · {x.template_key||'Custom'}</span></div>{has('customer_experience.publish')&&<button className="secondary small" onClick={()=>rollback(x.version)}>Rollback</button>}</div>)}</div></Card>
  </div>{preview&&<ExperiencePreview config={draft} storeName={data?.store?.name} font={font}/>}</div><Toast message={toast} onDone={()=>setToast('')}/>
 </>;
}
function FeatureToggle({label,checked,onChange}){return <label className="feature-toggle"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><div><strong>{label}</strong><span>{checked?'Enabled':'Disabled'}</span></div></label>}
function ExperiencePreview({config,storeName,font}){const style=useMemo(()=>({'--p':config.theme?.primary||'#166534','--s':config.theme?.secondary||'#111827','--bg':config.theme?.background||'#f8fafc','--surface':config.theme?.surface||'#fff','--txt':config.theme?.text||'#172033','--muted':config.theme?.muted_text||'#667085','--r':config.theme?.radius==='xl'?'30px':config.theme?.radius==='large'?'24px':config.theme?.radius==='small'?'8px':'16px','--preview-heading':font?.heading_stack||'system-ui','--preview-body':font?.body_stack||'system-ui'}),[config,font]);return <aside className="experience-preview"><div className="preview-sticky"><div className="eyebrow">Live renderer preview</div><div className={`phone-preview layout-${config.layout?.hero||'split'} card-${config.theme?.card_style||'clean'}`} style={style}>{config.branding?.announcement&&<div className="pv-announcement">{config.branding.announcement}</div>}<div className="pv-header"><span>{config.branding?.store_name?.slice(0,1)||'L'}</span><strong>{config.branding?.store_name||storeName||'Store'}</strong><i>{config.features?.search?'Search · ':''}Bag</i></div><div className="pv-hero"><small>{config.theme?.preset||'Custom'} · {config.typography?.preset}</small><h2>{config.branding?.hero_title||'Your storefront headline'}</h2><p>{config.branding?.hero_subtitle||'Customer-facing campaign copy.'}</p><button>{config.home?.sections?.[0]?.cta_label||'Explore'}</button></div><div className="pv-section"><b>Categories · {config.layout?.categories}</b><div><i/><i/><i/></div></div><div className="pv-section"><b>Products · {config.layout?.product_grid}</b><div><i/><i/><i/></div></div><div className="pv-nav">{(config.navigation||[]).map(n=><span key={n}>{n}</span>)}</div></div><p className="preview-note">Secure Preview opens the exact server-saved draft with real Customer Web data.</p></div></aside>}
