import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,DateTime,ErrorBox,Loading,Money,PageHeader,Stat,Table,statusTone}from'../components/UI.jsx';

export function DashboardPage(){
 const{api,session}=useAuth();const[s,setS]=useState({loading:true,error:null,data:{}});
 useEffect(()=>{let ok=true;(async()=>{const p=session.user.permissions||[];const jobs=[];const add=(k,perm,path)=>{if(!perm||p.includes(perm))jobs.push(api.request(path).then(x=>[k,x.data]).catch(e=>[k,{error:e}]))};add('tenant','tenant.settings.read','/v1/merchant/tenant');add('products','catalog.read','/v1/merchant/products?limit=100');add('orders','orders.read','/v1/merchant/orders?limit=100');add('customers','customers.read','/v1/merchant/customers?limit=100');add('payments','payments.read','/v1/merchant/payments?limit=100');add('inventory','inventory.read','/v1/merchant/inventory');add('promotions','promotions.read','/v1/merchant/promotions');const rows=await Promise.all(jobs);if(ok)setS({loading:false,error:null,data:Object.fromEntries(rows)})})().catch(error=>ok&&setS({loading:false,error,data:{}}));return()=>{ok=false}},[api,session]);
 const metrics=useMemo(()=>{const d=s.data,orders=d.orders?.orders||[],products=d.products?.products||[],customers=d.customers?.customers||[],payments=d.payments?.payments||[],inventory=d.inventory?.inventory||[],promotions=d.promotions?.promotions||[];return{orders,products,customers,payments,inventory,promotions,openOrders:orders.filter(x=>!['COMPLETED','CANCELLED','REFUNDED'].includes(x.status)),pendingPayments:payments.filter(x=>['PENDING','FAILED'].includes(x.status)),lowStock:inventory.filter(x=>Number(x.available)<=5),published:products.filter(x=>x.status==='PUBLISHED'),activePromos:promotions.filter(x=>x.status==='ACTIVE')}} ,[s.data]);
 if(s.loading)return <Loading/>;const d=s.data,m=metrics;const currency=d.tenant?.tenant?.currency||'USD';const recent=m.orders.slice(0,8);
 return <><PageHeader title="Operations overview" description="A tenant-scoped command view of catalog readiness, order workload, payment exceptions, customer activity, inventory risk, and active promotions."/><ErrorBox error={s.error}/><div className="stats-grid"><Stat label="Open orders" value={m.openOrders.length} detail={`${m.orders.length} loaded`}/><Stat label="Payment attention" value={m.pendingPayments.length} detail="pending or failed"/><Stat label="Low stock" value={m.lowStock.length} detail="available ≤ 5"/><Stat label="Published catalog" value={m.published.length} detail={`${m.products.length} products loaded`}/></div><div className="ops-grid"><Card title="Order queue" subtitle="Most recent operational work"><Table rows={recent} keyField="public_id" columns={[{key:'order_number',label:'Order'},{key:'customer_display_name',label:'Customer'},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'payment_status',label:'Payment',render:r=><Badge tone={statusTone(r.payment_status)}>{r.payment_status}</Badge>},{key:'grand_total',label:'Total',render:r=><Money value={r.grand_total} currency={r.currency||currency}/>},{key:'created_at',label:'Created',render:r=><DateTime value={r.created_at}/>}]} /></Card><div><Card title="Attention center" subtitle="Signals worth checking before routine work"><div className="attention-list"><div><span className="attention-dot warning"/><div><strong>{m.pendingPayments.length} payment exceptions</strong><span>Pending or failed payments in the loaded window.</span></div></div><div><span className="attention-dot warning"/><div><strong>{m.lowStock.length} low-stock lines</strong><span>Inventory with five or fewer available units.</span></div></div><div><span className="attention-dot success"/><div><strong>{m.activePromos.length} active promotions</strong><span>Programs currently marked ACTIVE.</span></div></div><div><span className="attention-dot neutral"/><div><strong>{m.customers.length} customers loaded</strong><span>Latest customer directory window.</span></div></div></div></Card><Card title="Store pulse"><div className="pulse-list"><div><span>On hand</span><strong>{m.inventory.reduce((a,x)=>a+Number(x.on_hand||0),0)}</strong></div><div><span>Reserved</span><strong>{m.inventory.reduce((a,x)=>a+Number(x.reserved||0),0)}</strong></div><div><span>Payment volume</span><strong><Money value={m.payments.reduce((a,x)=>a+Number(x.amount||0),0)} currency={currency}/></strong></div><div><span>Tenant status</span><Badge tone={statusTone(d.tenant?.tenant?.status)}>{d.tenant?.tenant?.status||'Restricted'}</Badge></div></div></Card></div></div></>;
}
