import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{navigate}from'../app/router.js';
import{VbenAlert,VbenBadge,VbenButton,VbenCard,VbenDateTime,VbenIcon,VbenMetric,VbenMoney,VbenSkeleton,VbenTable,vbenStatusTone}from'../components/VbenUI.jsx';

const sourceLabels={tenant:'Tenant settings',products:'Products',orders:'Orders',customers:'Customers',payments:'Payments',inventory:'Inventory',promotions:'Promotions'};

export function DashboardPage(){
 const{api,session}=useAuth();const[s,setS]=useState({loading:true,error:null,data:{}});
 useEffect(()=>{let ok=true;(async()=>{const p=session.user.permissions||[];const jobs=[];const add=(k,perm,path)=>{if(!perm||p.includes(perm))jobs.push(api.request(path).then(x=>[k,x.data]).catch(e=>[k,{error:e}]))};add('tenant','tenant.settings.read','/v1/merchant/tenant');add('products','catalog.read','/v1/merchant/products?limit=100');add('orders','orders.read','/v1/merchant/orders?limit=100');add('customers','customers.read','/v1/merchant/customers?limit=100');add('payments','payments.read','/v1/merchant/payments?limit=100');add('inventory','inventory.read','/v1/merchant/inventory');add('promotions','promotions.read','/v1/merchant/promotions');const rows=await Promise.all(jobs);if(ok)setS({loading:false,error:null,data:Object.fromEntries(rows)})})().catch(error=>ok&&setS({loading:false,error,data:{}}));return()=>{ok=false}},[api,session]);
 const metrics=useMemo(()=>{const d=s.data,orders=d.orders?.orders||[],products=d.products?.products||[],customers=d.customers?.customers||[],payments=d.payments?.payments||[],inventory=d.inventory?.inventory||[],promotions=d.promotions?.promotions||[];return{orders,products,customers,payments,inventory,promotions,openOrders:orders.filter(x=>!['COMPLETED','CANCELLED','REFUNDED'].includes(x.status)),pendingPayments:payments.filter(x=>['PENDING','FAILED'].includes(x.status)),lowStock:inventory.filter(x=>Number(x.available)<=5),published:products.filter(x=>x.status==='PUBLISHED'),activePromos:promotions.filter(x=>x.status==='ACTIVE')}} ,[s.data]);
 const permissions=session.user.permissions||[];const can=permission=>!permission||permissions.includes(permission);
 if(s.loading)return <div className="vben-dashboard-loading"><div className="vben-dashboard-loading-head"><VbenSkeleton lines={2}/></div><div className="vben-dashboard-metrics">{Array.from({length:4},(_,i)=><div className="vben-dashboard-metric-skeleton" key={i}><VbenSkeleton lines={3}/></div>)}</div><div className="vben-dashboard-loading-grid"><div><VbenSkeleton lines={8}/></div><div><VbenSkeleton lines={6}/></div></div></div>;
 const d=s.data,m=metrics;const currency=d.tenant?.tenant?.currency||'USD';const recent=m.orders.slice(0,8);const tenantStatus=d.tenant?.tenant?.status||'Restricted';const onHand=m.inventory.reduce((a,x)=>a+Number(x.on_hand||0),0);const reserved=m.inventory.reduce((a,x)=>a+Number(x.reserved||0),0);const paymentVolume=m.payments.reduce((a,x)=>a+Number(x.amount||0),0);const sourceErrors=Object.entries(d).filter(([,value])=>value?.error).map(([key])=>sourceLabels[key]||key);
 const orderColumns=[{key:'order_number',label:'Order'},{key:'customer_display_name',label:'Customer'},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status}</VbenBadge>},{key:'payment_status',label:'Payment',render:r=><VbenBadge tone={vbenStatusTone(r.payment_status)}>{r.payment_status}</VbenBadge>},{key:'grand_total',label:'Total',render:r=><VbenMoney value={r.grand_total} currency={r.currency||currency}/>},{key:'created_at',label:'Created',render:r=><VbenDateTime value={r.created_at}/>}];
 const attention=[
  {key:'payments',icon:'payments',tone:'warning',value:m.pendingPayments.length,title:'Payment attention',description:'Pending or failed payments in the loaded window.',permission:'payments.read',route:'/payments'},
  {key:'inventory',icon:'inventory',tone:'warning',value:m.lowStock.length,title:'Low stock',description:'Inventory lines with five or fewer available units.',permission:'inventory.read',route:'/inventory'},
  {key:'promotions',icon:'promotions',tone:'success',value:m.activePromos.length,title:'Active promotions',description:'Promotion programs currently marked ACTIVE.',permission:'promotions.read',route:'/promotions'},
  {key:'customers',icon:'users',tone:'neutral',value:m.customers.length,title:'Customers loaded',description:'Latest customer directory window available to this role.',permission:'customers.read',route:'/customers'},
 ];
 return <div className="vben-dashboard-page">
  <header className="vben-dashboard-head"><div><div className="vben-dashboard-kicker"><VbenIcon name="dashboard" size={15}/>Merchant command center</div><h1>Operations overview</h1><p>A tenant-scoped command view of catalog readiness, order workload, payment exceptions, customer activity, inventory risk, and active promotions.</p><div className="vben-dashboard-context"><span>{session.tenantSlug}</span><i/> <span>{session.storeId?'Store context active':'Primary store context'}</span></div></div>{can('orders.read')&&<VbenButton variant="secondary" icon="orders" onClick={()=>navigate('/orders')}>Open orders</VbenButton>}</header>
  {s.error&&<VbenAlert tone="danger" title="Dashboard could not be loaded">Refresh the workspace and try again.</VbenAlert>}
  {sourceErrors.length>0&&<VbenAlert tone="warning" title="Some dashboard sources are unavailable">{sourceErrors.join(', ')} could not be loaded. Available modules remain usable.</VbenAlert>}
  <div className="vben-dashboard-metrics">
   <VbenMetric label="Open orders" value={m.openOrders.length} detail={`${m.orders.length} loaded`} icon="orders" tone="primary" onClick={can('orders.read')?()=>navigate('/orders'):undefined}/>
   <VbenMetric label="Payment attention" value={m.pendingPayments.length} detail="pending or failed" icon="payments" tone="warning" onClick={can('payments.read')?()=>navigate('/payments'):undefined}/>
   <VbenMetric label="Low stock" value={m.lowStock.length} detail="available ≤ 5" icon="inventory" tone="danger" onClick={can('inventory.read')?()=>navigate('/inventory'):undefined}/>
   <VbenMetric label="Published catalog" value={m.published.length} detail={`${m.products.length} products loaded`} icon="products" tone="success" onClick={can('catalog.read')?()=>navigate('/products'):undefined}/>
  </div>
  <div className="vben-dashboard-main-grid">
   <VbenCard title="Order queue" description="Most recent operational work in the loaded order window." actions={can('orders.read')?<VbenButton variant="ghost" size="sm" onClick={()=>navigate('/orders')}>View all</VbenButton>:null} className="vben-dashboard-orders-card">
    {can('orders.read')?<VbenTable rows={recent} keyField="public_id" columns={orderColumns} ariaLabel="Recent merchant orders" emptyTitle="No recent orders" emptyDescription="New orders will appear here when they enter the loaded window."/>:<VbenAlert title="Orders are permission scoped">This merchant role does not include orders.read.</VbenAlert>}
   </VbenCard>
   <VbenCard title="Attention center" description="Signals worth checking before routine work." className="vben-dashboard-attention-card"><div className="vben-attention-list">{attention.map(item=>{const enabled=can(item.permission);return <button type="button" className="vben-attention-item" key={item.key} disabled={!enabled} onClick={enabled?()=>navigate(item.route):undefined}><span className={`vben-attention-icon is-${item.tone}`}><VbenIcon name={item.icon} size={17}/></span><span className="vben-attention-copy"><strong>{item.value} {item.title.toLowerCase()}</strong><small>{item.description}</small></span>{enabled&&<VbenIcon name="arrowRight" size={15} className="vben-attention-arrow"/>}</button>})}</div></VbenCard>
  </div>
  <div className="vben-dashboard-bottom-grid">
   <VbenCard title="Store pulse" description="Operational totals from the data available to this merchant role."><div className="vben-pulse-grid"><div><span className="vben-pulse-icon"><VbenIcon name="box" size={17}/></span><small>On hand</small><strong>{onHand}</strong></div><div><span className="vben-pulse-icon"><VbenIcon name="inventory" size={17}/></span><small>Reserved</small><strong>{reserved}</strong></div><div><span className="vben-pulse-icon"><VbenIcon name="wallet" size={17}/></span><small>Payment volume</small><strong><VbenMoney value={paymentVolume} currency={currency}/></strong></div><div><span className="vben-pulse-icon"><VbenIcon name="pulse" size={17}/></span><small>Tenant status</small><strong><VbenBadge tone={vbenStatusTone(tenantStatus)}>{tenantStatus}</VbenBadge></strong></div></div></VbenCard>
   <VbenCard title="Commerce snapshot" description="Current loaded-window counts, without estimated trends or invented projections."><div className="vben-snapshot-list"><button type="button" disabled={!can('catalog.read')} onClick={can('catalog.read')?()=>navigate('/products'):undefined}><span><VbenIcon name="products" size={17}/><b>Catalog</b></span><strong>{m.published.length}<small> published / {m.products.length} loaded</small></strong></button><button type="button" disabled={!can('promotions.read')} onClick={can('promotions.read')?()=>navigate('/promotions'):undefined}><span><VbenIcon name="promotions" size={17}/><b>Promotions</b></span><strong>{m.activePromos.length}<small> active / {m.promotions.length} loaded</small></strong></button><button type="button" disabled={!can('customers.read')} onClick={can('customers.read')?()=>navigate('/customers'):undefined}><span><VbenIcon name="users" size={17}/><b>Customers</b></span><strong>{m.customers.length}<small> loaded</small></strong></button></div></VbenCard>
  </div>
 </div>;
}
