import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{navigate}from'../app/router.js';
import{VbenAlert,VbenBadge,VbenButton,VbenCard,VbenDateTime,VbenIcon,VbenMetric,VbenMoney,VbenSelect,VbenSkeleton,VbenTable,vbenStatusTone}from'../components/VbenUI.jsx';

const PERIODS={TODAY:'Today','7D':'Last 7 days','30D':'Last 30 days'};
const safeObject=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const safeList=value=>Array.isArray(value)?value:[];
const count=value=>Number.isFinite(Number(value))?Number(value):0;

export function DashboardPage(){
 const{api,session}=useAuth();const[period,setPeriod]=useState('TODAY'),[reloadKey,setReloadKey]=useState(0),[state,setState]=useState({loading:true,error:null,data:{}});
 useEffect(()=>{let active=true;setState(current=>({...current,loading:true,error:null}));api.request('/v1/merchant/business-dashboard',{query:{period}}).then(result=>{if(active)setState({loading:false,error:null,data:safeObject(result?.data)})}).catch(error=>{if(active)setState({loading:false,error,data:{}})});return()=>{active=false}},[api,period,reloadKey,session.storeId]);
 if(state.loading&&!Object.keys(state.data).length)return <DashboardLoading/>;
 const data=safeObject(state.data),context=safeObject(data.context),available=safeObject(data.available),sections=safeObject(data.sections),currency=context.period?.currency||'USD';
 const orders=safeObject(sections.orders),orderSummary=safeObject(orders.summary),payments=safeObject(sections.payments?.summary),inventory=safeObject(sections.inventory?.summary),delivery=safeObject(sections.delivery?.summary),kitchen=safeObject(sections.kitchen?.summary),staff=safeObject(sections.staff?.summary),customers=safeObject(sections.customers?.summary),loyalty=safeObject(sections.loyalty?.summary),catalog=safeObject(sections.catalog?.summary),promotions=safeObject(sections.promotions?.summary);const recent=safeList(orders.recent_orders);
 const paymentAttention=count(payments.pending)+count(payments.failed)+count(payments.refund_attention);const codCurrency=delivery.cod_currency||currency;
 const primaryMetrics=[
  available.orders&&{key:'sales',label:'Completed sales',value:<VbenMoney value={orderSummary.completed_sales} currency={currency}/>,detail:`${count(orderSummary.completed)} completed orders`,icon:'wallet',tone:'success',route:'/orders'},
  available.orders&&{key:'open',label:'Open orders',value:count(orderSummary.open),detail:`${count(orderSummary.processing)} in progress`,icon:'orders',tone:'primary',route:'/orders'},
  available.payments&&{key:'payments',label:'Payment attention',value:paymentAttention,detail:`${count(payments.failed)} failed · ${count(payments.refund_attention)} refunds`,icon:'payments',tone:paymentAttention?'warning':'success',route:'/payments'},
  available.delivery&&{key:'cod',label:'COD to reconcile',value:<VbenMoney value={delivery.cod_reconciliation_amount} currency={codCurrency}/>,detail:`${count(delivery.cod_reconciliation_count)} store-held collections`,icon:'receipt',tone:count(delivery.cod_reconciliation_count)?'warning':'success',route:'/delivery-cod'},
 ].filter(Boolean);
 const attention=[
  available.payments&&{key:'payment',icon:'payments',tone:paymentAttention?'warning':'success',value:paymentAttention,title:'Payment exceptions',description:`${count(payments.pending)} pending · ${count(payments.failed)} failed · ${count(payments.refund_attention)} refund requests`,route:'/payments'},
  available.delivery&&{key:'cod',icon:'receipt',tone:count(delivery.cod_reconciliation_count)?'warning':'success',value:count(delivery.cod_reconciliation_count),title:'COD reconciliation',description:`${count(delivery.cod_driver_custody_count)} with drivers · ${count(delivery.cod_reconciliation_count)} received by store`,route:'/delivery-cod'},
  available.inventory&&{key:'stock',icon:'inventory',tone:count(inventory.out_of_stock)?'warning':'success',value:count(inventory.low_stock),title:'Inventory risk',description:`${count(inventory.out_of_stock)} out of stock · ${count(inventory.low_stock)} at five or fewer available`,route:'/inventory'},
  available.delivery&&{key:'dispatch',icon:'truck',tone:count(delivery.ready_unassigned)?'warning':'success',value:count(delivery.ready_unassigned),title:'Ready without driver',description:`${count(delivery.active_dispatches)} active deliveries · ${count(delivery.awaiting_acceptance)} awaiting driver acceptance`,route:'/operations'},
  available.kitchen&&{key:'kitchen',icon:'box',tone:count(kitchen.waiting)?'warning':'success',value:count(kitchen.waiting),title:'Kitchen workload',description:`${count(kitchen.ready)} ready for pickup or dispatch`,route:'/operations'},
 ].filter(Boolean);
 const orderColumns=[{key:'order_number',label:'Order'},{key:'customer_display_name',label:'Customer'},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status||'UNKNOWN'}</VbenBadge>},{key:'payment_status',label:'Payment',render:r=><VbenBadge tone={vbenStatusTone(r.payment_status)}>{r.payment_status||'UNKNOWN'}</VbenBadge>},{key:'grand_total',label:'Total',render:r=><VbenMoney value={r.grand_total} currency={r.currency||currency}/>},{key:'created_at',label:'Created',render:r=><VbenDateTime value={r.created_at}/>}];
 const unavailable=safeList(data.unavailable);
 return <div className="vben-dashboard-page a10-business-command-center" data-testid="business-command-center-a10-1">
  <header className="vben-dashboard-head a10-command-head"><div><div className="vben-dashboard-kicker"><VbenIcon name="dashboard" size={15}/>Business command center</div><h1>Business overview</h1><p>Exact server-calculated sales, order workload, finance exceptions, fulfillment risk and customer signals for the authorized store and reporting period.</p><div className="vben-dashboard-context"><span>{context.store?.name||session.tenantSlug}</span><i/><span>{PERIODS[context.period?.key||period]}</span><i/><span>{context.period?.timezone||'Store timezone'}</span>{data.generated_at&&<><i/><span>Updated <VbenDateTime value={data.generated_at}/></span></>}</div></div><div className="a10-command-actions"><VbenSelect value={period} onChange={event=>setPeriod(event.target.value)} aria-label="Business dashboard reporting period"><option value="TODAY">Today</option><option value="7D">Last 7 days</option><option value="30D">Last 30 days</option></VbenSelect><VbenButton variant="secondary" icon="refresh" loading={state.loading} onClick={()=>setReloadKey(value=>value+1)}>Refresh</VbenButton><VbenButton variant="secondary" icon="pulse" onClick={()=>navigate('/operations')}>Operations</VbenButton></div></header>
  {state.error&&<VbenAlert tone="danger" title="Business dashboard could not be loaded">The command-center summary is temporarily unavailable. Other Merchant Admin workspaces remain available.</VbenAlert>}
  {unavailable.length>0&&<VbenAlert tone="warning" title="Some business signals are temporarily unavailable">{unavailable.join(', ')} could not be calculated. Available sections remain authoritative and usable.</VbenAlert>}
  {primaryMetrics.length?<div className="vben-dashboard-metrics a10-primary-metrics">{primaryMetrics.map(metric=><VbenMetric key={metric.key} label={metric.label} value={metric.value} detail={metric.detail} icon={metric.icon} tone={metric.tone} onClick={()=>navigate(metric.route)}/>)}</div>:<VbenAlert title="Dashboard is permission scoped">This role has no business-summary modules assigned. Use Staff Web for daily operational work or ask an owner to review access.</VbenAlert>}
  <div className="vben-dashboard-main-grid">
   <VbenCard title="Recent orders" description={`Latest orders created during ${PERIODS[context.period?.key||period].toLowerCase()}.`} actions={available.orders?<VbenButton variant="ghost" size="sm" onClick={()=>navigate('/orders')}>View all orders</VbenButton>:null} className="vben-dashboard-orders-card">{available.orders?<VbenTable rows={recent} keyField="id" columns={orderColumns} ariaLabel="Recent business orders" emptyTitle="No orders in this period" emptyDescription="Orders will appear here when customers place them."/>:<VbenAlert title="Orders are permission scoped">This role does not include orders.read.</VbenAlert>}</VbenCard>
   <VbenCard title="Attention center" description="Operational and financial exceptions that may require an owner or manager decision." className="vben-dashboard-attention-card">{attention.length?<div className="vben-attention-list">{attention.map(item=><button type="button" className="vben-attention-item" key={item.key} onClick={()=>navigate(item.route)}><span className={`vben-attention-icon is-${item.tone}`}><VbenIcon name={item.icon} size={17}/></span><span className="vben-attention-copy"><strong>{item.value} {item.title.toLowerCase()}</strong><small>{item.description}</small></span><VbenIcon name="arrowRight" size={15} className="vben-attention-arrow"/></button>)}</div>:<div className="a10-clear-state"><span><VbenIcon name="check" size={20}/></span><strong>No visible exceptions</strong><small>No attention signals are available for this role.</small></div>}</VbenCard>
  </div>
  <div className="a10-business-grid">
   {(available.delivery||available.kitchen)&&<VbenCard title="Fulfillment pulse" description="Live operational counts; execution stays in Staff Web and dedicated Operations workspaces."><div className="vben-pulse-grid a10-pulse-grid">{available.kitchen&&<Pulse icon="box" label="Kitchen waiting" value={count(kitchen.waiting)}/>} {available.kitchen&&<Pulse icon="check" label="Kitchen ready" value={count(kitchen.ready)}/>} {available.delivery&&<Pulse icon="truck" label="Active deliveries" value={count(delivery.active_dispatches)}/>} {available.delivery&&<Pulse icon="mapPin" label="Ready unassigned" value={count(delivery.ready_unassigned)}/>} {available.delivery&&<Pulse icon="users" label="Active drivers" value={count(delivery.active_drivers)}/>} {available.delivery&&<Pulse icon="receipt" label="Driver COD custody" value={<VbenMoney value={delivery.cod_driver_custody_amount} currency={codCurrency}/>}/>}</div><div className="a10-card-link"><VbenButton variant="ghost" size="sm" onClick={()=>navigate('/operations')}>Open Operations command center</VbenButton></div></VbenCard>}
   {(available.inventory||available.catalog||available.promotions)&&<VbenCard title="Commerce readiness" description="Current catalog, stock and growth-program readiness for this store."><div className="vben-snapshot-list">{available.inventory&&<Snapshot icon="inventory" label="Inventory" value={count(inventory.low_stock)} detail={`low stock · ${count(inventory.out_of_stock)} out`} route="/inventory"/>}{available.catalog&&<Snapshot icon="products" label="Catalog" value={count(catalog.published_products)} detail={`${count(catalog.unpublished_products)} unpublished`} route="/products"/>}{available.promotions&&<Snapshot icon="promotions" label="Promotions" value={count(promotions.active_promotions)} detail={`${count(promotions.inactive_promotions)} inactive`} route="/promotions"/>}</div></VbenCard>}
   {(available.customers||available.loyalty)&&<VbenCard title="Customers & loyalty" description="Period customer activity plus current VIP and reward exposure."><div className="vben-pulse-grid a10-pulse-grid">{available.customers&&<Pulse icon="users" label="Ordering customers" value={count(customers.ordering_customers)}/>} {available.customers&&<Pulse icon="history" label="Returning customers" value={count(customers.returning_customers)}/>} {available.customers&&<Pulse icon="plus" label="New tenant customers" value={count(customers.new_customers)}/>} {available.loyalty&&<Pulse icon="promotions" label="VIP members" value={count(loyalty.vip_members)}/>} {available.loyalty&&<Pulse icon="wallet" label="Reward liability" value={<VbenMoney value={loyalty.reward_liability} currency={currency}/>}/>}</div><div className="a10-card-link">{available.loyalty?<VbenButton variant="ghost" size="sm" onClick={()=>navigate('/vip-analytics')}>Open VIP analytics</VbenButton>:<VbenButton variant="ghost" size="sm" onClick={()=>navigate('/customers')}>Open customers</VbenButton>}</div></VbenCard>}
   {available.staff&&<VbenCard title="Staff coverage" description="Active merchant identities authorized for this store context. This is access coverage, not an online-presence estimate."><div className="vben-pulse-grid a10-pulse-grid"><Pulse icon="users" label="Active staff" value={count(staff.active_staff)}/><Pulse icon="truck" label="Drivers" value={count(staff.drivers)}/><Pulse icon="box" label="Kitchen" value={count(staff.kitchen)}/><Pulse icon="payments" label="Cashiers" value={count(staff.cashiers)}/><Pulse icon="pulse" label="Dispatchers" value={count(staff.dispatchers)}/></div><div className="a10-card-link"><VbenButton variant="ghost" size="sm" onClick={()=>navigate('/access')}>Manage Staff & Access</VbenButton></div></VbenCard>}
  </div>
  <footer className="a10-dashboard-foot"><VbenIcon name="info" size={15}/><span>All figures are exact values returned by the Backend for the selected authorized store and period. No projected revenue, estimated trends or browser-side extrapolation is used.</span></footer>
 </div>;
}

function DashboardLoading(){return <div className="vben-dashboard-loading"><div className="vben-dashboard-loading-head"><VbenSkeleton lines={3}/></div><div className="vben-dashboard-metrics">{Array.from({length:4},(_,i)=><div className="vben-dashboard-metric-skeleton" key={i}><VbenSkeleton lines={3}/></div>)}</div><div className="vben-dashboard-loading-grid"><div><VbenSkeleton lines={8}/></div><div><VbenSkeleton lines={7}/></div></div></div>}
function Pulse({icon,label,value}){return <div><span className="vben-pulse-icon"><VbenIcon name={icon} size={17}/></span><small>{label}</small><strong>{value}</strong></div>}
function Snapshot({icon,label,value,detail,route}){return <button type="button" onClick={()=>navigate(route)}><span><VbenIcon name={icon} size={17}/><b>{label}</b></span><strong>{value}<small>{detail}</small></strong></button>}
