import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{VbenAlert,VbenBadge,VbenButton,VbenCard,VbenField,VbenIcon,VbenInput,VbenMetric,VbenModal,VbenMoney,VbenPermissionNote,VbenSelect,VbenSkeleton,VbenTable,VbenTextarea,VbenToast,vbenStatusTone}from'../components/VbenUI.jsx';

const fresh={code:'',name:'',fulfillment_mode:'SHIPPING',status:'ACTIVE',flat_fee:0,free_over:'',min_order:0,estimated_min_minutes:60,estimated_max_minutes:180,sort_order:0,public_config:'{}'};
const freshDigital={product_id:'',product_type:'DIGITAL_VIDEO',access_mode:'VIEW_ONLY',download_limit:''};
const DIGITAL_ACCESS=[
 {value:'VIEW_ONLY',label:'View in secure library only'},
 {value:'DOWNLOAD_ONLY',label:'Download only'},
 {value:'VIEW_AND_DOWNLOAD',label:'View in library + allow download'},
];
export function DeliveryPage(){
 const{api,has}=useAuth();const[methods,setMethods]=useState([]),[products,setProducts]=useState([]),[err,setErr]=useState(null),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[digitalOpen,setDigitalOpen]=useState(false),[toast,setToast]=useState(''),[form,setForm]=useState(fresh),[digitalForm,setDigitalForm]=useState(freshDigital),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[q,setQ]=useState(''),[mode,setMode]=useState(''),[statusFilter,setStatusFilter]=useState('');
 const load=async()=>{setErr(null);setLoading(true);try{const d=await api.request('/v1/merchant/delivery-methods');setMethods(d.data.delivery_methods||[])}catch(e){setErr(e)}finally{setLoading(false)}};
 const loadProducts=async()=>{if(!has('catalog.read'))return;try{const d=await api.request('/v1/merchant/products',{query:{limit:100}});setProducts(d.data.products||[])}catch(e){setErr(e)}};
 useEffect(()=>{load();loadProducts()},[]);
 const parseConfig=x=>{try{const v=JSON.parse(x||'{}');if(!v||Array.isArray(v)||typeof v!=='object')throw new Error();return v}catch{const e=new Error('Public configuration must be a valid JSON object');e.code='INVALID_JSON';throw e}};
 const payload=f=>({...f,public_config:typeof f.public_config==='string'?parseConfig(f.public_config):(f.public_config||{}),flat_fee:Number(f.flat_fee||0),min_order:Number(f.min_order||0),free_over:f.free_over===''?null:Number(f.free_over),estimated_min_minutes:f.estimated_min_minutes===''?null:Number(f.estimated_min_minutes),estimated_max_minutes:f.estimated_max_minutes===''?null:Number(f.estimated_max_minutes),sort_order:Number(f.sort_order||0)});
 const submit=async(e)=>{e.preventDefault();setBusy('create');try{await api.request('/v1/merchant/delivery-methods',{method:'POST',body:payload(form)});setOpen(false);setForm(fresh);setToast('Delivery method created');await load()}catch(e){setErr(e)}finally{setBusy('')}};
 const startEdit=r=>setEdit({...r,free_over:r.free_over??'',public_config:JSON.stringify(r.public_config||{},null,2)});
 const save=async()=>{setBusy('save');try{await api.request(`/v1/merchant/delivery-methods/${encodeURIComponent(edit.id)}`,{method:'PATCH',body:payload({name:edit.name,status:edit.status,flat_fee:edit.flat_fee,free_over:edit.free_over,min_order:edit.min_order,estimated_min_minutes:edit.estimated_min_minutes,estimated_max_minutes:edit.estimated_max_minutes,sort_order:edit.sort_order,public_config:edit.public_config})});setEdit(null);setToast('Delivery method updated');await load()}catch(e){setErr(e)}finally{setBusy('')}};
 const openDigitalConversion=()=>{const first=products[0];setDigitalForm({...freshDigital,product_id:first?.public_id||'',product_type:first?.product_type==='DIGITAL_IMAGE'?'DIGITAL_IMAGE':'DIGITAL_VIDEO'});setDigitalOpen(true)};
 const convertDigital=async(e)=>{e.preventDefault();if(!digitalForm.product_id)return;setBusy('digital');setErr(null);try{const body={product_type:digitalForm.product_type,access_mode:digitalForm.access_mode,download_limit:digitalForm.access_mode==='VIEW_ONLY'?null:(digitalForm.download_limit===''?null:Number(digitalForm.download_limit))};const result=await api.request(`/v1/merchant/products/${encodeURIComponent(digitalForm.product_id)}/nature`,{method:'PUT',body});const repaired=Number(result.data.conversion?.repaired_active_cart_items||0);setDigitalOpen(false);setToast(`Product converted to ${digitalForm.product_type.replaceAll('_',' ')}${repaired?` · ${repaired} active cart item${repaired===1?'':'s'} repaired`:''}`);await loadProducts()}catch(e){setErr(e)}finally{setBusy('')}};
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();return methods.filter(r=>(!mode||r.fulfillment_mode===mode)&&(!statusFilter||r.status===statusFilter)&&(!x||`${r.name||''} ${r.code||''} ${r.fulfillment_mode||''}`.toLowerCase().includes(x)))},[methods,q,mode,statusFilter]);
 const metrics=useMemo(()=>({all:methods.length,active:methods.filter(x=>x.status==='ACTIVE').length,shipping:methods.filter(x=>x.fulfillment_mode==='SHIPPING').length,local:methods.filter(x=>x.fulfillment_mode!=='SHIPPING').length}),[methods]);
 const selectedDigitalProduct=products.find(x=>x.public_id===digitalForm.product_id)||null;
 if(!has('delivery.read'))return <VbenPermissionNote permission="delivery.read"/>;
 return <div className="vben-delivery-page">
  <header className="vben-delivery-head"><div><span className="vben-delivery-kicker"><VbenIcon name="truck" size={14}/> Fulfillment operations</span><h1>Delivery methods</h1><p>Configure shipping, local delivery and pickup pricing, order thresholds, ETA ranges and customer-safe provider options.</p></div><div className="vben-delivery-head-actions"><VbenButton variant="secondary" icon="refresh" onClick={()=>{load();loadProducts()}} loading={loading}>Refresh</VbenButton>{has('delivery.manage')&&<VbenButton icon="plus" onClick={()=>setOpen(true)}>Add delivery method</VbenButton>}</div></header>
  {err&&<VbenAlert tone="danger" title={err.code||'Delivery operation failed'}>{err.message||'The delivery operation could not be completed.'}</VbenAlert>}
  {has('catalog.read')&&<VbenCard title="Digital products use Product Nature, not Delivery Methods" description="DIGITAL_ACCESS and DIGITAL_DOWNLOAD are secure product-entitlement modes. They do not have a delivery fee, ETA or shipping provider and therefore are intentionally not listed in the Fulfillment mode dropdown on this page."><div className="vben-delivery-digital-guidance"><VbenAlert tone="info" title="Selling an image or video?">Set the product to Digital image or Digital video and choose View, Download, or View + Download. Digital-only carts then skip the physical Delivery method section at checkout.</VbenAlert>{has('catalog.write')&&<VbenButton variant="secondary" icon="products" onClick={openDigitalConversion} disabled={!products.length}>Convert an existing product</VbenButton>}</div></VbenCard>}
  <section className="vben-delivery-metrics"><VbenMetric label="Methods" value={metrics.all} detail="Configured methods" icon="truck"/><VbenMetric label="Active" value={metrics.active} detail="Customer available" icon="check" tone="success"/><VbenMetric label="Shipping" value={metrics.shipping} detail="Shipping methods" icon="box"/><VbenMetric label="Pickup / local" value={metrics.local} detail="Non-shipping methods" icon="mapPin" tone="neutral"/></section>
  <VbenCard title="Delivery configuration" description="Select a method to edit merchant-facing fulfillment configuration" className="vben-delivery-card"><div className="vben-delivery-toolbar"><VbenInput icon="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, code or mode"/><VbenSelect value={mode} onChange={e=>setMode(e.target.value)}><option value="">All modes</option><option>SHIPPING</option><option>LOCAL_DELIVERY</option><option>PICKUP</option></VbenSelect><VbenSelect value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option></VbenSelect><span className="vben-delivery-result-count">{filtered.length} shown</span></div>{loading?<div className="vben-delivery-loading"><VbenSkeleton lines={5}/></div>:<VbenTable ariaLabel="Delivery methods" rows={filtered} keyField="id" emptyTitle="No delivery methods" emptyDescription="Configure a shipping, local delivery or pickup method for checkout." columns={[{key:'name',label:'Method',render:r=><button className="vben-delivery-method-link" onClick={()=>has('delivery.manage')&&startEdit(r)} disabled={!has('delivery.manage')}><span className="vben-delivery-method-icon"><VbenIcon name={r.fulfillment_mode==='SHIPPING'?'truck':r.fulfillment_mode==='PICKUP'?'mapPin':'box'} size={16}/></span><span><strong>{r.name}</strong><small>{r.code}</small></span></button>},{key:'fulfillment_mode',label:'Mode',render:r=><VbenBadge tone="neutral">{r.fulfillment_mode}</VbenBadge>},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status}</VbenBadge>},{key:'flat_fee',label:'Flat fee',render:r=><VbenMoney value={r.flat_fee}/>},{key:'free_over',label:'Free over',render:r=>r.free_over==null?'—':<VbenMoney value={r.free_over}/>},{key:'min_order',label:'Minimum',render:r=><VbenMoney value={r.min_order}/>},{key:'estimated_min_minutes',label:'ETA',render:r=><span className="vben-delivery-eta">{r.estimated_min_minutes??'—'}–{r.estimated_max_minutes??'—'} min</span>}]} />}</VbenCard>
  <VbenModal open={open} onClose={()=>!busy&&setOpen(false)} title="New delivery method" size="lg" footer={<><VbenButton variant="secondary" disabled={!!busy} onClick={()=>setOpen(false)}>Cancel</VbenButton><VbenButton type="submit" form="delivery-form" loading={busy==='create'}>Create method</VbenButton></>}><DeliveryForm form={form} setForm={setForm} onSubmit={submit} id="delivery-form" includeCode/></VbenModal>
  <VbenModal open={!!edit} onClose={()=>!busy&&setEdit(null)} title="Edit delivery method" size="lg" footer={<><VbenButton variant="secondary" disabled={!!busy} onClick={()=>setEdit(null)}>Cancel</VbenButton><VbenButton onClick={save} loading={busy==='save'}>Save changes</VbenButton></>}>{edit&&<div className="vben-delivery-edit"><div className="vben-delivery-summary"><div><span>Code</span><strong>{edit.code}</strong></div><div><span>Mode</span><strong>{edit.fulfillment_mode}</strong></div></div><DeliveryFields form={edit} setForm={setEdit}/></div>}</VbenModal>
  <VbenModal open={digitalOpen} onClose={()=>!busy&&setDigitalOpen(false)} title="Convert existing product to digital" size="lg" footer={<><VbenButton variant="secondary" disabled={!!busy} onClick={()=>setDigitalOpen(false)}>Cancel</VbenButton><VbenButton type="submit" form="digital-product-conversion" loading={busy==='digital'} disabled={!digitalForm.product_id}>Convert product</VbenButton></>}><form id="digital-product-conversion" onSubmit={convertDigital} className="vben-delivery-form"><VbenAlert tone="warning" title="Safe conversion rule">Product Nature can change only when the product has no order history. Existing orders are never rewritten. Any incompatible item in an active customer cart is repaired automatically.</VbenAlert><div className="vben-delivery-form-grid"><VbenField label="Product" className="vben-delivery-span-2"><VbenSelect value={digitalForm.product_id} onChange={e=>setDigitalForm({...digitalForm,product_id:e.target.value})}>{products.map(p=><option key={p.public_id} value={p.public_id}>{p.name} · {p.product_type}</option>)}</VbenSelect>{selectedDigitalProduct&&<small>Current nature: {selectedDigitalProduct.product_type}</small>}</VbenField><VbenField label="New Product Nature"><VbenSelect value={digitalForm.product_type} onChange={e=>setDigitalForm({...digitalForm,product_type:e.target.value})}><option value="DIGITAL_VIDEO">Digital video</option><option value="DIGITAL_IMAGE">Digital image</option></VbenSelect></VbenField><VbenField label="Customer access"><VbenSelect value={digitalForm.access_mode} onChange={e=>setDigitalForm({...digitalForm,access_mode:e.target.value,download_limit:e.target.value==='VIEW_ONLY'?'':digitalForm.download_limit})}>{DIGITAL_ACCESS.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</VbenSelect></VbenField>{digitalForm.access_mode!=='VIEW_ONLY'&&<VbenField label="Download limit" hint="Leave blank for unlimited downloads."><VbenInput type="number" min="0" step="1" value={digitalForm.download_limit} onChange={e=>setDigitalForm({...digitalForm,download_limit:e.target.value})} placeholder="Unlimited"/></VbenField>}<div className="vben-delivery-span-2"><VbenAlert tone="info" title="After conversion">Attach the purchased image/video as PRIVATE media on the product. PUBLIC media remains storefront preview content. Customers receive the private asset through My Library only after trusted PAID status.</VbenAlert></div></div></form></VbenModal>
  <VbenToast message={toast} onDone={()=>setToast('')}/>
 </div>;
}
function DeliveryForm({form,setForm,onSubmit,id,includeCode}){return <form id={id} onSubmit={onSubmit} className="vben-delivery-form"><div className="vben-delivery-form-grid">{includeCode&&<><VbenField label="Code" required><VbenInput value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></VbenField><VbenField label="Name" required><VbenInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></VbenField><VbenField label="Fulfillment mode"><VbenSelect value={form.fulfillment_mode} onChange={e=>setForm({...form,fulfillment_mode:e.target.value})}><option>SHIPPING</option><option>LOCAL_DELIVERY</option><option>PICKUP</option></VbenSelect></VbenField></>}<DeliveryFields form={form} setForm={setForm} includeName={!includeCode}/></div></form>}
function DeliveryFields({form,setForm,includeName=true}){return <>{includeName&&<VbenField label="Name"><VbenInput value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></VbenField>}<VbenField label="Status"><VbenSelect value={form.status||'ACTIVE'} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></VbenSelect></VbenField><VbenField label="Flat fee"><VbenInput type="number" min="0" step="0.01" value={form.flat_fee??0} onChange={e=>setForm({...form,flat_fee:e.target.value})}/></VbenField><VbenField label="Free over"><VbenInput type="number" min="0" step="0.01" value={form.free_over??''} onChange={e=>setForm({...form,free_over:e.target.value})} placeholder="Optional"/></VbenField><VbenField label="Minimum order"><VbenInput type="number" min="0" step="0.01" value={form.min_order??0} onChange={e=>setForm({...form,min_order:e.target.value})}/></VbenField><VbenField label="Min ETA (minutes)"><VbenInput type="number" min="0" value={form.estimated_min_minutes??''} onChange={e=>setForm({...form,estimated_min_minutes:e.target.value})}/></VbenField><VbenField label="Max ETA (minutes)"><VbenInput type="number" min="0" value={form.estimated_max_minutes??''} onChange={e=>setForm({...form,estimated_max_minutes:e.target.value})}/></VbenField><VbenField label="Sort order"><VbenInput type="number" value={form.sort_order??0} onChange={e=>setForm({...form,sort_order:e.target.value})}/></VbenField><VbenField label="Public configuration (JSON)" hint="Customer-safe delivery options only; never put secrets here." className="vben-delivery-span-2"><VbenTextarea className="vben-delivery-code" value={typeof form.public_config==='string'?form.public_config:JSON.stringify(form.public_config||{},null,2)} onChange={e=>setForm({...form,public_config:e.target.value})}/></VbenField></>}
