import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,ErrorBox,Field,Modal,Money,PageHeader,Table,Toast,statusTone,PermissionNote}from'../components/UI.jsx';

const fresh={code:'',name:'',fulfillment_mode:'SHIPPING',status:'ACTIVE',flat_fee:0,free_over:'',min_order:0,estimated_min_minutes:60,estimated_max_minutes:180,sort_order:0,public_config:'{}'};
export function DeliveryPage(){
 const{api,has}=useAuth();const[methods,setMethods]=useState([]),[err,setErr]=useState(null),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[toast,setToast]=useState(''),[form,setForm]=useState(fresh);
 const load=async()=>{setErr(null);try{const d=await api.request('/v1/merchant/delivery-methods');setMethods(d.data.delivery_methods)}catch(e){setErr(e)}};useEffect(()=>{load()},[]);
 const parseConfig=x=>{try{const v=JSON.parse(x||'{}');if(!v||Array.isArray(v)||typeof v!=='object')throw new Error();return v}catch{const e=new Error('Public configuration must be a valid JSON object');e.code='INVALID_JSON';throw e}};
 const payload=f=>({...f,public_config:typeof f.public_config==='string'?parseConfig(f.public_config):(f.public_config||{}),flat_fee:Number(f.flat_fee||0),min_order:Number(f.min_order||0),free_over:f.free_over===''?null:Number(f.free_over),estimated_min_minutes:f.estimated_min_minutes===''?null:Number(f.estimated_min_minutes),estimated_max_minutes:f.estimated_max_minutes===''?null:Number(f.estimated_max_minutes),sort_order:Number(f.sort_order||0)});
 const submit=async(e)=>{e.preventDefault();try{await api.request('/v1/merchant/delivery-methods',{method:'POST',body:payload(form)});setOpen(false);setForm(fresh);setToast('Delivery method created');load()}catch(e){setErr(e)}};
 const save=async()=>{try{await api.request(`/v1/merchant/delivery-methods/${encodeURIComponent(edit.id)}`,{method:'PATCH',body:payload({name:edit.name,status:edit.status,flat_fee:edit.flat_fee,free_over:edit.free_over,min_order:edit.min_order,estimated_min_minutes:edit.estimated_min_minutes,estimated_max_minutes:edit.estimated_max_minutes,sort_order:edit.sort_order,public_config:edit.public_config})});setEdit(null);setToast('Delivery method updated');load()}catch(e){setErr(e)}};
 if(!has('delivery.read'))return <PermissionNote permission="delivery.read"/>;
 return <><PageHeader title="Delivery" description="Configure shipping, local delivery, and pickup pricing, thresholds, ETAs, and operational availability." actions={has('delivery.manage')&&<button className="primary" onClick={()=>setOpen(true)}>Add delivery method</button>}/><ErrorBox error={err}/><div className="stats-grid compact"><div className="stat"><span>Methods</span><strong>{methods.length}</strong></div><div className="stat"><span>Active</span><strong>{methods.filter(x=>x.status==='ACTIVE').length}</strong></div><div className="stat"><span>Shipping</span><strong>{methods.filter(x=>x.fulfillment_mode==='SHIPPING').length}</strong></div><div className="stat"><span>Pickup / local</span><strong>{methods.filter(x=>x.fulfillment_mode!=='SHIPPING').length}</strong></div></div><Card title="Delivery methods" subtitle="Select a method to edit merchant-facing configuration"><Table rows={methods} keyField="id" columns={[{key:'name',label:'Method',render:r=><button className="link-btn" onClick={()=>has('delivery.manage')&&setEdit({...r,free_over:r.free_over??'',public_config:JSON.stringify(r.public_config||{},null,2)})}><strong>{r.name}</strong><small className="block">{r.code}</small></button>},{key:'fulfillment_mode',label:'Mode'},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'flat_fee',label:'Flat fee',render:r=><Money value={r.flat_fee}/>},{key:'free_over',label:'Free over',render:r=>r.free_over==null?'—':<Money value={r.free_over}/>},{key:'min_order',label:'Minimum',render:r=><Money value={r.min_order}/>},{key:'estimated_min_minutes',label:'ETA',render:r=>`${r.estimated_min_minutes??'—'}–${r.estimated_max_minutes??'—'} min`}]} /></Card>
 <Modal open={open} onClose={()=>setOpen(false)} title="New delivery method" footer={<><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" form="delivery-form">Create</button></>}><DeliveryForm form={form} setForm={setForm} onSubmit={submit} id="delivery-form" includeCode/></Modal>
 <Modal open={!!edit} onClose={()=>setEdit(null)} title="Edit delivery method" footer={<><button className="secondary" onClick={()=>setEdit(null)}>Cancel</button><button className="primary" onClick={save}>Save</button></>}>{edit&&<><div className="detail-grid"><div><span>Code</span><strong>{edit.code}</strong></div><div><span>Mode</span><strong>{edit.fulfillment_mode}</strong></div></div><DeliveryFields form={edit} setForm={setEdit}/></>}</Modal><Toast message={toast} onDone={()=>setToast('')}/></>;
}
function DeliveryForm({form,setForm,onSubmit,id,includeCode}){return <form id={id} onSubmit={onSubmit} className="form-grid">{includeCode&&<><Field label="Code"><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></Field><Field label="Name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="Fulfillment mode"><select value={form.fulfillment_mode} onChange={e=>setForm({...form,fulfillment_mode:e.target.value})}><option>SHIPPING</option><option>LOCAL_DELIVERY</option><option>PICKUP</option></select></Field></>}<DeliveryFields form={form} setForm={setForm} includeName={!includeCode}/></form>}
function DeliveryFields({form,setForm,includeName=true}){return <>{includeName&&<Field label="Name"><input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></Field>}<Field label="Status"><select value={form.status||'ACTIVE'} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></Field><Field label="Flat fee"><input type="number" min="0" step="0.01" value={form.flat_fee??0} onChange={e=>setForm({...form,flat_fee:e.target.value})}/></Field><Field label="Free over"><input type="number" min="0" step="0.01" value={form.free_over??''} onChange={e=>setForm({...form,free_over:e.target.value})} placeholder="Optional"/></Field><Field label="Minimum order"><input type="number" min="0" step="0.01" value={form.min_order??0} onChange={e=>setForm({...form,min_order:e.target.value})}/></Field><Field label="Min ETA (minutes)"><input type="number" min="0" value={form.estimated_min_minutes??''} onChange={e=>setForm({...form,estimated_min_minutes:e.target.value})}/></Field><Field label="Max ETA (minutes)"><input type="number" min="0" value={form.estimated_max_minutes??''} onChange={e=>setForm({...form,estimated_max_minutes:e.target.value})}/></Field><Field label="Sort order"><input type="number" value={form.sort_order??0} onChange={e=>setForm({...form,sort_order:e.target.value})}/></Field><Field label="Public configuration (JSON)" hint="Customer-safe delivery options only; never put secrets here."><textarea className="code-textarea" value={typeof form.public_config==='string'?form.public_config:JSON.stringify(form.public_config||{},null,2)} onChange={e=>setForm({...form,public_config:e.target.value})}/></Field></>}
