import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{navigate}from'../app/router.js';
import{staffWebConfigured,staffWebHref}from'../config/staffWeb.js';
import{VbenAlert,VbenButton,VbenCard,VbenPermissionNote,VbenToast}from'../components/VbenUI.jsx';

const defaultSettings={require_online_for_assignment:false,max_active_jobs:3,location_mode:'AUTO_ON_START_DELIVERY',location_update_seconds:10,tracking_stale_seconds:45,proof_policy:'ANY',cod_enabled:true,max_cod_held:'',allow_customer_call:true,allow_customer_chat:true,quick_replies:['I am on my way.','I have arrived.','I cannot find your location.','Please come to the entrance.','There is a small delay.'],supported_locales:['en','my']};
export function DriverAppSettingsPage(){
 const{api,has}=useAuth();const canRead=has('delivery.read'),canManage=has('delivery.manage');const[form,setForm]=useState(defaultSettings),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(null),[toast,setToast]=useState('');const driverUrl=staffWebHref('driver');
 const load=async()=>{if(!canRead)return;setLoading(true);setError(null);try{const r=await api.request('/v1/merchant/delivery/driver-app/settings');const s=r.data.settings||{};setForm({...defaultSettings,...s,max_cod_held:s.max_cod_held??'',quick_replies:s.quick_replies||defaultSettings.quick_replies,supported_locales:['en','my']})}catch(e){setError(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[canRead]);
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 const save=async()=>{if(!canManage)return;setBusy(true);setError(null);try{const body={require_online_for_assignment:Boolean(form.require_online_for_assignment),max_active_jobs:Number(form.max_active_jobs),location_mode:form.location_mode,location_update_seconds:Number(form.location_update_seconds),tracking_stale_seconds:Number(form.tracking_stale_seconds),proof_policy:form.proof_policy,cod_enabled:Boolean(form.cod_enabled),max_cod_held:form.max_cod_held===''?null:Number(form.max_cod_held),allow_customer_call:Boolean(form.allow_customer_call),allow_customer_chat:Boolean(form.allow_customer_chat),quick_replies:form.quick_replies.map(v=>v.trim()).filter(Boolean),supported_locales:['en','my']};const r=await api.request('/v1/merchant/delivery/driver-app/settings',{method:'PUT',body});setForm({...defaultSettings,...r.data.settings,max_cod_held:r.data.settings.max_cod_held??'',supported_locales:['en','my']});setToast('Driver App settings saved')}catch(e){setError(e)}finally{setBusy(false)}};
 if(!canRead)return <VbenPermissionNote permission="delivery.read"/>;
 return <div className="driver-settings-page" data-testid="driver-app-settings-v1">
  <header className="driver-settings-head"><div><span>DELIVERY SETTINGS</span><h1>Driver App settings</h1><p>Control the dedicated Staff Web Driver experience without exposing Merchant Admin complexity to drivers.</p></div><div><VbenButton variant="secondary" onClick={()=>navigate('/driver-access')}>Driver logins</VbenButton><VbenButton variant="secondary" onClick={()=>navigate('/delivery')}>Back to Delivery</VbenButton></div></header>
  {error&&<VbenAlert tone="danger" title={error.code||'Driver settings request failed'}>{error.message}{error.requestId&&<><br/><small>Request {error.requestId}</small></>}</VbenAlert>}
  {staffWebConfigured?<VbenAlert tone="info" title="Dedicated Staff Web workspace">Drivers open <strong>{driverUrl}</strong>. Linked DRIVER accounts see the assignment-scoped Driver workspace instead of Merchant Admin.</VbenAlert>:<VbenAlert tone="warning" title="Staff Web URL not configured">Set <code>VITE_LUKE_SHOP_STAFF_WEB_BASE_URL</code> in the Merchant Admin deployment before distributing the Driver URL.</VbenAlert>}
  <VbenAlert tone="info" title="Browser tracking boundary">Automatic GPS starts when the driver taps Start delivery while Staff Web is open. Reliable operating-system background tracking and native push are intentionally reserved for a later native-app reliability phase.</VbenAlert>
  {loading?<VbenCard title="Loading Driver App policy…"/>:<>
   <div className="driver-settings-grid">
    <VbenCard title="Assignment & capacity" description="These rules are enforced by Backend/database policy, not by the browser alone."><SettingToggle label="Require driver to be Online before assignment" checked={form.require_online_for_assignment} onChange={v=>set('require_online_for_assignment',v)}/><NumberSetting label="Maximum active jobs per driver" value={form.max_active_jobs} min="1" max="25" onChange={v=>set('max_active_jobs',v)}/></VbenCard>
    <VbenCard title="Location & tracking" description="GPS is scoped to active assigned deliveries."><label className="driver-setting-field">Tracking start<select value={form.location_mode} onChange={e=>set('location_mode',e.target.value)}><option value="AUTO_ON_START_DELIVERY">Automatic when Start delivery is tapped</option><option value="MANUAL">Driver starts manually</option></select></label><NumberSetting label="Location update interval (seconds)" value={form.location_update_seconds} min="5" max="120" onChange={v=>set('location_update_seconds',v)}/><NumberSetting label="Location stale after (seconds)" value={form.tracking_stale_seconds} min="15" max="600" onChange={v=>set('tracking_stale_seconds',v)}/></VbenCard>
    <VbenCard title="Delivery proof" description="Backend/database policy prevents delivery completion without the configured proof."><label className="driver-setting-field">Required proof<select value={form.proof_policy} onChange={e=>set('proof_policy',e.target.value)}><option value="ANY">Receiver acknowledgement or photo</option><option value="ACKNOWLEDGEMENT">Receiver acknowledgement</option><option value="PHOTO">Photo</option><option value="PHOTO_AND_ACKNOWLEDGEMENT">Photo + receiver acknowledgement</option></select></label></VbenCard>
    <VbenCard title="Cash on delivery" description="Driver workspace records custody only; cashier/owner reconciliation remains separate."><SettingToggle label="Allow COD collection in Driver workspace" checked={form.cod_enabled} onChange={v=>set('cod_enabled',v)}/><NumberSetting label="Maximum cash a driver may hold (blank = unlimited)" value={form.max_cod_held} min="0" step="0.01" onChange={v=>set('max_cod_held',v)}/></VbenCard>
    <VbenCard title="Customer contact" description="The current v1 delivery conversation is shared by Customer, Driver and Store."><SettingToggle label="Allow call customer" checked={form.allow_customer_call} onChange={v=>set('allow_customer_call',v)}/><SettingToggle label="Allow customer ↔ driver delivery chat" checked={form.allow_customer_chat} onChange={v=>set('allow_customer_chat',v)}/><p className="muted">Turning chat off makes Customer/Driver participation read-only. Separate Driver↔Store-only channels will be a later communication upgrade.</p></VbenCard>
    <VbenCard title="Driver language" description="Driver Mobile Pro v1 ships with simple English and Myanmar driver language support."><div className="detail-grid"><div><span>English</span><strong>EN</strong></div><div><span>Myanmar</span><strong>MY</strong></div></div></VbenCard>
   </div>
   <VbenCard title="Quick replies" description="One message per line. Keep them short enough to tap while delivering."><textarea className="driver-settings-textarea" value={form.quick_replies.join('\n')} onChange={e=>set('quick_replies',e.target.value.split('\n'))} rows="7" maxLength="3000"/></VbenCard>
   <div className="driver-settings-save"><VbenButton size="lg" loading={busy} onClick={save} disabled={!canManage}>Save Driver App settings</VbenButton>{!canManage&&<span>delivery.manage is required to change policy.</span>}</div>
  </>}
  <VbenToast message={toast} onDone={()=>setToast('')}/>
 </div>;
}
function SettingToggle({label,checked,onChange}){return <label className="driver-setting-toggle"><input type="checkbox" checked={Boolean(checked)} onChange={e=>onChange(e.target.checked)}/><span><strong>{label}</strong><small>{checked?'Enabled':'Disabled'}</small></span></label>}
function NumberSetting({label,value,onChange,...props}){return <label className="driver-setting-field">{label}<input type="number" value={value} onChange={e=>onChange(e.target.value)} {...props}/></label>}
