import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{navigate}from'../app/router.js';
import{VbenAlert,VbenBadge,VbenButton,VbenCard,VbenDateTime,VbenIcon,VbenMetric,VbenModal,VbenMoney,VbenSelect,VbenSkeleton,VbenTable,VbenTabs,VbenTextarea,vbenStatusTone}from'../components/VbenUI.jsx';

const PERIODS={TODAY:'Today','7D':'Last 7 days','30D':'Last 30 days'};
const safeObject=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const safeList=value=>Array.isArray(value)?value:[];
const count=value=>Number.isFinite(Number(value))?Number(value):0;

export function FinancePage(){
 const{api,session}=useAuth();const[period,setPeriod]=useState('TODAY'),[tab,setTab]=useState('overview'),[reloadKey,setReloadKey]=useState(0),[state,setState]=useState({loading:true,error:null,data:{}}),[target,setTarget]=useState(null),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[actionError,setActionError]=useState('');
 useEffect(()=>{let active=true;setState(current=>({...current,loading:true,error:null}));api.request('/v1/merchant/finance/overview',{query:{period}}).then(result=>{if(active)setState({loading:false,error:null,data:safeObject(result?.data)})}).catch(error=>{if(active)setState({loading:false,error,data:{}})});return()=>{active=false}},[api,period,reloadKey,session.storeId]);
 if(state.loading&&!Object.keys(state.data).length)return <FinanceLoading/>;
 const data=safeObject(state.data),context=safeObject(data.context),summary=safeObject(data.summary),actions=safeObject(data.actions),capabilities=safeObject(data.capabilities),reconciliation=safeObject(data.reconciliation),currency=summary.currency||context.period?.currency||'USD';
 const cod=safeList(reconciliation.cod),refunds=safeList(reconciliation.refunds),methods=safeList(data.payment_methods),activity=safeList(data.recent_activity);
 const reconcile=async()=>{if(!target||target.status!=='REMITTED'||!actions.cod_reconcile)return;setSaving(true);setActionError('');try{await api.request(`/v1/merchant/delivery/cod/${encodeURIComponent(target.id)}/reconcile`,{method:'POST',body:{note:note.trim()||'Reconciled from Finance Center'}});setTarget(null);setNote('');setReloadKey(value=>value+1)}catch(error){setActionError(error?.message||'COD reconciliation failed')}finally{setSaving(false)}};
 const metrics=[
  {key:'orders',label:'Completed order value',value:<VbenMoney value={summary.completed_order_value} currency={currency}/>,detail:`${count(summary.completed_orders)} completed orders`,icon:'wallet',tone:'success'},
  {key:'net',label:'Net paid volume',value:<VbenMoney value={summary.net_paid_volume} currency={currency}/>,detail:`Gross paid ${formatMoney(summary.gross_paid_volume,currency)}`,icon:'payments',tone:'primary'},
  {key:'refunds',label:'Refund attention',value:<VbenMoney value={summary.open_refund_amount} currency={currency}/>,detail:`${count(summary.open_refunds)} open refund cases`,icon:'history',tone:count(summary.open_refunds)?'warning':'success'},
  {key:'cod',label:'COD to reconcile',value:<VbenMoney value={summary.cod_awaiting_reconciliation_amount} currency={currency}/>,detail:`${count(summary.cod_awaiting_reconciliation_count)} remitted collections`,icon:'receipt',tone:count(summary.cod_awaiting_reconciliation_count)?'warning':'success'},
 ];
 const methodColumns=[{key:'name',label:'Method',render:r=><div className="finance-method-cell"><strong>{r.name||r.code}</strong><small>{r.provider_type}{r.provider_key?` · ${r.provider_key}`:''}</small></div>},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status||'UNKNOWN'}</VbenBadge>},{key:'payment_count',label:'Payments'},{key:'paid_count',label:'Paid'},{key:'pending_count',label:'Pending'},{key:'failed_count',label:'Failed'},{key:'gross_paid_volume',label:'Gross paid',render:r=><VbenMoney value={r.gross_paid_volume} currency={currency}/>},{key:'net_paid_volume',label:'Net paid',render:r=><VbenMoney value={r.net_paid_volume} currency={currency}/>}];
 const codColumns=[{key:'status',label:'Custody state',render:r=><VbenBadge tone={r.status==='REMITTED'?'warning':'neutral'}>{r.status}</VbenBadge>},{key:'order_number',label:'Order'},{key:'driver_name',label:'Driver'},{key:'collected_amount',label:'Cash',render:r=><VbenMoney value={r.collected_amount} currency={r.currency||currency}/>},{key:'collected_at',label:'Collected',render:r=><VbenDateTime value={r.collected_at}/>},{key:'remitted_at',label:'Remitted',render:r=><VbenDateTime value={r.remitted_at}/>},{key:'action',label:'Action',render:r=>r.status==='REMITTED'?(actions.cod_reconcile?<VbenButton size="sm" variant="secondary" onClick={()=>{setTarget(r);setNote('');setActionError('')}}>Reconcile</VbenButton>:<span className="finance-muted">Needs delivery.manage + payments.manage</span>):<span className="finance-muted">Awaiting remittance</span>}];
 const refundColumns=[{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status}</VbenBadge>},{key:'order_number',label:'Order'},{key:'customer_name',label:'Customer'},{key:'amount',label:'Amount',render:r=><VbenMoney value={r.amount} currency={r.currency||currency}/>},{key:'reason',label:'Reason'},{key:'requested_at',label:'Requested',render:r=><VbenDateTime value={r.requested_at}/>},{key:'action',label:'Action',render:()=>actions.refund_manage?<VbenButton size="sm" variant="ghost" onClick={()=>navigate('/payments')}>Open Payments</VbenButton>:<span className="finance-muted">Read only</span>}];
 const activityColumns=[{key:'kind',label:'Type',render:r=><VbenBadge tone={r.kind?.startsWith('COD_')?'warning':r.kind==='REFUND'?'neutral':'primary'}>{String(r.kind||'').replaceAll('_',' ')}</VbenBadge>},{key:'order_number',label:'Order'},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status||'UNKNOWN'}</VbenBadge>},{key:'channel',label:'Channel'},{key:'amount',label:'Amount',render:r=><VbenMoney value={r.amount} currency={r.currency||currency}/>},{key:'occurred_at',label:'Time',render:r=><VbenDateTime value={r.occurred_at}/>}];
 return <div className="finance-center-a10-2" data-testid="finance-reconciliation-center-a10-2">
  <header className="finance-head"><div><div className="finance-kicker"><VbenIcon name="wallet" size={15}/>Finance & reconciliation</div><h1>Finance Center</h1><p>Server-authoritative payment, refund and COD custody visibility for the selected store. Cash collection and financial settlement remain separate audited states.</p><div className="finance-context"><span>{context.store?.name||session.tenantSlug}</span><i/><span>{PERIODS[context.period?.key||period]}</span><i/><span>{context.period?.timezone||'Store timezone'}</span>{data.generated_at&&<><i/><span>Updated <VbenDateTime value={data.generated_at}/></span></>}</div></div><div className="finance-head-actions"><VbenSelect value={period} onChange={event=>setPeriod(event.target.value)} aria-label="Finance reporting period"><option value="TODAY">Today</option><option value="7D">Last 7 days</option><option value="30D">Last 30 days</option></VbenSelect><VbenButton variant="secondary" icon="refresh" loading={state.loading} onClick={()=>setReloadKey(value=>value+1)}>Refresh</VbenButton><VbenButton variant="secondary" icon="payments" onClick={()=>navigate('/payments')}>Payments setup</VbenButton></div></header>
  {state.error&&<VbenAlert tone="danger" title="Finance Center could not be loaded">Financial data is temporarily unavailable. No cached or estimated values are shown.</VbenAlert>}
  <VbenAlert tone="info" title="Financial custody boundary">Driver collection is custody evidence only. COD becomes financially settled only after store remittance and an authorized reconciliation using the existing audited Backend workflow.</VbenAlert>
  <div className="finance-metrics">{metrics.map(metric=><VbenMetric key={metric.key} {...metric}/>)}</div>
  <VbenTabs value={tab} onChange={setTab} items={[{value:'overview',label:'Overview'},{value:'reconciliation',label:'Reconciliation',count:cod.length+refunds.length},{value:'activity',label:'Activity',count:activity.length}]}/>
  {tab==='overview'&&<div className="finance-grid">
   <VbenCard title="Payment method performance" description={`Exact payment records created during ${PERIODS[context.period?.key||period].toLowerCase()}.`} className="finance-wide"><VbenTable rows={methods} columns={methodColumns} keyField="id" ariaLabel="Payment method financial performance" emptyTitle="No payment methods" emptyDescription="Configure payment methods in Payments before accepting checkout payments."/></VbenCard>
   <VbenCard title="Payment position" description="Current period payment state based on authoritative order payment records."><div className="finance-snapshot"><FinanceFact label="Gross paid" value={<VbenMoney value={summary.gross_paid_volume} currency={currency}/>} detail="Before recorded refunds"/><FinanceFact label="Net paid" value={<VbenMoney value={summary.net_paid_volume} currency={currency}/>} detail="Less recorded refunded amount"/><FinanceFact label="Pending" value={<VbenMoney value={summary.pending_payment_volume} currency={currency}/>} detail={`${count(summary.pending_payments)} payments`}/><FinanceFact label="Failed" value={count(summary.failed_payments)} detail="Payment records in failed state"/></div></VbenCard>
   <VbenCard title="COD custody" description="Current unresolved cash position is deliberately not restricted by the report period."><div className="finance-snapshot"><FinanceFact label="With drivers" value={<VbenMoney value={summary.cod_driver_custody_amount} currency={currency}/>} detail={`${count(summary.cod_driver_custody_count)} collections`}/><FinanceFact label="Awaiting reconciliation" value={<VbenMoney value={summary.cod_awaiting_reconciliation_amount} currency={currency}/>} detail={`${count(summary.cod_awaiting_reconciliation_count)} remitted`}/><FinanceFact label="Reconciled in period" value={<VbenMoney value={summary.cod_reconciled_period_amount} currency={currency}/>} detail={`${count(summary.cod_reconciled_period_count)} collections`}/><FinanceFact label="Refunded in period" value={<VbenMoney value={summary.refunded_volume_period} currency={currency}/>} detail={`${count(summary.succeeded_refunds_period)} successful refunds`}/></div></VbenCard>
   <VbenCard title="Finance capability boundary" description="Only facts backed by current production ledgers are shown."><div className="finance-capabilities"><Capability enabled={capabilities.provider_settlement_ledger} label="Provider settlement ledger"/><Capability enabled={capabilities.provider_fee_ledger} label="Provider fee ledger"/><Capability enabled={capabilities.manual_finance_adjustments} label="Manual finance adjustments"/><Capability enabled={capabilities.csv_export} label="CSV export"/></div><p className="finance-boundary-note">Unavailable capabilities are intentionally disabled rather than inferred from payment metadata. They can be added in later A10.2 slices with dedicated authoritative records.</p></VbenCard>
  </div>}
  {tab==='reconciliation'&&<div className="finance-reconciliation-grid"><VbenCard title="COD reconciliation queue" description="REMITTED cash can be settled by authorized management. COLLECTED cash is still in driver custody." className="finance-wide"><VbenTable rows={cod} columns={codColumns} keyField="id" ariaLabel="COD reconciliation queue" emptyTitle="No unresolved COD cash" emptyDescription="There are no driver-custody or remitted COD collections awaiting action."/></VbenCard><VbenCard title="Refund attention" description="Open refund requests remain visible regardless of report period. Refund execution stays in the existing Payments workflow." className="finance-wide"><VbenTable rows={refunds} columns={refundColumns} keyField="id" ariaLabel="Open refund attention queue" emptyTitle="No open refunds" emptyDescription="There are no requested or processing refunds awaiting attention."/></VbenCard></div>}
  {tab==='activity'&&<VbenCard title="Recent finance activity" description={`Payments, refund events and COD custody events during ${PERIODS[context.period?.key||period].toLowerCase()}.`}><VbenTable rows={activity} columns={activityColumns} keyField="id" ariaLabel="Recent finance activity" emptyTitle="No finance activity" emptyDescription="No payment, refund or COD events occurred in this reporting period."/></VbenCard>}
  <footer className="finance-foot"><VbenIcon name="info" size={15}/><span>{data.definitions?.net_paid_volume||'All values are returned by the Backend for the authorized store.'} No projected revenue, provider fees or settlement estimates are generated in the browser.</span></footer>
  <VbenModal open={Boolean(target)} onClose={()=>{if(!saving){setTarget(null);setActionError('')}}} title="Reconcile COD cash" eyebrow="Finance control" footer={<><VbenButton variant="secondary" disabled={saving} onClick={()=>{setTarget(null);setActionError('')}}>Cancel</VbenButton><VbenButton loading={saving} disabled={!target||target?.status!=='REMITTED'} onClick={reconcile}>Confirm reconciliation</VbenButton></>}><div className="finance-reconcile-modal"><VbenAlert tone="warning" title="This settles the order payment">Only confirm after the remitted cash has been checked against the expected amount. The Backend will preserve the immutable COD and payment audit trail.</VbenAlert>{target&&<div className="finance-reconcile-summary"><span><small>Order</small><strong>{target.order_number}</strong></span><span><small>Driver</small><strong>{target.driver_name}</strong></span><span><small>Expected</small><strong><VbenMoney value={target.expected_amount} currency={target.currency||currency}/></strong></span><span><small>Collected</small><strong><VbenMoney value={target.collected_amount} currency={target.currency||currency}/></strong></span></div>}<label className="finance-note-label"><span>Reconciliation note</span><VbenTextarea value={note} onChange={event=>setNote(event.target.value)} maxLength={1000} rows={4} placeholder="Optional internal note for the audit trail"/></label>{actionError&&<VbenAlert tone="danger" title="Reconciliation failed">{actionError}</VbenAlert>}</div></VbenModal>
 </div>;
}

function FinanceLoading(){return <div className="finance-loading"><VbenSkeleton lines={3}/><div className="finance-metrics">{Array.from({length:4},(_,i)=><div key={i}><VbenSkeleton lines={3}/></div>)}</div><VbenSkeleton lines={10}/></div>}
function FinanceFact({label,value,detail}){return <div className="finance-fact"><small>{label}</small><strong>{value}</strong><span>{detail}</span></div>}
function Capability({enabled,label}){return <div className={enabled?'is-enabled':'is-disabled'}><VbenIcon name={enabled?'check':'alert'} size={16}/><span><strong>{label}</strong><small>{enabled?'Available':'Not yet backed by an authoritative ledger'}</small></span></div>}
function formatMoney(value,currency){try{return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(value||0))}catch{return `${Number(value||0).toFixed(2)} ${currency}`}}
