import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,DateTime,ErrorBox,Field,Modal,PageHeader,Table,Tabs,Toast,PermissionNote}from'../components/UI.jsx';

export function InventoryPage(){
 const{api,has}=useAuth();
 const[rows,setRows]=useState([]),[locations,setLocations]=useState([]),[ledger,setLedger]=useState([]),[err,setErr]=useState(null),[toast,setToast]=useState('');
 const[tab,setTab]=useState('balances'),[open,setOpen]=useState(false),[locationOpen,setLocationOpen]=useState(false),[ledgerItem,setLedgerItem]=useState('');
 const[form,setForm]=useState({inventory_item_id:'',location_id:'',movement_type:'RECEIVE',quantity:1,reason:'Admin adjustment'}),[locationForm,setLocationForm]=useState({code:'',name:'',status:'ACTIVE',is_default:false});
 const load=async()=>{setErr(null);try{const[i,l]=await Promise.all([api.request('/v1/merchant/inventory'),api.request('/v1/merchant/inventory/locations')]);setRows(i.data.inventory);setLocations(l.data.locations||[])}catch(e){setErr(e)}};
 const loadLedger=async(item='')=>{setErr(null);try{const d=await api.request('/v1/merchant/inventory/ledger',{query:{inventory_item_id:item||undefined,limit:150}});setLedger(d.data.ledger||d.data.movements||[]);setLedgerItem(item)}catch(e){setErr(e)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(tab==='ledger')loadLedger(ledgerItem)},[tab]);
 const submit=async(e)=>{e.preventDefault();try{await api.request('/v1/merchant/inventory/adjustments',{method:'POST',body:{...form,quantity:Number(form.quantity),location_id:form.location_id||undefined}});setOpen(false);setToast('Inventory adjusted');await load();if(tab==='ledger')await loadLedger(form.inventory_item_id)}catch(e){setErr(e)}};
 const createLocation=async(e)=>{e.preventDefault();try{await api.request('/v1/merchant/inventory/locations',{method:'POST',body:locationForm});setLocationOpen(false);setLocationForm({code:'',name:'',status:'ACTIVE',is_default:false});setToast('Inventory location created');load()}catch(e){setErr(e)}};
 if(!has('inventory.read'))return <PermissionNote permission="inventory.read"/>;
 const onHand=rows.reduce((a,x)=>a+Number(x.on_hand||0),0),reserved=rows.reduce((a,x)=>a+Number(x.reserved||0),0),available=rows.reduce((a,x)=>a+Number(x.available||0),0),low=rows.filter(x=>Number(x.available)<=5).length;
 return <>
  <PageHeader title="Inventory" description="Operate stock balances, locations, reservations, and the append-only inventory ledger." actions={has('inventory.write')&&<><button className="secondary" onClick={()=>setLocationOpen(true)}>New location</button><button className="primary" onClick={()=>setOpen(true)}>Adjust stock</button></>}/>
  <ErrorBox error={err}/>
  <div className="stats-grid compact"><div className="stat"><span>Inventory lines</span><strong>{rows.length}</strong></div><div className="stat"><span>On hand</span><strong>{onHand}</strong></div><div className="stat"><span>Reserved</span><strong>{reserved}</strong></div><div className="stat"><span>Low stock lines</span><strong>{low}</strong><small>{available} units available total</small></div></div>
  <Tabs value={tab} onChange={setTab} items={[{value:'balances',label:'Balances',count:rows.length},{value:'ledger',label:'Ledger',count:ledger.length},{value:'locations',label:'Locations',count:locations.length}]}/>
  {tab==='balances'&&<Card title="Stock balances" subtitle="Reserved stock is protected from manual reductions"><Table rows={rows} keyField="inventory_item_id" columns={[{key:'product_name',label:'Product',render:r=><button className="link-btn" onClick={()=>{setTab('ledger');loadLedger(r.inventory_item_id)}}><strong>{r.product_name}</strong><small className="block">{r.variant_title||r.sku||'Base product'}</small></button>},{key:'location_name',label:'Location'},{key:'on_hand',label:'On hand'},{key:'reserved',label:'Reserved'},{key:'available',label:'Available',render:r=><Badge tone={Number(r.available)<=5?'warning':'success'}>{r.available}</Badge>}]} /></Card>}
  {tab==='ledger'&&<Card title="Inventory ledger" subtitle="Filter by an inventory item or inspect the latest movements"><div className="toolbar"><select className="toolbar-select" value={ledgerItem} onChange={e=>loadLedger(e.target.value)}><option value="">All inventory items</option>{[...new Map(rows.map(r=>[r.inventory_item_id,r])).values()].map(r=><option key={r.inventory_item_id} value={r.inventory_item_id}>{r.product_name} — {r.variant_title||r.sku||'Base'}</option>)}</select><button className="secondary" onClick={()=>loadLedger(ledgerItem)}>Refresh</button></div><Table rows={ledger} keyField="id" columns={[{key:'movement_type',label:'Movement',render:r=><Badge tone={Number(r.on_hand_delta)<0?'warning':'success'}>{r.movement_type}</Badge>},{key:'product_name',label:'Product',render:r=><div><strong>{r.product_name||r.sku||r.inventory_item_id}</strong><small className="block">{r.variant_title||r.location_name||''}</small></div>},{key:'on_hand_delta',label:'On-hand Δ'},{key:'reserved_delta',label:'Reserved Δ'},{key:'on_hand_after',label:'On hand after'},{key:'reserved_after',label:'Reserved after'},{key:'reason',label:'Reason'},{key:'created_at',label:'Time',render:r=><DateTime value={r.created_at}/>}]} /></Card>}
  {tab==='locations'&&<Card title="Inventory locations"><Table rows={locations} keyField="public_id" columns={[{key:'name',label:'Location',render:r=><div><strong>{r.name}</strong><small className="block">{r.code}</small></div>},{key:'status',label:'Status',render:r=><Badge tone={r.status==='ACTIVE'?'success':'danger'}>{r.status}</Badge>},{key:'is_default',label:'Default',render:r=>r.is_default?<Badge tone="success">DEFAULT</Badge>:'—'},{key:'created_at',label:'Created',render:r=><DateTime value={r.created_at}/>}]} /></Card>}
  <Modal open={open} onClose={()=>setOpen(false)} title="Inventory adjustment" footer={<><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" form="inv-form">Apply adjustment</button></>}><form id="inv-form" onSubmit={submit}><Field label="Inventory item"><select value={form.inventory_item_id} onChange={e=>setForm({...form,inventory_item_id:e.target.value})} required><option value="">Select item</option>{[...new Map(rows.map(r=>[r.inventory_item_id,r])).values()].map(r=><option key={r.inventory_item_id} value={r.inventory_item_id}>{r.product_name} — {r.variant_title||r.sku||'Base'}</option>)}</select></Field><Field label="Location"><select value={form.location_id} onChange={e=>setForm({...form,location_id:e.target.value})}><option value="">Default location</option>{locations.filter(l=>l.status==='ACTIVE').map(l=><option key={l.public_id} value={l.public_id}>{l.name}</option>)}</select></Field><Field label="Movement type"><select value={form.movement_type} onChange={e=>setForm({...form,movement_type:e.target.value})}>{['RECEIVE','RETURN','DAMAGE','ADJUSTMENT'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="On-hand delta" hint="DAMAGE requires a negative value; RECEIVE/RETURN require positive values."><input type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} required/></Field><Field label="Reason"><textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></Field></form></Modal>
  <Modal open={locationOpen} onClose={()=>setLocationOpen(false)} title="Create inventory location" footer={<><button className="secondary" onClick={()=>setLocationOpen(false)}>Cancel</button><button className="primary" form="loc-form">Create location</button></>}><form id="loc-form" onSubmit={createLocation}><Field label="Code"><input value={locationForm.code} onChange={e=>setLocationForm({...locationForm,code:e.target.value})} placeholder="WAREHOUSE_2" required/></Field><Field label="Name"><input value={locationForm.name} onChange={e=>setLocationForm({...locationForm,name:e.target.value})} required/></Field><Field label="Status"><select value={locationForm.status} onChange={e=>setLocationForm({...locationForm,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></Field><label className="switch-line"><input type="checkbox" checked={locationForm.is_default} onChange={e=>setLocationForm({...locationForm,is_default:e.target.checked})}/>Make this the default location</label></form></Modal>
  <Toast message={toast} onDone={()=>setToast('')}/>
 </>;
}
