import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';

const LABEL={NEW:'New order',ACCEPTED:'Accepted',PREPARING:'Preparing',READY:'Ready'};
const CTA={ACCEPTED:'Accept order',PREPARING:'Start preparing',READY:'Mark ready'};
const age=value=>{const ms=Date.now()-new Date(value).getTime(),m=Math.max(0,Math.floor(ms/60000));return m<60?`${m} min`: `${Math.floor(m/60)}h ${m%60}m`};
export function KitchenPage(){
 const{api,session,logout}=useAuth();const[jobs,setJobs]=useState([]),[settings,setSettings]=useState(null),[filter,setFilter]=useState('ACTIVE'),[busy,setBusy]=useState(''),[error,setError]=useState(null),[online,setOnline]=useState(navigator.onLine);
 const load=async()=>{try{const r=await api.request('/v1/merchant/kitchen/queue',{query:{limit:200}});setJobs(r.data.jobs||[]);setSettings(r.data.settings||null);setError(null)}catch(e){setError(e)}};
 useEffect(()=>{document.documentElement.classList.add('store-ops-document');load();const timer=setInterval(load,10000),on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{document.documentElement.classList.remove('store-ops-document');clearInterval(timer);removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 const visible=useMemo(()=>jobs.filter(j=>filter==='ACTIVE'?j.status!=='READY':j.status===filter),[jobs,filter]);const counts=useMemo(()=>Object.fromEntries(['NEW','ACCEPTED','PREPARING','READY'].map(s=>[s,jobs.filter(j=>j.status===s).length])),[jobs]);
 const transition=async job=>{if(!job.next_status||busy)return;setBusy(job.id);setError(null);try{await api.request(`/v1/merchant/kitchen/jobs/${encodeURIComponent(job.id)}/transition`,{method:'POST',body:{status:job.next_status}});await load()}catch(e){setError(e)}finally{setBusy('')}};
 return <main className="store-ops-page kitchen-page" data-testid="kitchen-operations-v1"><header className="store-ops-top"><div><span className="store-ops-eyebrow">KITCHEN</span><h1>Food orders</h1><p>{session?.user?.display_name||'Kitchen staff'} · {settings?.default_prep_minutes??20} min default prep</p></div><div className={`store-ops-network ${online?'online':'offline'}`}>{online?'Online':'Offline'}</div></header>{error&&<div className="store-ops-error"><strong>{error.code||'Kitchen error'}</strong><span>{error.message}</span></div>}<section className="store-ops-summary">{['NEW','ACCEPTED','PREPARING','READY'].map(s=><button key={s} className={filter===s?'active':''} onClick={()=>setFilter(s)}><strong>{counts[s]}</strong><span>{LABEL[s]}</span></button>)}</section><div className="store-ops-toolbar"><button className={filter==='ACTIVE'?'active':''} onClick={()=>setFilter('ACTIVE')}>Active queue</button><button onClick={load}>Refresh</button><button onClick={()=>logout('/kitchen-login')}>Sign out</button></div><section className="kitchen-list">{visible.length?visible.map(job=><article key={job.id} className={`kitchen-ticket status-${job.status.toLowerCase()}`}><div className="kitchen-ticket-head"><div><span className="store-ops-status">{LABEL[job.status]}</span><strong>{job.order_number}</strong></div><b>{age(job.order_created_at)}</b></div><h2>{job.customer_name||'Customer'}</h2><div className="kitchen-payment"><span>{job.provider_type==='CASH_ON_DELIVERY'?'COD':job.payment_method_name||'Payment'}</span><strong className={job.payment_ready?'ok':'warn'}>{job.provider_type==='CASH_ON_DELIVERY'?'Prepare · collect on delivery':job.payment_ready?'Payment ready':'Waiting for payment'}</strong></div><div className="kitchen-items">{(job.items||[]).map(item=><div key={item.id}><strong>{item.quantity} × {item.title}</strong>{item.variant&&<span>{item.variant}</span>}{Array.isArray(item.modifiers)&&item.modifiers.length>0&&<small>{item.modifiers.map(m=>m.name).filter(Boolean).join(' · ')}</small>}</div>)}</div>{job.estimated_ready_at&&<p className="kitchen-eta">Estimated ready: {new Date(job.estimated_ready_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p>}{job.next_status&&<button className="store-ops-primary sticky-action" onClick={()=>transition(job)} disabled={busy===job.id||!job.payment_ready}>{busy===job.id?'Updating…':CTA[job.next_status]}</button>}{!job.payment_ready&&<div className="store-ops-warning">Wait for payment confirmation. COD orders are allowed to prepare without prepayment.</div>}</article>):<div className="store-ops-empty"><h2>No orders in this queue</h2><p>The screen refreshes automatically every 10 seconds.</p></div>}</section></main>;
}
