import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Card,ErrorBox,Field,Loading,PageHeader,PermissionNote,Toast}from'../components/UI.jsx';
import{ADMIN_LOCALES,useAdminI18n}from'../i18n/AdminI18nContext.jsx';

const clone=x=>JSON.parse(JSON.stringify(x||{}));
const builtins=[{code:'en',label:'English',native_label:'English'},{code:'my',label:'Burmese',native_label:'မြန်မာ'},{code:'id',label:'Indonesian',native_label:'Bahasa Indonesia'}];
const baseLocalization={enabled:true,default_locale:'en',enabled_locales:['en'],locales:builtins,translations:{},ui:{}};
const normalizeCode=x=>String(x||'').trim().replace('_','-').toLowerCase().slice(0,12);
function localizationOf(config={}){const raw=config.localization||config.languages||{};const enabled=[...new Set((raw.enabled_locales||raw.locales?.filter(x=>x.enabled!==false).map(x=>x.code)||['en']).map(normalizeCode).filter(Boolean))].slice(0,4);const rows=[...(raw.locales||[])];for(const b of builtins)if(!rows.some(x=>normalizeCode(x.code)===b.code))rows.push(b);return{...baseLocalization,...raw,enabled_locales:enabled.length?enabled:['en'],locales:rows.slice(0,8),translations:raw.translations||{},ui:raw.ui||{}};}
function localeRow(loc,code){return(loc.locales||[]).find(x=>normalizeCode(x.code)===code)||builtins.find(x=>x.code===code)||{code,label:code.toUpperCase(),native_label:code.toUpperCase()};}
function pack(loc,code){return loc.translations?.[code]||{};}
function valueAt(obj,path){return path.reduce((v,k)=>v?.[k],obj)??'';}
function setAt(obj,path,value){let cur=obj;for(let i=0;i<path.length-1;i++){cur[path[i]]={...(cur[path[i]]||{})};cur=cur[path[i]];}cur[path[path.length-1]]=value;}

export function LanguagesPage(){
 const{api,has,session}=useAuth();const{t}=useAdminI18n();
 const[data,setData]=useState(null),[config,setConfig]=useState(null),[loc,setLoc]=useState(baseLocalization),[selectedLocale,setSelectedLocale]=useState('my'),[cats,setCats]=useState([]),[products,setProducts]=useState([]),[productRef,setProductRef]=useState(''),[product,setProduct]=useState(null),[custom,setCustom]=useState({code:'',label:'',native_label:''}),[err,setErr]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
 const load=async()=>{setErr(null);try{const exp=await api.request('/v1/merchant/customer-experience');const next=clone(exp.data.draft?.config||exp.data.published?.config||{});setData(exp.data);setConfig(next);const l=localizationOf(next);setLoc(l);setSelectedLocale(x=>l.enabled_locales.includes(x)?x:(l.enabled_locales.find(c=>c!==l.default_locale)||l.default_locale));const [c,p]=await Promise.allSettled([api.request('/v1/merchant/categories'),api.request('/v1/merchant/products',{query:{limit:100}})]);if(c.status==='fulfilled')setCats(c.value.data.categories||[]);if(p.status==='fulfilled')setProducts(p.value.data.products||[]);}catch(e){setErr(e)}};
 useEffect(()=>{load()},[session?.storeId]);
 useEffect(()=>{if(!productRef){setProduct(null);return}let live=true;api.request(`/v1/merchant/products/${encodeURIComponent(productRef)}`).then(r=>live&&setProduct(r.data.product)).catch(e=>live&&setErr(e));return()=>{live=false}},[productRef]);
 const languageLimit=Math.max(1,Math.min(4,Number(data?.experience_policy?.language_limit||4)));
 const selectedPack=useMemo(()=>pack(loc,selectedLocale),[loc,selectedLocale]);
 const mutateLoc=fn=>setLoc(prev=>{const next=clone(prev);fn(next);return next});
 const setTranslation=(path,value)=>mutateLoc(next=>{next.translations={...(next.translations||{})};next.translations[selectedLocale]={...(next.translations[selectedLocale]||{})};setAt(next.translations[selectedLocale],path,value)});
 const addLocale=()=>{const code=normalizeCode(custom.code);if(!code||loc.enabled_locales.includes(code)||loc.enabled_locales.length>=languageLimit)return;mutateLoc(next=>{next.enabled_locales=[...next.enabled_locales,code].slice(0,languageLimit);next.locales=[...(next.locales||[]).filter(x=>normalizeCode(x.code)!==code),{code,label:custom.label||code.toUpperCase(),native_label:custom.native_label||custom.label||code.toUpperCase(),enabled:true}]});setSelectedLocale(code);setCustom({code:'',label:'',native_label:''});};
 const toggleLocale=code=>{if(code===loc.default_locale)return;mutateLoc(next=>{next.enabled_locales=next.enabled_locales.includes(code)?next.enabled_locales.filter(x=>x!==code):[...next.enabled_locales,code].slice(0,languageLimit);if(!next.enabled_locales.includes(next.default_locale))next.enabled_locales.unshift(next.default_locale);next.enabled_locales=[...new Set(next.enabled_locales)].slice(0,languageLimit);});};
 const save=async(publish=false)=>{if(!has('customer_experience.manage'))return;setBusy(true);setErr(null);try{const next=clone(config);next.localization={...loc,enabled_locales:loc.enabled_locales.slice(0,languageLimit),locales:(loc.locales||[]).filter(x=>loc.enabled_locales.includes(normalizeCode(x.code))).slice(0,languageLimit)};const r=await api.request('/v1/merchant/customer-experience/draft',{method:'PUT',body:{config:next}});const saved=clone(r.data.draft?.config||next);setConfig(saved);setLoc(localizationOf(saved));if(publish&&has('customer_experience.publish')){await api.request('/v1/merchant/customer-experience/publish',{method:'POST',body:{}});setToast(t('languages.published'));await load();}else setToast(t('languages.saved'));}catch(e){setErr(e)}finally{setBusy(false)}};
 if(!has('customer_experience.read'))return <PermissionNote permission="customer_experience.read"/>;
 if(!config&&!err)return <Loading/>;
 const disabled=data?.experience_policy?.localization===false;
 return <>
  <PageHeader eyebrow="Customer Experience" title={t('languages.title')} description={t('languages.desc')} actions={<>{has('customer_experience.manage')&&<button className="secondary" disabled={busy||disabled} onClick={()=>save(false)}>{t('common.save')}</button>}{has('customer_experience.publish')&&<button className="primary" disabled={busy||disabled} onClick={()=>save(true)}>{t('common.publish')}</button>}</>}/>
  <ErrorBox error={err}/>
  {disabled&&<div className="alert"><strong>Platform capability disabled</strong><span>The platform owner has disabled storefront localization for this tenant.</span></div>}
  <div className="localization-layout">
   <Card title={t('languages.settings')} subtitle={`Maximum ${languageLimit} storefront language${languageLimit===1?'':'s'} for this tenant.`}>
    <label className="policy-row"><span><strong>{t('common.enabled')}</strong><small>Show the customer language selector.</small></span><input type="checkbox" checked={loc.enabled!==false} disabled={disabled} onChange={e=>mutateLoc(x=>{x.enabled=e.target.checked})}/></label>
    <Field label={t('languages.default')}><select value={loc.default_locale} disabled={disabled} onChange={e=>mutateLoc(x=>{x.default_locale=e.target.value;if(!x.enabled_locales.includes(e.target.value))x.enabled_locales=[e.target.value,...x.enabled_locales].slice(0,languageLimit)})}>{loc.enabled_locales.map(code=><option key={code} value={code}>{localeRow(loc,code).native_label||localeRow(loc,code).label}</option>)}</select></Field>
    <div className="locale-list">{[...new Set([...builtins.map(x=>x.code),...loc.enabled_locales])].map(code=>{const row=localeRow(loc,code);const on=loc.enabled_locales.includes(code);return <label className="locale-row" key={code}><span><strong>{row.native_label||row.label}</strong><small>{row.label} · {code}{code===loc.default_locale?' · Default':''}</small></span><input type="checkbox" checked={on} disabled={disabled||code===loc.default_locale||(!on&&loc.enabled_locales.length>=languageLimit)} onChange={()=>toggleLocale(code)}/></label>})}</div>
    <div className="custom-locale"><strong>{t('languages.add')}</strong><div className="three-field-grid"><Field label={t('languages.code')}><input value={custom.code} placeholder="hi" onChange={e=>setCustom({...custom,code:e.target.value})}/></Field><Field label={t('languages.label')}><input value={custom.label} placeholder="Hindi" onChange={e=>setCustom({...custom,label:e.target.value})}/></Field><Field label={t('languages.native')}><input value={custom.native_label} placeholder="हिन्दी" onChange={e=>setCustom({...custom,native_label:e.target.value})}/></Field></div><button className="secondary" disabled={disabled||loc.enabled_locales.length>=languageLimit||!custom.code.trim()} onClick={addLocale}>{t('common.add')}</button></div>
   </Card>
   <Card title={t('languages.translations')} subtitle="Merchant-created content uses manual translations. Missing fields fall back to the default storefront language.">
    <Field label={t('common.language')}><select value={selectedLocale} onChange={e=>setSelectedLocale(e.target.value)}>{loc.enabled_locales.map(code=><option key={code} value={code}>{localeRow(loc,code).native_label||localeRow(loc,code).label}</option>)}</select></Field>
    {selectedLocale===loc.default_locale&&<div className="info-strip">The default language uses your normal product/category/store content. You may still add overrides, but they are optional.</div>}
    <TranslationSections loc={loc} locale={selectedLocale} selectedPack={selectedPack} config={config} cats={cats} products={products} productRef={productRef} setProductRef={setProductRef} product={product} setTranslation={setTranslation} t={t}/>
   </Card>
  </div>
  <Toast message={toast} onDone={()=>setToast('')}/>
 </>;
}

function TranslationSections({selectedPack,config,cats,products,productRef,setProductRef,product,setTranslation,t}){
 const field=(label,path,base,textarea=false)=><Field label={label} hint={base?`Default: ${base}`:''}>{textarea?<textarea value={valueAt(selectedPack,path)} onChange={e=>setTranslation(path,e.target.value)}/>:<input value={valueAt(selectedPack,path)} onChange={e=>setTranslation(path,e.target.value)}/>}</Field>;
 return <div className="translation-sections">
  <details open><summary>{t('languages.brand')}</summary><div className="translation-panel">{field('Store display name',['branding','store_name'],config.branding?.store_name)}{field('Announcement',['branding','announcement'],config.branding?.announcement)}{field('Hero title',['branding','hero_title'],config.branding?.hero_title)}{field('Hero subtitle',['branding','hero_subtitle'],config.branding?.hero_subtitle,true)}{field('SEO title',['seo','title'],config.seo?.title)}{field('SEO description',['seo','description'],config.seo?.description,true)}</div></details>
  <details><summary>{t('languages.navigation')}</summary><div className="translation-panel">{['home','explore','cart','orders','profile'].map(key=><div className="translate-pair" key={key}>{field(`${key} title`,['navigation',key,'title'],key)}{field(`${key} description`,['navigation',key,'description'],'',true)}</div>)}</div></details>
  <details><summary>{t('languages.categories')}</summary><div className="translation-panel">{cats.map(cat=><div className="translate-entity" key={cat.public_id||cat.id}><strong>{cat.name}</strong>{field('Name',['categories',String(cat.public_id||cat.id),'name'],cat.name)}{field('Description',['categories',String(cat.public_id||cat.id),'description'],cat.description,true)}</div>)}{!cats.length&&<p className="muted">No merchant categories are available.</p>}</div></details>
  <details><summary>{t('languages.products')}</summary><div className="translation-panel"><Field label={t('languages.select_product')}><select value={productRef} onChange={e=>setProductRef(e.target.value)}><option value="">—</option>{products.map(p=><option key={p.public_id} value={p.public_id}>{p.name}</option>)}</select></Field>{product?<><div className="translate-entity"><strong>{product.name}</strong>{field('Product title',['products',String(product.public_id),'name'],product.name)}{field('Short description',['products',String(product.public_id),'short_description'],product.short_description,true)}{field('Description',['products',String(product.public_id),'description'],product.description,true)}</div>{(product.modifier_groups||[]).map(group=><div className="translate-entity modifier" key={group.public_id||group.id}><strong>Modifier · {group.name}</strong>{field('Group name',['modifier_groups',String(group.public_id||group.id),'name'],group.name)}{(group.options||[]).map(option=><div className="translate-option" key={option.public_id||option.id}>{field(`Option · ${option.name}`,['modifier_options',String(option.public_id||option.id),'name'],option.name)}</div>)}</div>)}</>:<p className="muted">{t('languages.no_product')}</p>}</div></details>
  <details><summary>{t('languages.home')}</summary><div className="translation-panel">{(config.home?.sections||[]).map(section=><div className="translate-entity" key={section.id}><strong>{section.type} · {section.title||section.id}</strong>{field('Title',['home_sections',String(section.id),'title'],section.title)}{field('Description',['home_sections',String(section.id),'body'],section.body,true)}{field('CTA label',['home_sections',String(section.id),'cta_label'],section.cta_label)}</div>)}</div></details>
 </div>;
}
