import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,DateTime,ErrorBox,Field,PageHeader,Table,Toast,statusTone}from'../components/UI.jsx';
export function MyProfilePage(){
 const{api,session,refreshProfile}=useAuth();const[displayName,setDisplayName]=useState(session?.user?.display_name||''),[sessions,setSessions]=useState([]),[password,setPassword]=useState({current_password:'',new_password:''}),[err,setErr]=useState(null),[toast,setToast]=useState('');
 const loadSessions=async()=>{try{const d=await api.request('/v1/merchant/me/sessions');setSessions(d.data.sessions||[])}catch(e){setErr(e)}};useEffect(()=>{loadSessions()},[]);
 const saveProfile=async()=>{try{await api.request('/v1/merchant/me',{method:'PATCH',body:{display_name:displayName.trim()}});await refreshProfile();setToast('Profile updated')}catch(e){setErr(e)}};
 const changePassword=async e=>{e.preventDefault();try{await api.request('/v1/merchant/me/change-password',{method:'POST',body:password});setPassword({current_password:'',new_password:''});setToast('Password changed. Other sessions were revoked');loadSessions()}catch(e){setErr(e)}};
 const revoke=async id=>{try{await api.request(`/v1/merchant/me/sessions/${encodeURIComponent(id)}`,{method:'DELETE'});setToast('Session revoked');loadSessions()}catch(e){setErr(e)}};
 const revokeOthers=async()=>{try{const d=await api.request('/v1/merchant/me/sessions/revoke-others',{method:'POST',body:{}});setToast(`${d.data.sessions_revoked||0} other session(s) revoked`);loadSessions()}catch(e){setErr(e)}};
 return <><PageHeader title="My profile & security" description="Manage your merchant identity, password and signed-in devices without requiring Platform Admin."/><ErrorBox error={err}/><div className="grid2"><Card title="Profile"><Field label="Email"><input readOnly value={session?.user?.email||''}/></Field><Field label="Display name"><input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></Field><div className="detail-grid"><div><span>Role</span><strong>{session?.user?.role||'Merchant'}</strong></div><div><span>Status</span><Badge tone={statusTone(session?.user?.status)}>{session?.user?.status||'ACTIVE'}</Badge></div></div><button className="primary" onClick={saveProfile}>Save profile</button></Card><Card title="Change password" subtitle="Changing your password revokes every other merchant session."><form onSubmit={changePassword}><Field label="Current password"><input type="password" required value={password.current_password} onChange={e=>setPassword({...password,current_password:e.target.value})}/></Field><Field label="New password" hint="At least 12 characters."><input type="password" required minLength="12" value={password.new_password} onChange={e=>setPassword({...password,new_password:e.target.value})}/></Field><button className="primary">Change password</button></form></Card></div><Card title="Active sessions" subtitle="Review devices signed into your merchant account." ><Table rows={sessions} keyField="id" columns={[{key:'current',label:'Session',render:r=>r.current?<Badge tone="success">CURRENT</Badge>:<Badge>ACTIVE</Badge>},{key:'user_agent',label:'Device / browser',render:r=><span className="truncate">{r.user_agent||'Unknown'}</span>},{key:'request_ip',label:'IP'},{key:'last_seen_at',label:'Last seen',render:r=><DateTime value={r.last_seen_at}/>},{key:'expires_at',label:'Expires',render:r=><DateTime value={r.expires_at}/>},{key:'action',label:'',render:r=>r.current?'—':<button className="danger-mini" onClick={()=>revoke(r.id)}>Revoke</button>}]} /><div className="right"><button className="secondary" onClick={revokeOthers}>Revoke all other sessions</button></div></Card><Toast message={toast} onDone={()=>setToast('')}/></>;
}
