import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{VbenAlert,VbenBadge,VbenButton,VbenCard,VbenDateTime,VbenField,VbenIcon,VbenInput,VbenMetric,VbenModal,VbenMoney,VbenPermissionNote,VbenSelect,VbenSkeleton,VbenTable,VbenTabs,VbenTextarea,VbenToast,vbenStatusTone}from'../components/VbenUI.jsx';

const fresh={code:'',name:'',provider_type:'MANUAL',provider_key:'',status:'ACTIVE',instructions:'',public_config:'{}',sort_order:0};
function parseJson(text,label){try{const value=JSON.parse(text||'{}');if(!value||Array.isArray(value)||typeof value!=='object')throw new Error();return value}catch{const e=new Error(`${label} must be valid JSON object`);e.code='INVALID_JSON';throw e}}
const paymentAttention=s=>['PENDING','PENDING_PAYMENT','FAILED','PAYMENT_FAILED'].includes(String(s||'').toUpperCase());
const refundOpen=s=>['REQUESTED','PROCESSING'].includes(String(s||'').toUpperCase());

export function PaymentsPage(){
 const{api,has}=useAuth();
 const[rows,setRows]=useState([]),[methods,setMethods]=useState([]),[refunds,setRefunds]=useState([]),[err,setErr]=useState(null),[tab,setTab]=useState('activity'),[open,setOpen]=useState(false),[editMethod,setEditMethod]=useState(null),[payment,setPayment]=useState(null),[refund,setRefund]=useState(null),[toast,setToast]=useState(''),[loading,setLoading]=useState(true),[q,setQ]=useState('');
 const[form,setForm]=useState(fresh),[refundRequest,setRefundRequest]=useState(null),[refundReason,setRefundReason]=useState('Customer refund'),[refundFields,setRefundFields]=useState({provider_reference:'',failure_message:''}),[busy,setBusy]=useState('');
 const load=async()=>{setErr(null);setLoading(true);try{const[p,m,r]=await Promise.all([api.request('/v1/merchant/payments',{query:{limit:100}}),api.request('/v1/merchant/payment-methods'),api.request('/v1/merchant/refunds',{query:{limit:100}})]);setRows(p.data.payments||[]);setMethods(m.data.payment_methods||[]);setRefunds(r.data.refunds||[])}catch(e){setErr(e)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const submit=async(e)=>{e.preventDefault();setBusy('method-create');try{await api.request('/v1/merchant/payment-methods',{method:'POST',body:{...form,provider_key:form.provider_key.trim()||undefined,public_config:parseJson(form.public_config,'Public configuration'),sort_order:Number(form.sort_order||0)}});setOpen(false);setForm(fresh);setToast('Payment method created');await load()}catch(e){setErr(e)}finally{setBusy('')}};
 const startEdit=m=>setEditMethod({...m,provider_key:m.provider_key||'',instructions:m.instructions||'',public_config:JSON.stringify(m.public_config||{},null,2),sort_order:Number(m.sort_order||0)});
 const saveMethod=async()=>{setBusy('method-save');try{await api.request(`/v1/merchant/payment-methods/${encodeURIComponent(editMethod.id)}`,{method:'PATCH',body:{name:editMethod.name,provider_key:editMethod.provider_key.trim()||null,status:editMethod.status,instructions:editMethod.instructions||null,public_config:parseJson(editMethod.public_config,'Public configuration'),sort_order:Number(editMethod.sort_order||0)}});setEditMethod(null);setToast('Payment method updated');await load()}catch(e){setErr(e)}finally{setBusy('')}};
 const openPayment=async r=>{setBusy(`payment-${r.id}`);try{const d=await api.request(`/v1/merchant/orders/${encodeURIComponent(r.order_number)}/payment`);setPayment(d.data.payment)}catch(e){setErr(e)}finally{setBusy('')}};
 const openRefundRequest=p=>{setPayment(null);setRefundRequest(p);setRefundReason('Customer refund');setErr(null)};
 const submitRefundRequest=async()=>{if(!refundReason.trim())return;setBusy('request-refund');try{await api.request(`/v1/merchant/orders/${encodeURIComponent(refundRequest.order_number)}/refunds`,{method:'POST',body:{reason:refundReason.trim()}});setRefundRequest(null);setToast('Full remaining refund requested');await load();setTab('refunds')}catch(e){setErr(e)}finally{setBusy('')}};
 const openRefund=r=>{setRefund(r);setRefundFields({provider_reference:r.provider_reference||'',failure_message:r.failure_message||''});setErr(null)};
 const advanceRefund=async(status)=>{if(status==='FAILED'&&!refundFields.failure_message.trim()){setErr(Object.assign(new Error('Failure reason is required when marking a refund failed.'),{code:'REFUND_FAILURE_REASON_REQUIRED'}));return}setBusy(`refund-${status}`);try{const body={status};if(status==='SUCCEEDED')body.provider_reference=refundFields.provider_reference.trim()||null;if(status==='FAILED')body.failure_message=refundFields.failure_message.trim();await api.request(`/v1/merchant/refunds/${encodeURIComponent(refund.id)}`,{method:'PATCH',body});setRefund(null);setToast(`Refund ${status.toLowerCase()}`);await load()}catch(e){setErr(e)}finally{setBusy('')}};
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();if(!x)return tab==='activity'?rows:tab==='refunds'?refunds:methods;const list=tab==='activity'?rows:tab==='refunds'?refunds:methods;return list.filter(r=>Object.values(r||{}).some(v=>typeof v==='string'&&v.toLowerCase().includes(x)))},[q,tab,rows,refunds,methods]);
 const metrics=useMemo(()=>({payments:rows.length,attention:rows.filter(r=>paymentAttention(r.status)).length,refunds:refunds.filter(r=>refundOpen(r.status)).length,methods:methods.filter(m=>m.status==='ACTIVE').length}),[rows,refunds,methods]);
 if(!has('payments.read'))return <VbenPermissionNote permission="payments.read"/>;
 const error=err?<VbenAlert tone="danger" title={err.code||'Payment operation failed'}>{err.message||'The payment operation could not be completed.'}</VbenAlert>:null;
 return <div className="vben-payments-page">
  <header className="vben-payments-head"><div><span className="vben-payments-kicker"><VbenIcon name="payments" size={14}/> Commerce operations</span><h1>Payments & refunds</h1><p>Operate checkout methods, inspect payment attempts and maintain Luke's auditable refund records without crossing the configured provider boundary.</p></div><div className="vben-payments-head-actions"><VbenButton variant="secondary" icon="refresh" onClick={load} loading={loading}>Refresh</VbenButton>{has('payments.manage')&&<VbenButton icon="plus" onClick={()=>setOpen(true)}>Add payment method</VbenButton>}</div></header>
  {error}
  <section className="vben-payments-metrics"><VbenMetric label="Payments loaded" value={metrics.payments} detail="Latest 100 records" icon="payments"/><VbenMetric label="Needs attention" value={metrics.attention} detail="Pending or failed" icon="alert" tone={metrics.attention?'warning':'success'}/><VbenMetric label="Open refunds" value={metrics.refunds} detail="Requested or processing" icon="receipt" tone={metrics.refunds?'warning':'neutral'}/><VbenMetric label="Active methods" value={metrics.methods} detail={`${methods.length} configured`} icon="wallet" tone="success"/></section>
  <VbenCard className="vben-payments-workspace-card"><VbenTabs value={tab} onChange={v=>{setTab(v);setQ('')}} items={[{value:'activity',label:'Payment activity',count:rows.length},{value:'refunds',label:'Refunds',count:refunds.length},{value:'methods',label:'Payment methods',count:methods.length}]}/><div className="vben-payments-toolbar"><VbenInput icon="search" value={q} onChange={e=>setQ(e.target.value)} placeholder={tab==='activity'?'Search order, reference or method':tab==='refunds'?'Search order, customer, reason or reference':'Search method, code or provider'}/><span>{filtered.length} shown</span></div>{loading?<div className="vben-payments-loading"><VbenSkeleton lines={5}/></div>:tab==='activity'?<PaymentActivity rows={filtered} onOpen={openPayment} busy={busy}/>:tab==='refunds'?<RefundTable rows={filtered} onOpen={openRefund}/>:<MethodTable rows={filtered} canManage={has('payments.manage')} onOpen={startEdit}/>}</VbenCard>

  <VbenModal open={open} onClose={()=>!busy&&setOpen(false)} title="New payment method" size="lg" footer={<><VbenButton variant="secondary" disabled={!!busy} onClick={()=>setOpen(false)}>Cancel</VbenButton><VbenButton type="submit" form="payment-form" loading={busy==='method-create'}>Create method</VbenButton></>}><PaymentMethodForm id="payment-form" form={form} setForm={setForm} onSubmit={submit} create/></VbenModal>
  <VbenModal open={!!editMethod} onClose={()=>!busy&&setEditMethod(null)} title="Edit payment method" size="lg" footer={<><VbenButton variant="secondary" disabled={!!busy} onClick={()=>setEditMethod(null)}>Cancel</VbenButton><VbenButton onClick={saveMethod} loading={busy==='method-save'}>Save changes</VbenButton></>}>{editMethod&&<PaymentMethodForm form={editMethod} setForm={setEditMethod}/>}</VbenModal>
  <VbenModal open={!!payment} onClose={()=>setPayment(null)} title={payment?.order_number||'Payment details'} size="xl">{payment&&<PaymentWorkspace payment={payment} canManage={has('payments.manage')} onRefund={()=>openRefundRequest(payment)}/>}</VbenModal>
  <VbenModal open={!!refundRequest} onClose={()=>!busy&&setRefundRequest(null)} title="Request full remaining refund" size="lg" footer={<><VbenButton variant="secondary" disabled={!!busy} onClick={()=>setRefundRequest(null)}>Cancel</VbenButton><VbenButton variant="danger" disabled={!!busy||!refundReason.trim()} loading={busy==='request-refund'} onClick={submitRefundRequest}>Create refund request</VbenButton></>}>{refundRequest&&<><VbenAlert tone="warning" title="Audit-controlled action">This creates a full remaining refund record in Luke for order {refundRequest.order_number}. It does not send money through an external provider.</VbenAlert><div className="vben-payment-summary-grid"><Fact label="Order" value={refundRequest.order_number}/><div><span>Remaining refundable</span><strong><VbenMoney value={Number(refundRequest.amount||0)-Number(refundRequest.refunded_amount||0)} currency={refundRequest.currency}/></strong></div></div><VbenField label="Refund reason" hint="Required for the audit trail."><VbenTextarea value={refundReason} onChange={e=>setRefundReason(e.target.value)} maxLength="500" autoFocus/></VbenField></>}</VbenModal>
  <VbenModal open={!!refund} onClose={()=>!busy&&setRefund(null)} title="Refund control" size="lg" footer={refund&&has('payments.manage')&&!['SUCCEEDED','FAILED','CANCELLED'].includes(refund.status)&&<><VbenButton variant="secondary" disabled={!!busy} onClick={()=>advanceRefund('CANCELLED')}>Cancel refund</VbenButton><VbenButton variant="danger" disabled={!!busy||!refundFields.failure_message.trim()} onClick={()=>advanceRefund('FAILED')}>Mark failed</VbenButton>{refund.status==='REQUESTED'&&<VbenButton variant="secondary" disabled={!!busy} onClick={()=>advanceRefund('PROCESSING')}>Mark processing</VbenButton>}<VbenButton disabled={!!busy} onClick={()=>advanceRefund('SUCCEEDED')}>Mark succeeded</VbenButton></>}>{refund&&<RefundControl refund={refund} fields={refundFields} setFields={setRefundFields} canManage={has('payments.manage')}/>}</VbenModal>
  <VbenToast message={toast} onDone={()=>setToast('')}/>
 </div>;
}

function PaymentActivity({rows,onOpen,busy}){return <VbenTable ariaLabel="Payment activity" rows={rows} keyField="id" emptyTitle="No payment activity" emptyDescription="Payment records will appear here as orders move through checkout." columns={[{key:'order_number',label:'Order',render:r=><button className="vben-payment-link" onClick={()=>onOpen(r)} disabled={busy===`payment-${r.id}`}><strong>{r.order_number}</strong><span>{r.payment_method_name||'Payment'}</span></button>},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status}</VbenBadge>},{key:'amount',label:'Amount',render:r=><strong className="vben-payment-money"><VbenMoney value={r.amount} currency={r.currency}/></strong>},{key:'payment_method_name',label:'Method'},{key:'provider_reference',label:'Reference',render:r=><code className="vben-payment-reference">{r.provider_reference||'—'}</code>},{key:'created_at',label:'Created',render:r=><span className="vben-payment-time"><VbenDateTime value={r.created_at}/></span>}]} />}
function RefundTable({rows,onOpen}){return <><VbenAlert tone="info" title="Provider boundary">Luke records and audits the refund lifecycle here. Marking a refund succeeded does not itself call an external payment provider.</VbenAlert><VbenTable ariaLabel="Refund workflow" rows={rows} keyField="id" emptyTitle="No refunds" emptyDescription="Refund requests will appear here when created from eligible paid orders." columns={[{key:'order_number',label:'Order'},{key:'customer_name',label:'Customer',render:r=>r.customer_name||r.customer_id||'—'},{key:'status',label:'Status',render:r=><button className="vben-refund-link" onClick={()=>onOpen(r)}><VbenBadge tone={vbenStatusTone(r.status)}>{r.status}</VbenBadge></button>},{key:'amount',label:'Amount',render:r=><VbenMoney value={r.amount} currency={r.currency}/>},{key:'reason',label:'Reason',render:r=><span className="vben-payment-truncate">{r.reason||'—'}</span>},{key:'requested_at',label:'Requested',render:r=><span className="vben-payment-time"><VbenDateTime value={r.requested_at}/></span>}]} /></>}
function MethodTable({rows,canManage,onOpen}){return <VbenTable ariaLabel="Payment methods" rows={rows} keyField="id" emptyTitle="No payment methods" emptyDescription="Configure a customer-safe checkout method to make it available to commerce workflows." columns={[{key:'name',label:'Method',render:r=><button className="vben-payment-link" onClick={()=>canManage&&onOpen(r)} disabled={!canManage}><strong>{r.name}</strong><span>{r.code} · {r.provider_type}</span></button>},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status}</VbenBadge>},{key:'provider_key',label:'Provider key',render:r=><code className="vben-payment-reference">{r.provider_key||'—'}</code>},{key:'sort_order',label:'Order'},{key:'instructions',label:'Instructions',render:r=><span className="vben-payment-truncate">{r.instructions||'—'}</span>}]} />}
function PaymentMethodForm({id,form,setForm,onSubmit,create=false}){return <form id={id} onSubmit={onSubmit} className="vben-payment-form"><div className="vben-payment-form-grid">{create?<><VbenField label="Code" required><VbenInput value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></VbenField><VbenField label="Name" required><VbenInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></VbenField><VbenField label="Provider type"><VbenSelect value={form.provider_type} onChange={e=>setForm({...form,provider_type:e.target.value})}><option>MANUAL</option><option>BANK_TRANSFER</option><option>CASH_ON_DELIVERY</option><option>EXTERNAL</option></VbenSelect></VbenField></>:<><VbenField label="Code"><VbenInput readOnly value={form.code}/></VbenField><VbenField label="Provider type"><VbenInput readOnly value={form.provider_type}/></VbenField><VbenField label="Name"><VbenInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></VbenField></>}<VbenField label="Provider key" hint="Public adapter/provider identifier, never a secret key."><VbenInput value={form.provider_key||''} onChange={e=>setForm({...form,provider_key:e.target.value})}/></VbenField><VbenField label="Status"><VbenSelect value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></VbenSelect></VbenField><VbenField label="Sort order"><VbenInput type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></VbenField><VbenField label="Instructions" className="vben-payment-span-2"><VbenTextarea value={form.instructions||''} onChange={e=>setForm({...form,instructions:e.target.value})}/></VbenField><VbenField label="Public configuration (JSON)" hint="Customer-safe values only. Never store provider secrets in public_config." className="vben-payment-span-2"><VbenTextarea className="vben-payment-code" value={form.public_config} onChange={e=>setForm({...form,public_config:e.target.value})}/></VbenField></div></form>}
function PaymentWorkspace({payment,canManage,onRefund}){return <div className="vben-payment-detail"><div className="vben-payment-detail-head"><div><span>Payment snapshot</span><h3>{payment.payment_method_name||'Payment'}</h3><div><VbenBadge tone={vbenStatusTone(payment.status)}>{payment.status}</VbenBadge><span>{payment.provider_type||'—'}</span></div></div><div className="vben-payment-summary-grid"><div><span>Amount</span><strong><VbenMoney value={payment.amount} currency={payment.currency}/></strong></div><Fact label="Reference" value={payment.provider_reference||'—'}/><div><span>Refunded amount</span><strong><VbenMoney value={payment.refunded_amount} currency={payment.currency}/></strong></div></div></div><div className="vben-payment-detail-grid"><VbenCard title="Payment lifecycle" description="Read-only backend payment facts"><div className="vben-payment-facts"><div><span>Paid</span><strong><VbenDateTime value={payment.paid_at}/></strong></div><div><span>Failed</span><strong><VbenDateTime value={payment.failed_at}/></strong></div><Fact label="Failure code" value={payment.failure_code||'—'}/><Fact label="Provider type" value={payment.provider_type||'—'}/></div>{canManage&&['PAID','PARTIALLY_REFUNDED'].includes(payment.status)&&<VbenButton variant="danger" onClick={onRefund}>Request full remaining refund</VbenButton>}</VbenCard><VbenCard title="Attempts" description={`${payment.attempts?.length||0} payment attempt(s)`} className="vben-payment-attempt-card"><VbenTable rows={payment.attempts||[]} keyField="id" ariaLabel="Payment attempts" emptyTitle="No attempts recorded" columns={[{key:'attempt_no',label:'#'},{key:'status',label:'Status',render:r=><VbenBadge tone={vbenStatusTone(r.status)}>{r.status}</VbenBadge>},{key:'provider_reference',label:'Reference',render:r=><code>{r.provider_reference||'—'}</code>},{key:'failure_code',label:'Failure'},{key:'created_at',label:'Created',render:r=><VbenDateTime value={r.created_at}/>}]} /></VbenCard></div></div>}
function RefundControl({refund,fields,setFields,canManage}){const editable=canManage&&!['SUCCEEDED','FAILED','CANCELLED'].includes(refund.status);return <div className="vben-refund-control"><VbenAlert tone="warning" title="Provider boundary">Update this record only after the corresponding provider/operator action. Luke records the result; this control does not execute the external refund.</VbenAlert><div className="vben-payment-summary-grid"><Fact label="Order" value={refund.order_number}/><div><span>Status</span><strong><VbenBadge tone={vbenStatusTone(refund.status)}>{refund.status}</VbenBadge></strong></div><div><span>Amount</span><strong><VbenMoney value={refund.amount} currency={refund.currency}/></strong></div><Fact label="Reason" value={refund.reason||'—'}/></div>{editable&&<div className="vben-payment-form-grid"><VbenField label="Provider refund reference" hint="Optional provider/operator reference after a successful refund."><VbenInput value={fields.provider_reference} onChange={e=>setFields({...fields,provider_reference:e.target.value})}/></VbenField><VbenField label="Failure reason" hint="Required only when marking the refund failed."><VbenTextarea value={fields.failure_message} onChange={e=>setFields({...fields,failure_message:e.target.value})}/></VbenField></div>}<div className="vben-payment-summary-grid"><Fact label="Recorded provider reference" value={refund.provider_reference||'—'}/><Fact label="Recorded failure" value={refund.failure_message||refund.failure_code||'—'}/></div></div>}
function Fact({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
