import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,DateTime,ErrorBox,Field,Modal,Money,PageHeader,Table,Tabs,Toast,statusTone,PermissionNote}from'../components/UI.jsx';

export function PaymentsPage(){
 const{api,has}=useAuth();const[rows,setRows]=useState([]),[methods,setMethods]=useState([]),[err,setErr]=useState(null),[tab,setTab]=useState('activity'),[open,setOpen]=useState(false),[editMethod,setEditMethod]=useState(null),[payment,setPayment]=useState(null),[toast,setToast]=useState('');
 const[form,setForm]=useState({code:'',name:'',provider_type:'MANUAL',status:'ACTIVE',instructions:''});
 const load=async()=>{setErr(null);try{const[p,m]=await Promise.all([api.request('/v1/merchant/payments',{query:{limit:100}}),api.request('/v1/merchant/payment-methods')]);setRows(p.data.payments);setMethods(m.data.payment_methods)}catch(e){setErr(e)}};useEffect(()=>{load()},[]);
 const submit=async(e)=>{e.preventDefault();try{await api.request('/v1/merchant/payment-methods',{method:'POST',body:form});setOpen(false);setForm({code:'',name:'',provider_type:'MANUAL',status:'ACTIVE',instructions:''});setToast('Payment method created');load()}catch(e){setErr(e)}};
 const saveMethod=async()=>{try{await api.request(`/v1/merchant/payment-methods/${encodeURIComponent(editMethod.id)}`,{method:'PATCH',body:{name:editMethod.name,status:editMethod.status,instructions:editMethod.instructions||null,sort_order:Number(editMethod.sort_order||0)}});setEditMethod(null);setToast('Payment method updated');load()}catch(e){setErr(e)}};
 const openPayment=async(r)=>{try{const d=await api.request(`/v1/merchant/orders/${encodeURIComponent(r.order_number)}/payment`);setPayment(d.data.payment)}catch(e){setErr(e)}};
 if(!has('payments.read'))return <PermissionNote permission="payments.read"/>;
 return <><PageHeader title="Payments" description="Manage checkout payment methods and inspect payment attempts, references, failures, and settlement state." actions={has('payments.manage')&&<button className="primary" onClick={()=>setOpen(true)}>Add payment method</button>}/><ErrorBox error={err}/><Tabs value={tab} onChange={setTab} items={[{value:'activity',label:'Payment activity',count:rows.length},{value:'methods',label:'Payment methods',count:methods.length}]}/>{tab==='activity'&&<Card title="Payment activity"><Table rows={rows} keyField="id" columns={[{key:'order_number',label:'Order',render:r=><button className="link-btn" onClick={()=>openPayment(r)}>{r.order_number}</button>},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'amount',label:'Amount',render:r=><Money value={r.amount} currency={r.currency}/>},{key:'payment_method_name',label:'Method'},{key:'provider_reference',label:'Reference',render:r=><code>{r.provider_reference||'—'}</code>},{key:'created_at',label:'Created',render:r=><DateTime value={r.created_at}/>}]} /></Card>}{tab==='methods'&&<Card title="Payment methods"><Table rows={methods} keyField="id" columns={[{key:'name',label:'Method',render:r=><button className="link-btn" onClick={()=>has('payments.manage')&&setEditMethod({...r})}><strong>{r.name}</strong><small className="block">{r.code} · {r.provider_type}</small></button>},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'provider_key',label:'Provider key'},{key:'instructions',label:'Instructions',render:r=><span className="truncate">{r.instructions||'—'}</span>}]} /></Card>}
 <Modal open={open} onClose={()=>setOpen(false)} title="New payment method" footer={<><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" form="payment-form">Create</button></>}><form id="payment-form" onSubmit={submit}><Field label="Code"><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></Field><Field label="Name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="Provider type"><select value={form.provider_type} onChange={e=>setForm({...form,provider_type:e.target.value})}><option>MANUAL</option><option>BANK_TRANSFER</option><option>CASH_ON_DELIVERY</option><option>EXTERNAL</option></select></Field><Field label="Instructions"><textarea value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></Field></form></Modal>
 <Modal open={!!editMethod} onClose={()=>setEditMethod(null)} title="Edit payment method" footer={<><button className="secondary" onClick={()=>setEditMethod(null)}>Cancel</button><button className="primary" onClick={saveMethod}>Save</button></>}>{editMethod&&<><div className="detail-grid"><div><span>Code</span><strong>{editMethod.code}</strong></div><div><span>Provider</span><strong>{editMethod.provider_type}</strong></div></div><Field label="Name"><input value={editMethod.name} onChange={e=>setEditMethod({...editMethod,name:e.target.value})}/></Field><Field label="Status"><select value={editMethod.status} onChange={e=>setEditMethod({...editMethod,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></Field><Field label="Instructions"><textarea value={editMethod.instructions||''} onChange={e=>setEditMethod({...editMethod,instructions:e.target.value})}/></Field></>}</Modal>
 <Modal open={!!payment} onClose={()=>setPayment(null)} title={payment?.order_number||'Payment details'} size="lg">{payment&&<><div className="workspace-summary"><div><Badge tone={statusTone(payment.status)}>{payment.status}</Badge><strong>{payment.payment_method_name}</strong><span>{payment.provider_type}</span></div><div><span>Amount</span><strong><Money value={payment.amount} currency={payment.currency}/></strong></div><div><span>Reference</span><strong>{payment.provider_reference||'—'}</strong></div></div><Card title="Payment lifecycle"><div className="detail-grid"><div><span>Paid</span><strong><DateTime value={payment.paid_at}/></strong></div><div><span>Failed</span><strong><DateTime value={payment.failed_at}/></strong></div><div><span>Failure code</span><strong>{payment.failure_code||'—'}</strong></div><div><span>Refunded amount</span><strong><Money value={payment.refunded_amount} currency={payment.currency}/></strong></div></div></Card><Card title="Attempts"><Table rows={payment.attempts||[]} keyField="id" columns={[{key:'attempt_no',label:'#'},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'provider_reference',label:'Reference'},{key:'failure_code',label:'Failure'},{key:'created_at',label:'Created',render:r=><DateTime value={r.created_at}/>}]} /></Card></>}</Modal><Toast message={toast} onDone={()=>setToast('')}/></>;
}
