import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Card,ErrorBox,Field,PageHeader,Tabs,Toast,PermissionNote}from'../components/UI.jsx';
export function SettingsPage(){
 const{api,has}=useAuth();const[tenant,setTenant]=useState(null),[tab,setTab]=useState('regional'),[regional,setRegional]=useState({currency:'USD',locale:'en',timezone:'UTC'}),[branding,setBranding]=useState({}),[modules,setModules]=useState({}),[support,setSupport]=useState({enabled:false,provider:'LUKE_CS',label:'Customer Support',placement:{}}),[identity,setIdentity]=useState({id_prefix:'CUS',auth_config:{email_password:true,google:false,telegram:false,phone:false,phone_countries:['KH','IN','MM','ID']}}),[authRuntime,setAuthRuntime]=useState(null),[err,setErr]=useState(null),[toast,setToast]=useState('');
 const load=async()=>{setErr(null);try{const[d,a]=await Promise.all([api.request('/v1/merchant/tenant'),api.request('/v1/merchant/customer-auth/options')]);const t=d.data.tenant;setTenant(t);setRegional({currency:t.currency,locale:t.locale,timezone:t.timezone});setBranding(t.branding||{});setModules(t.modules||{});setSupport(t.customer_service||{enabled:false,provider:'LUKE_CS',label:'Customer Support',placement:{}});setIdentity({id_prefix:t.customer_id_prefix||a.data.auth?.id_prefix||'CUS',auth_config:{email_password:t.customer_auth?.email_password!==false,google:Boolean(t.customer_auth?.google),telegram:Boolean(t.customer_auth?.telegram),phone:Boolean(t.customer_auth?.phone),phone_countries:t.customer_auth?.phone_countries||['KH','IN','MM','ID']}});setAuthRuntime(a.data)}catch(e){setErr(e)}};useEffect(()=>{load()},[]);
 const save=async body=>{try{await api.request('/v1/merchant/tenant/settings',{method:'PATCH',body});setToast('Settings saved');load()}catch(e){setErr(e)}};
 if(!has('tenant.settings.read'))return <PermissionNote permission="tenant.settings.read"/>;
 return <><PageHeader title="Store settings" description="Human-readable tenant, regional, feature and support controls. Advanced storefront design belongs in Customer Experience."/><ErrorBox error={err}/><div className="settings-identity"><div><span>Tenant</span><strong>{tenant?.name||'Loading…'}</strong></div><div><span>Slug</span><strong>{tenant?.slug||'—'}</strong></div><div><span>Status</span><strong>{tenant?.status||'—'}</strong></div><div><span>Tenant ID</span><code>{tenant?.public_id||'—'}</code></div></div><Tabs value={tab} onChange={setTab} items={[{value:'regional',label:'Regional'},{value:'identity',label:'Customer identity & login'},{value:'branding',label:'Branding identity'},{value:'modules',label:'Modules'},{value:'customer_service',label:'Customer service'}]}/>
 {tab==='regional'&&<Card title="Regional settings"><form onSubmit={e=>{e.preventDefault();save(regional)}} className="form-grid"><Field label="Currency"><input maxLength="3" value={regional.currency} onChange={e=>setRegional({...regional,currency:e.target.value.toUpperCase()})}/></Field><Field label="Locale"><input value={regional.locale} onChange={e=>setRegional({...regional,locale:e.target.value})}/></Field><Field label="Timezone" hint="Used by promotion scheduling and merchant date/time displays."><input value={regional.timezone} onChange={e=>setRegional({...regional,timezone:e.target.value})} placeholder="Asia/Singapore"/></Field>{has('tenant.settings.write')&&<div className="form-actions"><button className="primary">Save regional settings</button></div>}</form></Card>}
 {tab==='identity'&&<Card title="Customer identity & login" subtitle="Choose the readable customer ID prefix and which production login providers customers may use."><div className="identity-settings-grid"><div><Field label="Customer ID prefix" hint="2–6 uppercase letters. Existing member IDs never change when you change the prefix."><input maxLength="6" value={identity.id_prefix} onChange={e=>setIdentity({...identity,id_prefix:e.target.value.toUpperCase().replace(/[^A-Z]/g,'')})}/></Field><div className="customer-id-preview"><span>Next customer ID preview</span><strong>{authRuntime?.next_customer_code||`${identity.id_prefix||'CUS'}0000001`}</strong><small>Internal UUIDs remain unchanged and private.</small></div></div><div><h3>Login methods</h3><div className="auth-provider-grid">{[['email_password','Email & password','Built in',true],['google','Google / Gmail','Google client ID',authRuntime?.auth?.methods?.google?.ready],['telegram','Telegram','Telegram bot',authRuntime?.auth?.methods?.telegram?.ready],['phone','Phone OTP','SMS/OTP webhook',authRuntime?.auth?.methods?.phone?.ready]].map(([key,label,need,ready])=><label className={`auth-provider-card ${ready?'ready':'not-ready'}`} key={key}><input type="checkbox" checked={Boolean(identity.auth_config[key])} onChange={e=>setIdentity({...identity,auth_config:{...identity.auth_config,[key]:e.target.checked}})}/><div><strong>{label}</strong><span>{ready?'Provider ready':key==='email_password'?'Built in':`Needs ${need} configuration`}</span></div><b>{ready?'READY':'SETUP'}</b></label>)}</div><p className="muted provider-safety-note">Enabling an external method does not bypass provider setup. Customer Web only exposes methods that Backend confirms are both enabled and production-ready.</p></div></div>{has('tenant.settings.write')&&<button className="primary" onClick={()=>save({customer_identity:identity})}>Save customer identity settings</button>}</Card>}
 {tab==='branding'&&<Card title="Tenant identity" subtitle="Basic platform identity. Storefront theme, templates and typography are managed in Customer Experience."><div className="form-grid"><Field label="Store name"><input value={branding.store_name||''} onChange={e=>setBranding({...branding,store_name:e.target.value})}/></Field><Field label="Logo URL"><input value={branding.logo_url||''} onChange={e=>setBranding({...branding,logo_url:e.target.value})}/></Field><Field label="Legacy accent"><input type="color" value={branding.accent||'#166534'} onChange={e=>setBranding({...branding,accent:e.target.value})}/></Field></div>{has('tenant.settings.write')&&<button className="primary" onClick={()=>save({branding})}>Save identity</button>}</Card>}
 {tab==='modules'&&<Card title="Enabled modules" subtitle="Platform plan/owner controls can still limit what a tenant is allowed to use."><div className="settings-toggle-grid">{Object.entries(modules).map(([k,v])=><label key={k} className="feature-toggle"><input type="checkbox" checked={Boolean(v)} onChange={e=>setModules({...modules,[k]:e.target.checked})}/><div><strong>{k.replace(/_/g,' ')}</strong><span>{v?'Enabled':'Disabled'}</span></div></label>)}</div>{has('tenant.settings.write')&&<button className="primary" onClick={()=>save({modules})}>Save modules</button>}</Card>}
 {tab==='customer_service'&&<Card title="Customer service" subtitle="Choose where Luke CS appears without editing JSON."><div className="form-grid"><Field label="Enabled"><label className="switch-line"><input type="checkbox" checked={Boolean(support.enabled)} onChange={e=>setSupport({...support,enabled:e.target.checked})}/>Customer support enabled</label></Field><Field label="Provider"><input value={support.provider||'LUKE_CS'} onChange={e=>setSupport({...support,provider:e.target.value})}/></Field><Field label="Button label"><input value={support.label||''} onChange={e=>setSupport({...support,label:e.target.value})}/></Field></div><h3>Placements</h3><div className="settings-toggle-grid">{['floating','home','profile','order_detail','product_detail','checkout'].map(k=><label key={k} className="feature-toggle"><input type="checkbox" checked={Boolean(support.placement?.[k])} onChange={e=>setSupport({...support,placement:{...(support.placement||{}),[k]:e.target.checked}})}/><div><strong>{k.replace(/_/g,' ')}</strong><span>{support.placement?.[k]?'Visible':'Hidden'}</span></div></label>)}</div>{has('tenant.settings.write')&&<button className="primary" onClick={()=>save({customer_service:support})}>Save customer service</button>}</Card>}
 <Toast message={toast} onDone={()=>setToast('')}/></>;
}
