import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,ErrorBox,Field,Modal,PageHeader,Table,Toast,statusTone,PermissionNote}from'../components/UI.jsx';
const empty={name:'',slug:'',is_primary:false,template_key:'MODERN_COMMERCE'};
export function StoresPage(){
 const{api,has,session,updateStore}=useAuth();const[rows,setRows]=useState([]),[templates,setTemplates]=useState([]),[err,setErr]=useState(null),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[form,setForm]=useState(empty),[toast,setToast]=useState('');
 const load=async()=>{setErr(null);try{const[d,c]=await Promise.all([api.request('/v1/merchant/stores'),api.request('/v1/merchant/customer-experience/catalog')]);setRows(d.data.stores||[]);setTemplates(c.data.templates||[]);if(c.data.templates?.length&&!c.data.templates.some(t=>t.key===form.template_key))setForm(x=>({...x,template_key:c.data.templates[0].key}))}catch(e){setErr(e)}};useEffect(()=>{load()},[]);
 const create=async e=>{e.preventDefault();try{await api.request('/v1/merchant/stores',{method:'POST',body:{...form,name:form.name.trim(),slug:form.slug.trim().toLowerCase()}});setOpen(false);setForm(empty);setToast('Store created with inventory, commerce defaults and Store Designer draft');await load()}catch(e){setErr(e)}};
 const save=async()=>{try{const body={name:edit.name.trim(),slug:edit.slug.trim().toLowerCase(),status:edit.status,is_primary:Boolean(edit.is_primary)};await api.request(`/v1/merchant/stores/${encodeURIComponent(edit.id)}`,{method:'PATCH',body});if(session?.storeId===edit.id&&body.status!=='ACTIVE')updateStore('');setEdit(null);setToast('Store updated');await load()}catch(e){setErr(e)}};
 if(!has('stores.read'))return <PermissionNote permission="stores.read"/>;
 return <><PageHeader title="Stores" description="Manage each storefront independently. Creating a store provisions its inventory location, checkout defaults and a safe Store Designer draft." actions={has('stores.manage')&&<button className="primary" onClick={()=>setOpen(true)}>+ New store</button>}/><ErrorBox error={err}/><Card title="Tenant stores" subtitle="The primary store is used when no explicit store context is selected."><Table rows={rows} keyField="id" columns={[{key:'name',label:'Store',render:r=><button className="link-btn" onClick={()=>has('stores.manage')&&setEdit({...r})}><strong>{r.name}</strong><small className="block">/{r.slug}</small></button>},{key:'status',label:'Status',render:r=><Badge tone={statusTone(r.status)}>{r.status}</Badge>},{key:'is_primary',label:'Primary',render:r=>r.is_primary?<Badge tone="success">PRIMARY</Badge>:'—'},{key:'products',label:'Products'},{key:'orders',label:'Orders'},{key:'id',label:'Context',render:r=><button className="secondary small" onClick={()=>updateStore(r.is_primary?'':r.id)}>{(session?.storeId||'')===r.id?'Selected':r.is_primary&&!session?.storeId?'Selected':'Use store'}</button>}]} /></Card>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create store" footer={<><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" form="store-create">Create store</button></>}><form id="store-create" onSubmit={create}><Field label="Store name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Store slug" hint="Used in the customer storefront route."><input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase()})} placeholder="orchard-store"/></Field><Field label="Starting template"><select value={form.template_key} onChange={e=>setForm({...form,template_key:e.target.value})}>{templates.map(t=><option key={t.key} value={t.key}>{t.name} · {t.business_type}</option>)}</select></Field><label className="switch-line"><input type="checkbox" checked={form.is_primary} onChange={e=>setForm({...form,is_primary:e.target.checked})}/>Make this the primary store</label></form></Modal>
 <Modal open={!!edit} onClose={()=>setEdit(null)} title="Manage store" footer={<><button className="secondary" onClick={()=>setEdit(null)}>Cancel</button><button className="primary" onClick={save}>Save store</button></>}>{edit&&<><Field label="Store name"><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label="Store slug"><input value={edit.slug} onChange={e=>setEdit({...edit,slug:e.target.value.toLowerCase()})}/></Field><Field label="Status"><select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></Field><label className="switch-line"><input type="checkbox" checked={Boolean(edit.is_primary)} onChange={e=>setEdit({...edit,is_primary:e.target.checked})}/>Primary store</label>{edit.is_primary&&<p className="muted">A primary store must stay active. To move the primary role, edit another active store and mark it primary.</p>}</>}</Modal><Toast message={toast} onDone={()=>setToast('')}/></>;
}
