import React from'react';
import{Field}from'./UI.jsx';

export const cartA4Defaults={layout:'standard',item_style:'cards',summary_style:'sticky',empty_style:'standard',show_continue_shopping:true,show_item_count:true,show_fulfillment:true,show_modifiers:true,show_delivery_hint:true,show_assurance:true};
export const checkoutA4Defaults={layout:'standard',summary_style:'sticky',section_style:'cards',saved_address_style:'cards',show_section_descriptions:true,show_promotion_code:true,show_order_note:true,show_support:true,show_trust:true};
const cartLayouts=[['standard','Standard','Current balanced Cart presentation'],['compact','Compact','Tighter spacing for denser stores'],['spacious','Spacious','More breathing room around Cart content']];
const cartItems=[['cards','Cards','Current product-card treatment'],['rows','Rows','Reduced media and tighter item rows'],['minimal','Minimal','Low-chrome cart item presentation']];
const summaryStyles=[['sticky','Sticky','Keep summary available on wide screens'],['standard','Standard','Normal sidebar without sticky behavior'],['inline','Inline','Place summary in the main document flow']];
const checkoutLayouts=[['standard','Standard','Current two-column checkout'],['focused','Focused','Narrower checkout with reduced visual width'],['compact','Compact','Denser checkout spacing']];
const sectionStyles=[['cards','Cards','Current filled checkout cards'],['compact','Compact','Reduced section padding'],['outlined','Outlined','Lower-chrome outlined sections']];

function ChoiceGrid({value,options,onChange,kind}){return <div className={`a4-choice-grid ${kind||''}`}>{options.map(([key,label,description])=><button type="button" key={key} className={value===key?'selected':''} onClick={()=>onChange(key)}><span className={`a4-choice-preview ${kind||''} ${key}`} aria-hidden="true"><i/><i/><i/></span><strong>{label}</strong><small>{description}</small></button>)}</div>}
function Toggle({checked,onChange,title,body,disabled=false}){return <label className={`designer-check ${disabled?'is-disabled':''}`}><input type="checkbox" disabled={disabled} checked={checked} onChange={e=>onChange(e.target.checked)}/><span><strong>{title}</strong><small>{body}</small></span></label>}
function Boundary({children}){return <section className="a4-boundary"><strong>Commerce boundary</strong><p>{children}</p></section>}
function PreviewNotice({page}){return <div className="a4-preview-notice"><i/><span><strong>Real {page} preview</strong><small>Store Designer uses the actual Customer Web route and customer session. No fake cart, products, payment methods or checkout state are generated.</small></span></div>}

export function CartBuilderA4({draft,mutate}){
 const source=draft.cart&&typeof draft.cart==='object'?draft.cart:{};const cart={...cartA4Defaults,...source};
 const patch=values=>mutate(x=>{x.cart={...cartA4Defaults,...(x.cart||{}),...values}});
 return <div className="cart-checkout-builder-a4"><PreviewNotice page="Cart"/>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Cart layout</strong><span>Change spacing and page composition without changing cart data.</span></div><b>A4</b></div><ChoiceGrid value={cart.layout} options={cartLayouts} onChange={layout=>patch({layout})} kind="layout"/></section>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Cart items</strong><span>Choose how real cart lines are presented.</span></div></div><ChoiceGrid value={cart.item_style} options={cartItems} onChange={item_style=>patch({item_style})} kind="items"/></section>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Order summary</strong><span>The existing server totals remain authoritative in every style.</span></div></div><ChoiceGrid value={cart.summary_style} options={summaryStyles} onChange={summary_style=>patch({summary_style})} kind="summary"/><Field label="Empty cart style"><select value={cart.empty_style} onChange={e=>patch({empty_style:e.target.value})}><option value="standard">Standard message</option><option value="minimal">Minimal message</option></select></Field></section>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Visible information</strong><span>These options hide presentation only. Cart operations and totals do not change.</span></div></div><div className="a4-toggle-stack"><Toggle checked={cart.show_continue_shopping!==false} onChange={v=>patch({show_continue_shopping:v})} title="Continue Shopping" body="Show the link back to product discovery."/><Toggle checked={cart.show_item_count!==false} onChange={v=>patch({show_item_count:v})} title="Cart item count" body="Show the loaded quantity count in the Cart header."/><Toggle checked={cart.show_fulfillment!==false} onChange={v=>patch({show_fulfillment:v})} title="Fulfillment label" body="Show the existing product fulfillment mode."/><Toggle checked={cart.show_modifiers!==false} onChange={v=>patch({show_modifiers:v})} title="Modifier summary" body="Show selected real product modifiers when present."/><Toggle checked={cart.show_delivery_hint!==false} onChange={v=>patch({show_delivery_hint:v})} title="Delivery calculation hint" body="Show that delivery is calculated at Checkout."/><Toggle checked={cart.show_assurance!==false} onChange={v=>patch({show_assurance:v})} title="Checkout assurance" body="Show the server-confirmed totals explanation under the CTA."/></div></section>
  <Boundary>Prices, quantities, stock, cart totals, item removal and checkout navigation stay on the existing commerce contracts. Store Designer cannot override them.</Boundary>
 </div>;
}

export function CheckoutBuilderA4({draft,mutate}){
 const source=draft.checkout&&typeof draft.checkout==='object'?draft.checkout:{};const checkout={...checkoutA4Defaults,...source};
 const patch=values=>mutate(x=>{x.checkout={...checkoutA4Defaults,...(x.checkout||{}),...values}});
 return <div className="cart-checkout-builder-a4"><PreviewNotice page="Checkout"/>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Checkout layout</strong><span>Control density without changing the order-submission flow.</span></div><b>A4</b></div><ChoiceGrid value={checkout.layout} options={checkoutLayouts} onChange={layout=>patch({layout})} kind="layout"/></section>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Checkout sections</strong><span>Required address, delivery and payment steps remain present when applicable.</span></div></div><ChoiceGrid value={checkout.section_style} options={sectionStyles} onChange={section_style=>patch({section_style})} kind="sections"/><Field label="Saved address style"><select value={checkout.saved_address_style} onChange={e=>patch({saved_address_style:e.target.value})}><option value="cards">Address cards</option><option value="compact">Compact addresses</option></select></Field></section>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Order summary</strong><span>Subtotal and final order creation remain server-authoritative.</span></div></div><ChoiceGrid value={checkout.summary_style} options={summaryStyles} onChange={summary_style=>patch({summary_style})} kind="summary"/></section>
  <section className="a4-section"><div className="a4-section-head"><div><strong>Optional presentation</strong><span>Hide optional shopper assistance without removing required Checkout controls.</span></div></div><div className="a4-toggle-stack"><Toggle checked={checkout.show_section_descriptions!==false} onChange={v=>patch({show_section_descriptions:v})} title="Section descriptions" body="Show helper copy under Delivery Address, Delivery Method and Payment."/><Toggle checked={checkout.show_promotion_code!==false} onChange={v=>patch({show_promotion_code:v})} title="Promotion code" body="Show the existing optional promotion-code input."/><Toggle checked={checkout.show_order_note!==false} onChange={v=>patch({show_order_note:v})} title="Customer order note" body="Show the existing optional order-note input."/><Toggle checked={checkout.show_support!==false} onChange={v=>patch({show_support:v})} title="Checkout support launcher" body="Show support only when the existing Customer Support feature is also available."/><Toggle checked={checkout.show_trust!==false} onChange={v=>patch({show_trust:v})} title="Server-confirmed trust message" body="Show the existing explanation that fees and discounts are validated by the server."/></div></section>
  <section className="a4-required"><strong>Required Checkout flow is locked</strong><div><span>Delivery address</span><span>Delivery method</span><span>Payment method</span><span>Place order</span></div><small>Store Designer cannot disable required operational steps.</small></section>
  <Boundary>Payment methods, delivery methods, address policy, location capture, discounts, totals, the checkout endpoint and idempotency remain outside Store Designer.</Boundary>
 </div>;
}
