import React,{useState}from'react';

const money=(value,currency='USD')=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(value||0))}catch{return`${currency} ${Number(value||0).toFixed(2)}`}};
const human=value=>String(value||'').replaceAll('_',' ').toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase());

export function CodReconciliationPanel({api,has,collection,onReconciled}){
 const[note,setNote]=useState(''),[armed,setArmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(null);
 if(!collection)return null;
 const id=collection.public_id||collection.id,status=String(collection.status||''),canReconcile=has('delivery.manage')&&has('payments.manage');
 const amount=collection.collected_amount??collection.expected_amount??0,currency=collection.currency||'USD';
 if(status==='RECONCILED')return <div className="cod-reconcile-panel is-complete" data-testid="owner-cod-reconciliation"><div><span>OWNER RECONCILIATION</span><strong>Reconciled · payment confirmed</strong><small>{collection.reconciled_at?new Date(collection.reconciled_at).toLocaleString():'Final reconciliation recorded'}</small></div><b>{money(amount,currency)}</b></div>;
 if(status!=='REMITTED')return <div className="cod-reconcile-panel is-waiting" data-testid="owner-cod-reconciliation"><div><span>OWNER RECONCILIATION</span><strong>Waiting for Cashier custody</strong><small>Driver cash must be received by the store before final payment reconciliation.</small></div><b>{human(status)}</b></div>;
 if(!canReconcile)return <div className="cod-reconcile-panel is-locked" data-testid="owner-cod-reconciliation"><div><span>OWNER RECONCILIATION</span><strong>Manager authorization required</strong><small>Final COD reconciliation requires both Delivery management and Payments management authority.</small></div><b>{money(amount,currency)}</b></div>;
 const reconcile=async()=>{if(!armed||busy)return;setBusy(true);setError(null);try{await api.request(`/v1/merchant/delivery/cod/${encodeURIComponent(id)}/reconcile`,{method:'POST',body:{note:note.trim()||undefined}});setArmed(false);setNote('');await onReconciled?.()}catch(e){setError(e)}finally{setBusy(false)}};
 return <div className="cod-reconcile-panel is-ready" data-testid="owner-cod-reconciliation"><div className="cod-reconcile-heading"><div><span>OWNER RECONCILIATION</span><strong>{money(amount,currency)} ready for final settlement</strong><small>The Backend rechecks collected cash against the server-authoritative expected payment amount.</small></div><b>REMITTED</b></div>{error&&<div className="cod-reconcile-error"><strong>{error.code||'Reconciliation failed'}</strong><span>{error.message||'The COD record was not reconciled.'}</span></div>}{!armed?<div className="cod-reconcile-actions"><p>This action finalizes cash custody and confirms the order payment. Cashier accounts cannot perform it.</p><button className="primary" onClick={()=>setArmed(true)}>Review reconciliation</button></div>:<div className="cod-reconcile-confirm"><label>Audit note<textarea value={note} maxLength="1000" onChange={e=>setNote(e.target.value)} placeholder="Optional reconciliation note"/></label><div className="cod-reconcile-warning"><strong>Confirm final settlement</strong><span>Expected: {money(collection.expected_amount,currency)} · Collected: {money(collection.collected_amount,currency)}</span></div><div className="cod-reconcile-buttons"><button className="secondary" disabled={busy} onClick={()=>setArmed(false)}>Cancel</button><button className="primary" disabled={busy} onClick={reconcile}>{busy?'Reconciling…':'Reconcile COD & confirm payment'}</button></div></div>}</div>;
}
