import React from'react';
import{Field}from'./UI.jsx';

export const exploreDefaults={hero_style:'standard',show_result_count:true,show_category_description:false,categories:{enabled:true,style:'rail',show_images:false},page_size:24,load_more_style:'button'};
const heroStyles=[['standard','Standard','Full discovery heading with helper copy'],['compact','Compact','Shorter header for product-first stores'],['minimal','Minimal','Clean heading with the least visual weight']];
const categoryStyles=[['rail','Horizontal rail','Scrollable category controls'],['chips','Compact chips','Wrapped pill-style category controls'],['cards','Category cards','Visual category discovery cards']];
const pageSizes=[12,24,36,48];

export function ExploreBuilderA3({draft,mutate}){
 const source=draft.explore&&typeof draft.explore==='object'?draft.explore:{};
 const explore={...exploreDefaults,...source,categories:{...exploreDefaults.categories,...(source.categories||{})}};
 const patch=values=>mutate(x=>{x.explore={...exploreDefaults,...(x.explore||{}),...values,categories:{...exploreDefaults.categories,...(x.explore?.categories||{}),...(values.categories||{})}}});
 const patchCategories=values=>patch({categories:{...explore.categories,...values}});
 return <div className="explore-builder-a3">
  <section className="explore-a3-section"><div className="explore-a3-head"><div><strong>Explore page</strong><span>Control catalog presentation while products, pricing and availability remain server-authoritative.</span></div><b>Schema v4</b></div><div className="explore-a3-safety"><i/>Presentation only · no sorting, price or fulfillment rules</div></section>
  <section className="explore-a3-section"><div className="explore-a3-head"><div><strong>Discovery header</strong><span>Choose the visual weight of the Explore page heading.</span></div></div><div className="explore-a3-choice-grid">{heroStyles.map(([value,label,description])=><button type="button" key={value} className={explore.hero_style===value?'selected':''} onClick={()=>patch({hero_style:value})}><span className={`explore-a3-hero-preview ${value}`} aria-hidden="true"><i/><i/></span><strong>{label}</strong><small>{description}</small></button>)}</div><label className="designer-check"><input type="checkbox" checked={explore.show_result_count!==false} onChange={e=>patch({show_result_count:e.target.checked})}/><span><strong>Show result count</strong><small>Displays the number of currently loaded products.</small></span></label><label className="designer-check"><input type="checkbox" checked={explore.show_category_description===true} onChange={e=>patch({show_category_description:e.target.checked})}/><span><strong>Show active category description</strong><small>Uses the real merchant category description when one exists.</small></span></label></section>
  <section className="explore-a3-section"><div className="explore-a3-head"><div><strong>Category discovery</strong><span>Configure how real published categories are presented to shoppers.</span></div></div><label className="designer-check"><input type="checkbox" checked={explore.categories.enabled!==false} onChange={e=>patchCategories({enabled:e.target.checked})}/><span><strong>Show category discovery</strong><small>Hiding this affects presentation only; category URLs and catalog data remain unchanged.</small></span></label><Field label="Category style"><select disabled={explore.categories.enabled===false} value={explore.categories.style} onChange={e=>patchCategories({style:e.target.value})}>{categoryStyles.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><div className={`explore-a3-category-preview ${explore.categories.style}`} aria-hidden="true"><i/><i/><i/><i/></div><label className={`designer-check ${explore.categories.style!=='cards'||explore.categories.enabled===false?'is-disabled':''}`}><input type="checkbox" disabled={explore.categories.style!=='cards'||explore.categories.enabled===false} checked={explore.categories.show_images===true} onChange={e=>patchCategories({show_images:e.target.checked})}/><span><strong>Show category images</strong><small>Available only for Category cards and uses existing public category media.</small></span></label></section>
  <section className="explore-a3-section"><div className="explore-a3-head"><div><strong>Product discovery flow</strong><span>Bound the number of real products requested per page without changing catalog ordering.</span></div></div><Field label="Products per request"><select value={explore.page_size} onChange={e=>patch({page_size:Number(e.target.value)})}>{pageSizes.map(value=><option key={value} value={value}>{value} products</option>)}</select></Field><Field label="Load more style"><select value={explore.load_more_style} onChange={e=>patch({load_more_style:e.target.value})}><option value="button">Standard button</option><option value="quiet">Quiet text action</option></select></Field><div className="explore-a3-flow-preview" aria-hidden="true"><div><i/><i/><i/><i/></div><span className={explore.load_more_style}>{explore.load_more_style==='quiet'?'Load more →':'Load more'}</span></div></section>
  <section className="explore-a3-section explore-a3-boundary"><strong>Catalog boundary</strong><p>Explore Builder does not create sorting, price filters, product-type filters, custom queries, inventory rules, payment controls or delivery promises. Those require separate authoritative commerce contracts.</p></section>
 </div>;
}
