import React from'react';
import{Field}from'./UI.jsx';

export const footerDefaults={enabled:false,layout:'columns',tagline:'',show_brand:true,show_copyright:true,copyright_text:'',groups:[],social_links:[]};
const destinations=[['home','Home'],['explore','Explore'],['cart','Cart'],['orders','Orders'],['profile','Profile'],['signin','Sign in']];
const networks=[['facebook','Facebook'],['instagram','Instagram'],['telegram','Telegram'],['tiktok','TikTok'],['youtube','YouTube'],['x','X']];
const freshId=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;

export function FooterBuilderA2({draft,mutate}){
 const footer={...footerDefaults,...(draft.footer||{}),groups:Array.isArray(draft.footer?.groups)?draft.footer.groups:[],social_links:Array.isArray(draft.footer?.social_links)?draft.footer.social_links:[]};
 const patch=values=>mutate(x=>{x.footer={...footerDefaults,...(x.footer||{}),...values}});
 const addGroup=()=>{if(footer.groups.length>=4)return;mutate(x=>{const current=Array.isArray(x.footer?.groups)?x.footer.groups:[];x.footer={...footerDefaults,...(x.footer||{}),groups:[...current,{id:freshId('group'),title:'Link group',links:[]}]}})};
 const removeGroup=index=>mutate(x=>{const groups=[...(x.footer?.groups||[])];groups.splice(index,1);x.footer={...footerDefaults,...(x.footer||{}),groups}});
 const patchGroup=(index,values)=>mutate(x=>{const groups=[...(x.footer?.groups||[])];groups[index]={...groups[index],...values};x.footer={...footerDefaults,...(x.footer||{}),groups}});
 const addLink=index=>{const group=footer.groups[index];if((group?.links||[]).length>=6)return;mutate(x=>{const groups=[...(x.footer?.groups||[])];const target={...groups[index],links:[...(groups[index]?.links||[]),{id:freshId('link'),label:'New link',destination:'home'}]};groups[index]=target;x.footer={...footerDefaults,...(x.footer||{}),groups}})};
 const patchLink=(groupIndex,linkIndex,values)=>mutate(x=>{const groups=[...(x.footer?.groups||[])];const links=[...(groups[groupIndex]?.links||[])];links[linkIndex]={...links[linkIndex],...values};groups[groupIndex]={...groups[groupIndex],links};x.footer={...footerDefaults,...(x.footer||{}),groups}});
 const removeLink=(groupIndex,linkIndex)=>mutate(x=>{const groups=[...(x.footer?.groups||[])];const links=[...(groups[groupIndex]?.links||[])];links.splice(linkIndex,1);groups[groupIndex]={...groups[groupIndex],links};x.footer={...footerDefaults,...(x.footer||{}),groups}});
 const addSocial=()=>{if(footer.social_links.length>=6)return;mutate(x=>{const links=Array.isArray(x.footer?.social_links)?x.footer.social_links:[];x.footer={...footerDefaults,...(x.footer||{}),social_links:[...links,{network:'instagram',url:''}]}})};
 const patchSocial=(index,values)=>mutate(x=>{const links=[...(x.footer?.social_links||[])];links[index]={...links[index],...values};x.footer={...footerDefaults,...(x.footer||{}),social_links:links}});
 const removeSocial=index=>mutate(x=>{const links=[...(x.footer?.social_links||[])];links.splice(index,1);x.footer={...footerDefaults,...(x.footer||{}),social_links:links}});
 return <div className="footer-builder-a2">
  <section className="footer-a2-section footer-a2-status"><div className="footer-a2-head"><div><strong>Storefront Footer</strong><span>Global footer rendered by the real Customer Web preview.</span></div><label className="footer-a2-switch"><input type="checkbox" checked={footer.enabled===true} onChange={e=>patch({enabled:e.target.checked})}/><span/></label></div><div className={`footer-a2-state ${footer.enabled?'on':'off'}`}><i/>{footer.enabled?'Visible on storefront':'Hidden on storefront'}</div></section>
  <section className="footer-a2-section"><div className="footer-a2-head"><div><strong>Layout & brand</strong><span>Choose one of the three Backend-approved layouts.</span></div></div><Field label="Footer layout"><select value={footer.layout} onChange={e=>patch({layout:e.target.value})}><option value="columns">Columns</option><option value="compact">Compact</option><option value="minimal">Minimal</option></select></Field><div className={`footer-a2-layout-preview ${footer.layout}`} aria-hidden="true"><i/><div><span/><span/><span/></div></div><label className="designer-check"><input type="checkbox" checked={footer.show_brand!==false} onChange={e=>patch({show_brand:e.target.checked})}/><span><strong>Show storefront brand</strong><small>Uses the existing Customer Display Name and logo.</small></span></label><Field label="Tagline" hint={`${footer.tagline.length}/240`}><textarea maxLength="240" value={footer.tagline} onChange={e=>patch({tagline:e.target.value})} placeholder="A short brand statement for the footer"/></Field></section>
  <section className="footer-a2-section"><div className="footer-a2-head"><div><strong>Link groups</strong><span>Up to four groups with six real Customer Web destinations each.</span></div><b>{footer.groups.length}/4</b></div><div className="footer-a2-groups">{footer.groups.map((group,groupIndex)=><article key={group.id||groupIndex}><div className="footer-a2-row"><input maxLength="80" value={group.title||''} onChange={e=>patchGroup(groupIndex,{title:e.target.value})} aria-label={`Footer group ${groupIndex+1} title`}/><button type="button" className="danger-mini" onClick={()=>removeGroup(groupIndex)} aria-label={`Remove footer group ${groupIndex+1}`}>×</button></div><div className="footer-a2-links">{(group.links||[]).map((link,linkIndex)=><div key={link.id||linkIndex}><input maxLength="80" value={link.label||''} onChange={e=>patchLink(groupIndex,linkIndex,{label:e.target.value})} aria-label={`Footer link ${linkIndex+1} label`}/><select value={link.destination||'home'} onChange={e=>patchLink(groupIndex,linkIndex,{destination:e.target.value})}>{destinations.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={()=>removeLink(groupIndex,linkIndex)} aria-label={`Remove footer link ${linkIndex+1}`}>×</button></div>)}</div><button type="button" className="footer-a2-add" disabled={(group.links||[]).length>=6} onClick={()=>addLink(groupIndex)}>+ Add link <span>{(group.links||[]).length}/6</span></button></article>)}</div><button type="button" className="footer-a2-add footer-a2-add-group" disabled={footer.groups.length>=4} onClick={addGroup}>+ Add link group</button></section>
  <section className="footer-a2-section"><div className="footer-a2-head"><div><strong>Social links</strong><span>Approved networks only. Production accepts HTTPS URLs only.</span></div><b>{footer.social_links.length}/6</b></div><div className="footer-a2-socials">{footer.social_links.map((social,index)=><div key={`${social.network}-${index}`}><select value={social.network||'instagram'} onChange={e=>patchSocial(index,{network:e.target.value})}>{networks.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input type="url" inputMode="url" value={social.url||''} onChange={e=>patchSocial(index,{url:e.target.value})} placeholder="https://" aria-label={`${social.network||'social'} URL`}/><button type="button" onClick={()=>removeSocial(index)} aria-label={`Remove social link ${index+1}`}>×</button></div>)}</div><button type="button" className="footer-a2-add" disabled={footer.social_links.length>=6} onClick={addSocial}>+ Add social link</button></section>
  <section className="footer-a2-section"><div className="footer-a2-head"><div><strong>Copyright</strong><span>Presentation copy only; this does not create legal-policy pages.</span></div></div><label className="designer-check"><input type="checkbox" checked={footer.show_copyright!==false} onChange={e=>patch({show_copyright:e.target.checked})}/><span><strong>Show copyright line</strong><small>If blank, Customer Web uses the current year and store name.</small></span></label><Field label="Custom copyright" hint={`${footer.copyright_text.length}/180`}><input maxLength="180" disabled={footer.show_copyright===false} value={footer.copyright_text} onChange={e=>patch({copyright_text:e.target.value})} placeholder="Optional custom copyright text"/></Field></section>
  <div className="footer-a2-safety"><strong>Contract boundary</strong><span>Footer links use approved storefront destinations. Arbitrary HTML, scripts, payment content, delivery promises and fabricated legal routes are intentionally unavailable.</span></div>
 </div>
}
