import React, { useEffect } from 'react';

export const cn=(...x)=>x.filter(Boolean).join(' ');
export function Badge({children,tone='neutral'}){return <span className={`badge badge-${tone}`}>{children}</span>}
export function statusTone(s=''){const x=String(s).toUpperCase();if(['ACTIVE','PAID','PUBLISHED','DELIVERED','COMPLETED','READY','SUCCEEDED'].includes(x))return'success';if(['FAILED','BLOCKED','DISABLED','CANCELLED','REFUNDED','INACTIVE','ARCHIVED','EXPIRED'].includes(x))return'danger';if(['SUSPENDED','PENDING','PENDING_PAYMENT','PROCESSING','PREPARING','DRAFT','PAUSED','REFUND_PENDING','SCHEDULED'].includes(x))return'warning';return'neutral'}
export function PageHeader({eyebrow='Luke Shop',title,description,actions}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div>}
export function Card({title,subtitle,children,className=''}){return <section className={`card ${className}`}><div className="card-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section>}
export function Stat({label,value,detail}){return <div className="stat"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>}
export function Empty({title='Nothing here yet',description='There is no data to show.'}){return <div className="empty"><div className="empty-icon">◇</div><strong>{title}</strong><span>{description}</span></div>}
export function Loading(){return <div className="loading"><i/><span>Loading…</span></div>}
export function ErrorBox({error}){if(!error)return null;return <div className="alert alert-error"><strong>{error.code||'Request failed'}</strong><span>{error.message}</span>{error.requestId&&<small>Request: {error.requestId}</small>}</div>}
export function PermissionNote({permission}){return <div className="alert"><strong>Permission required</strong><span>Your merchant role does not include <code>{permission}</code>.</span></div>}
export function Money({value,currency='USD'}){const n=Number(value||0);return <>{new Intl.NumberFormat(undefined,{style:'currency',currency}).format(n)}</>}
export function DateTime({value}){return <>{value?new Date(value).toLocaleString():'—'}</>}
export function Field({label,hint,children}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Modal({open,onClose,title,children,footer,size='md'}){if(!open)return null;return <div className="modal-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><div className={`modal modal-${size}`}><div className="modal-head"><div><div className="eyebrow">Luke Shop</div><h2>{title}</h2></div><button className="icon-btn" onClick={onClose} aria-label="Close">×</button></div><div className="modal-body">{children}</div>{footer&&<div className="modal-foot">{footer}</div>}</div></div>}
export function Toast({message,onDone}){useEffect(()=>{if(!message)return;const t=setTimeout(onDone,3200);return()=>clearTimeout(t)},[message,onDone]);if(!message)return null;return <div className="toast">{message}</div>}
export function SearchBar({value,onChange,placeholder='Search'}){return <div className="search"><span>⌕</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function Table({columns,rows,keyField='id',emptyTitle}){if(!rows?.length)return <Empty title={emptyTitle||'No records'}/>;return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r[keyField]||r.public_id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):r[c.key]??'—'}</td>)}</tr>)}</tbody></table></div>}
export function Tabs({value,onChange,items}){return <div className="tabs">{items.map(i=><button key={i.value} className={value===i.value?'active':''} onClick={()=>onChange(i.value)}>{i.label}{i.count!==undefined&&<span>{i.count}</span>}</button>)}</div>}
export function KeyValue({label,children}){return <div className="kv"><span>{label}</span><strong>{children??'—'}</strong></div>}


export function humanizeKey(value=''){return String(value).replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
export function FriendlyObject({value,empty='No additional details'}){const entries=Object.entries(value||{}).filter(([,v])=>v!==null&&v!==undefined&&v!=='');if(!entries.length)return <span className="muted">{empty}</span>;return <div className="friendly-object">{entries.map(([k,v])=><div key={k}><span>{humanizeKey(k)}</span><strong>{typeof v==='boolean'?(v?'Yes':'No'):Array.isArray(v)?v.join(', '):typeof v==='object'?Object.entries(v).map(([a,b])=>`${humanizeKey(a)}: ${String(b)}`).join(' · '):String(v)}</strong></div>)}</div>}

function zoneParts(iso,timeZone){if(!iso)return{date:'',time:''};try{const d=new Date(iso);const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`}}catch{return{date:'',time:''}}}
function zoneLocalToIso(date,time,timeZone){if(!date||!time)return null;const[y,m,d]=date.split('-').map(Number),[hh,mm]=time.split(':').map(Number);let guess=Date.UTC(y,m-1,d,hh,mm,0);for(let i=0;i<2;i++){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess)).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));const shown=Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day),Number(parts.hour),Number(parts.minute),Number(parts.second));guess-=shown-Date.UTC(y,m-1,d,hh,mm,0)}return new Date(guess).toISOString()}
export function DateTimePicker({label,value,onChange,timeZone='UTC',clearable=true}){const initial=zoneParts(value,timeZone);const[open,setOpen]=React.useState(false),[date,setDate]=React.useState(initial.date),[time,setTime]=React.useState(initial.time||'09:00'),[month,setMonth]=React.useState(()=>initial.date?new Date(`${initial.date}T00:00:00`):new Date());React.useEffect(()=>{const x=zoneParts(value,timeZone);setDate(x.date);setTime(x.time||'09:00');if(x.date)setMonth(new Date(`${x.date}T00:00:00`))},[value,timeZone]);const days=React.useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,total=new Date(y,m+1,0).getDate(),out=[];for(let i=0;i<start;i++)out.push(null);for(let n=1;n<=total;n++)out.push(n);return out},[month]);const choose=n=>{if(!n)return;const v=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;setDate(v)};const apply=()=>{onChange(zoneLocalToIso(date,time,timeZone));setOpen(false)};return <Field label={label} hint={`Timezone: ${timeZone}`}><div className="datetime-picker"><button type="button" className="datetime-trigger" onClick={()=>setOpen(!open)}>{value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone}).format(new Date(value)):'Choose date & time'}<span>▣</span></button>{open&&<div className="calendar-popover"><div className="calendar-head"><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{month.toLocaleString(undefined,{month:'long',year:'numeric'})}</strong><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="calendar-week"><span>Mo</span><span>Tu</span><span>We</span><span>Th</span><span>Fr</span><span>Sa</span><span>Su</span></div><div className="calendar-grid">{days.map((n,i)=>n?<button type="button" key={i} className={date===`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`?'selected':''} onClick={()=>choose(n)}>{n}</button>:<span key={i}/>)}</div><div className="calendar-time"><span>Time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></div><div className="calendar-actions">{clearable&&<button type="button" className="secondary small" onClick={()=>{setDate('');onChange(null);setOpen(false)}}>Clear</button>}<button type="button" className="primary small" disabled={!date||!time} onClick={apply}>Apply</button></div></div>}</div></Field>}
