import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{VbenAlert,VbenBadge,VbenButton,VbenCard,VbenDateTime,VbenField,VbenInput,VbenSelect,VbenSkeleton,VbenSwitch,VbenTextarea,VbenToast}from'./VbenUI.jsx';

const errorText=error=>error?`${error.code||'Request failed'}: ${error.message||String(error)}${error.requestId?` · ${error.requestId}`:''}`:'';
const newRequestKey=()=>{const random=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;return`vip-manual-${random.replace(/[^A-Za-z0-9._:-]/g,'')}`.slice(0,120)};

export function VipIssuanceControls(){
 const{api,has,session}=useAuth();
 const[policy,setPolicy]=useState(null),[store,setStore]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState(null),[toast,setToast]=useState('');
 const[requested,setRequested]=useState(false),[limit,setLimit]=useState('5000'),[summary,setSummary]=useState(null),[benefits,setBenefits]=useState([]);
 const[manual,setManual]=useState({customer_ref:'',benefit_id:'',reason:''}),[manualBusy,setManualBusy]=useState(false),[manualResult,setManualResult]=useState(null),[requestKey,setRequestKey]=useState(newRequestKey);
 const canManage=has('loyalty.manage');
 const manualBenefits=useMemo(()=>benefits.filter(item=>item.status==='ACTIVE'&&item.frequency==='MANUAL'&&['VOUCHER','GIFT'].includes(item.benefit_type)),[benefits]);

 const syncPolicy=value=>{setPolicy(value||null);setRequested(!!value?.recurring_entitlement_issuance_enabled)};
 const load=async()=>{setLoading(true);setError(null);try{const[p,o]=await Promise.all([api.request('/v1/merchant/vip/issuance-policy'),api.request('/v1/merchant/vip/overview')]);setStore(p.data.store||null);syncPolicy(p.data.policy);setBenefits(o.data.benefits||[])}catch(e){setError(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[session?.storeId]);
 useEffect(()=>{if(manual.benefit_id&&!manualBenefits.some(item=>item.id===manual.benefit_id))setManual(v=>({...v,benefit_id:''}))},[manualBenefits,manual.benefit_id]);

 const savePolicy=async()=>{setSaving(true);setError(null);try{const result=await api.request('/v1/merchant/vip/issuance-policy',{method:'PUT',body:{recurring_entitlement_issuance_enabled:requested}});syncPolicy(result.data.policy);setToast('Recurring entitlement issuance policy saved')}catch(e){setError(e)}finally{setSaving(false)}};
 const runNow=async()=>{const bounded=Number(limit);if(!Number.isInteger(bounded)||bounded<1||bounded>5000){setError({code:'VIP_ISSUANCE_LIMIT_INVALID',message:'Run limit must be an integer from 1 to 5,000.'});return}setRunning(true);setError(null);try{const result=await api.request('/v1/merchant/vip/issuance/run',{method:'POST',body:{limit:bounded}});setSummary(result.data.summary||null);setToast('Recurring entitlement run completed')}catch(e){setError(e)}finally{setRunning(false)}};
 const issueManual=async()=>{const customerRef=manual.customer_ref.trim(),benefitId=manual.benefit_id.trim(),reason=manual.reason.trim();if(!customerRef||!benefitId||reason.length<3){setError({code:'VIP_MANUAL_ISSUANCE_INPUT_REQUIRED',message:'Customer, manual benefit and a reason of at least 3 characters are required.'});return}setManualBusy(true);setError(null);setManualResult(null);const usedKey=requestKey;try{const result=await api.request(`/v1/merchant/vip/members/${encodeURIComponent(customerRef)}/entitlements/issue`,{method:'POST',body:{benefit_id:benefitId,request_key:usedKey,reason}});setManualResult({...result.data,request_key:usedKey});if(result.data.created)setRequestKey(newRequestKey());setToast(result.data.created?'Manual VIP entitlement issued':'Existing manual issuance returned safely')}catch(e){setError(e)}finally{setManualBusy(false)}};

 const effective=!!policy?.enabled,programEnabled=!!policy?.program_enabled;
 return <VbenCard title="Voucher & gift issuance" description="Store-scoped recurring and manual entitlement operations. Backend validates current VIP level, benefit eligibility, issuance keys and entitlement state.">
  {loading?<VbenSkeleton lines={7}/>:<div className="vip-redemption-policy-card" data-testid="vip-issuance-controls">
   <div className="vip-redemption-policy-status"><div><span className="vip-redemption-store-label">Working store</span><strong>{store?.name||session?.storeId||'Current store'}</strong><small className="vip-table-sub">Timezone: {policy?.timezone||'UTC'}</small></div><div className="vip-redemption-badges"><VbenBadge tone={programEnabled?'success':'warning'}>{programEnabled?'VIP PROGRAM ON':'VIP PROGRAM OFF'}</VbenBadge><VbenBadge tone={effective?'success':requested?'warning':'neutral'}>{effective?'RECURRING ACTIVE':requested?'WAITING FOR VIP PROGRAM':'RECURRING OFF'}</VbenBadge></div></div>
   {error&&<VbenAlert tone="danger" title={error.code||'VIP issuance request failed'}>{errorText(error)}</VbenAlert>}
   {!programEnabled&&requested&&<VbenAlert tone="warning" title="VIP program is disabled">The recurring switch is stored for this working store, but issuance remains ineffective until the VIP program is enabled. Backend enforces this relationship.</VbenAlert>}
   <VbenSwitch checked={requested} onChange={setRequested} label="Enable recurring voucher & gift issuance" description="Disabled by default. Supports tier-entry, monthly, annual and birthday VOUCHER/GIFT benefits after Backend migration 034 is deployed." disabled={!canManage}/>
   <div className="vip-redemption-authority-note"><strong>Production scheduler boundary</strong><span>Recurring execution belongs on the Backend server using the vip:issue-recurring command. Merchant Admin never creates browser timers or becomes the authority for scheduled rewards.</span></div>
   <div className="vip-form-grid"><VbenField label="Enabled since" hint="Tier-entry issuance does not backfill tier events from before this timestamp."><div className="readonly-field">{policy?.enabled_at?<VbenDateTime value={policy.enabled_at}/>:<span>Not enabled</span>}</div></VbenField><VbenField label="Run-now customer limit" hint="Operational fallback and verification tool. Maximum 5,000 per run."><VbenInput type="number" min="1" max="5000" step="1" value={limit} disabled={!canManage} onChange={e=>setLimit(e.target.value)}/></VbenField></div>
   {canManage&&<div className="vip-member-actions"><VbenButton variant="secondary" loading={saving} onClick={savePolicy}>Save issuance policy</VbenButton><VbenButton loading={running} onClick={runNow}>Run recurring issuance now</VbenButton></div>}
   {summary&&<VbenAlert tone={summary.enabled?'success':'warning'} title={summary.enabled?'Recurring run summary':'Recurring issuance is not effective'}><div>Processed {summary.processed_members||0} member(s) · issued {summary.issued||0} · already issued {summary.already_issued||0} · expired {summary.expired||0}.</div><div>Tier entry {summary.by_frequency?.TIER_ENTRY||0} · monthly {summary.by_frequency?.MONTHLY||0} · annual {summary.by_frequency?.ANNUAL||0} · birthday {summary.by_frequency?.BIRTHDAY||0}.</div></VbenAlert>}

   <div className="vip-redemption-authority-note"><strong>Manual entitlement issuance</strong><span>Select an active MANUAL voucher or gift. Backend confirms the customer’s current VIP level and rejects ineligible benefits. The request key is kept stable across retries to prevent duplicate grants.</span></div>
   {!manualBenefits.length&&<VbenAlert tone="warning" title="No manual voucher/gift benefit is active">Create an active VOUCHER or GIFT benefit with frequency MANUAL in Benefits & Rules before issuing one to a customer.</VbenAlert>}
   <div className="vip-form-grid"><VbenField label="Customer ID" hint="Customer public ID or readable customer code."><VbenInput value={manual.customer_ref} disabled={!canManage} placeholder="CUS... or member code" onChange={e=>setManual(v=>({...v,customer_ref:e.target.value}))}/></VbenField><VbenField label="Manual benefit"><VbenSelect value={manual.benefit_id} disabled={!canManage||!manualBenefits.length} onChange={e=>setManual(v=>({...v,benefit_id:e.target.value}))}><option value="">Select manual benefit</option>{manualBenefits.map(item=><option key={item.id} value={item.id}>{item.name} · {item.level_name||item.level_id||'VIP level'} · {item.benefit_type}</option>)}</VbenSelect></VbenField></div>
   <VbenField label="Issuance reason" hint="Required audit reason, 3–1,000 characters."><VbenTextarea rows="3" maxLength="1000" disabled={!canManage} value={manual.reason} onChange={e=>setManual(v=>({...v,reason:e.target.value}))}/></VbenField>
   <VbenField label="Retry-safe request key" hint="Keep this key for retries. Generate a new key only for a genuinely new grant request."><VbenInput readOnly value={requestKey}/></VbenField>
   {canManage&&<div className="vip-member-actions"><VbenButton variant="secondary" disabled={manualBusy} onClick={()=>{setRequestKey(newRequestKey());setManualResult(null)}}>New request key</VbenButton><VbenButton loading={manualBusy} disabled={!manualBenefits.length||!manual.customer_ref.trim()||!manual.benefit_id||manual.reason.trim().length<3} onClick={issueManual}>Issue entitlement</VbenButton></div>}
   {manualResult&&<VbenAlert tone={manualResult.created?'success':'info'} title={manualResult.created?'Entitlement issued':'Idempotent existing entitlement returned'}><div>{manualResult.customer?.display_name||manualResult.customer?.customer_code||manualResult.customer?.id||'Customer'} · {manualResult.entitlement?.benefit_name||manualResult.entitlement?.benefit_id||'Manual benefit'} · {manualResult.entitlement?.status||'UNKNOWN'}</div><div>Request key: <code>{manualResult.request_key}</code>{manualResult.entitlement?.redeem_code?<> · Code: <code>{manualResult.entitlement.redeem_code}</code></>:null}</div></VbenAlert>}
  </div>}
  <VbenToast message={toast} onDone={()=>setToast('')}/>
 </VbenCard>;
}
